package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentAccountInfoExample {
    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public AgentAccountInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_agent_account_info
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_account_info
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAgentCdIsNull() {
            addCriterion("`agent_cd` is null");
            return (Criteria) this;
        }

        public Criteria andAgentCdIsNotNull() {
            addCriterion("`agent_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCdEqualTo(String value) {
            addCriterion("`agent_cd` =", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotEqualTo(String value) {
            addCriterion("`agent_cd` <>", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThan(String value) {
            addCriterion("`agent_cd` >", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_cd` >=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThan(String value) {
            addCriterion("`agent_cd` <", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThanOrEqualTo(String value) {
            addCriterion("`agent_cd` <=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLike(String value) {
            addCriterion("`agent_cd` like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotLike(String value) {
            addCriterion("`agent_cd` not like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdIn(List<String> values) {
            addCriterion("`agent_cd` in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotIn(List<String> values) {
            addCriterion("`agent_cd` not in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdBetween(String value1, String value2) {
            addCriterion("`agent_cd` between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotBetween(String value1, String value2) {
            addCriterion("`agent_cd` not between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIsNull() {
            addCriterion("`account_type` is null");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIsNotNull() {
            addCriterion("`account_type` is not null");
            return (Criteria) this;
        }

        public Criteria andAccountTypeEqualTo(String value) {
            addCriterion("`account_type` =", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotEqualTo(String value) {
            addCriterion("`account_type` <>", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeGreaterThan(String value) {
            addCriterion("`account_type` >", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`account_type` >=", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLessThan(String value) {
            addCriterion("`account_type` <", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLessThanOrEqualTo(String value) {
            addCriterion("`account_type` <=", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLike(String value) {
            addCriterion("`account_type` like", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotLike(String value) {
            addCriterion("`account_type` not like", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIn(List<String> values) {
            addCriterion("`account_type` in", values, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotIn(List<String> values) {
            addCriterion("`account_type` not in", values, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeBetween(String value1, String value2) {
            addCriterion("`account_type` between", value1, value2, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotBetween(String value1, String value2) {
            addCriterion("`account_type` not between", value1, value2, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountNoIsNull() {
            addCriterion("`account_no` is null");
            return (Criteria) this;
        }

        public Criteria andAccountNoIsNotNull() {
            addCriterion("`account_no` is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNoEqualTo(String value) {
            addCriterion("`account_no` =", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotEqualTo(String value) {
            addCriterion("`account_no` <>", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoGreaterThan(String value) {
            addCriterion("`account_no` >", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoGreaterThanOrEqualTo(String value) {
            addCriterion("`account_no` >=", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLessThan(String value) {
            addCriterion("`account_no` <", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLessThanOrEqualTo(String value) {
            addCriterion("`account_no` <=", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoLike(String value) {
            addCriterion("`account_no` like", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotLike(String value) {
            addCriterion("`account_no` not like", value, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoIn(List<String> values) {
            addCriterion("`account_no` in", values, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotIn(List<String> values) {
            addCriterion("`account_no` not in", values, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoBetween(String value1, String value2) {
            addCriterion("`account_no` between", value1, value2, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNoNotBetween(String value1, String value2) {
            addCriterion("`account_no` not between", value1, value2, "accountNo");
            return (Criteria) this;
        }

        public Criteria andAccountNameIsNull() {
            addCriterion("`account_name` is null");
            return (Criteria) this;
        }

        public Criteria andAccountNameIsNotNull() {
            addCriterion("`account_name` is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNameEqualTo(String value) {
            addCriterion("`account_name` =", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotEqualTo(String value) {
            addCriterion("`account_name` <>", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameGreaterThan(String value) {
            addCriterion("`account_name` >", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("`account_name` >=", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLessThan(String value) {
            addCriterion("`account_name` <", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLessThanOrEqualTo(String value) {
            addCriterion("`account_name` <=", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameLike(String value) {
            addCriterion("`account_name` like", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotLike(String value) {
            addCriterion("`account_name` not like", value, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameIn(List<String> values) {
            addCriterion("`account_name` in", values, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotIn(List<String> values) {
            addCriterion("`account_name` not in", values, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameBetween(String value1, String value2) {
            addCriterion("`account_name` between", value1, value2, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountNameNotBetween(String value1, String value2) {
            addCriterion("`account_name` not between", value1, value2, "accountName");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeIsNull() {
            addCriterion("`account_bank_code` is null");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeIsNotNull() {
            addCriterion("`account_bank_code` is not null");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeEqualTo(String value) {
            addCriterion("`account_bank_code` =", value, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeNotEqualTo(String value) {
            addCriterion("`account_bank_code` <>", value, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeGreaterThan(String value) {
            addCriterion("`account_bank_code` >", value, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeGreaterThanOrEqualTo(String value) {
            addCriterion("`account_bank_code` >=", value, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeLessThan(String value) {
            addCriterion("`account_bank_code` <", value, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeLessThanOrEqualTo(String value) {
            addCriterion("`account_bank_code` <=", value, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeLike(String value) {
            addCriterion("`account_bank_code` like", value, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeNotLike(String value) {
            addCriterion("`account_bank_code` not like", value, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeIn(List<String> values) {
            addCriterion("`account_bank_code` in", values, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeNotIn(List<String> values) {
            addCriterion("`account_bank_code` not in", values, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeBetween(String value1, String value2) {
            addCriterion("`account_bank_code` between", value1, value2, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankCodeNotBetween(String value1, String value2) {
            addCriterion("`account_bank_code` not between", value1, value2, "accountBankCode");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameIsNull() {
            addCriterion("`account_bank_name` is null");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameIsNotNull() {
            addCriterion("`account_bank_name` is not null");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameEqualTo(String value) {
            addCriterion("`account_bank_name` =", value, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameNotEqualTo(String value) {
            addCriterion("`account_bank_name` <>", value, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameGreaterThan(String value) {
            addCriterion("`account_bank_name` >", value, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("`account_bank_name` >=", value, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameLessThan(String value) {
            addCriterion("`account_bank_name` <", value, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameLessThanOrEqualTo(String value) {
            addCriterion("`account_bank_name` <=", value, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameLike(String value) {
            addCriterion("`account_bank_name` like", value, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameNotLike(String value) {
            addCriterion("`account_bank_name` not like", value, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameIn(List<String> values) {
            addCriterion("`account_bank_name` in", values, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameNotIn(List<String> values) {
            addCriterion("`account_bank_name` not in", values, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameBetween(String value1, String value2) {
            addCriterion("`account_bank_name` between", value1, value2, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andAccountBankNameNotBetween(String value1, String value2) {
            addCriterion("`account_bank_name` not between", value1, value2, "accountBankName");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("`priority` is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("`priority` is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("`priority` =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("`priority` <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("`priority` >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("`priority` >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("`priority` <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("`priority` <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("`priority` in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("`priority` not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("`priority` between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("`priority` not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("`weight` is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("`weight` is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("`weight` =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("`weight` <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("`weight` >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("`weight` >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("`weight` <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("`weight` <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("`weight` in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("`weight` not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("`weight` between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("`weight` not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtIsNull() {
            addCriterion("`max_card_amt` is null");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtIsNotNull() {
            addCriterion("`max_card_amt` is not null");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtEqualTo(Long value) {
            addCriterion("`max_card_amt` =", value, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtNotEqualTo(Long value) {
            addCriterion("`max_card_amt` <>", value, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtGreaterThan(Long value) {
            addCriterion("`max_card_amt` >", value, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtGreaterThanOrEqualTo(Long value) {
            addCriterion("`max_card_amt` >=", value, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtLessThan(Long value) {
            addCriterion("`max_card_amt` <", value, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtLessThanOrEqualTo(Long value) {
            addCriterion("`max_card_amt` <=", value, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtIn(List<Long> values) {
            addCriterion("`max_card_amt` in", values, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtNotIn(List<Long> values) {
            addCriterion("`max_card_amt` not in", values, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtBetween(Long value1, Long value2) {
            addCriterion("`max_card_amt` between", value1, value2, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andMaxCardAmtNotBetween(Long value1, Long value2) {
            addCriterion("`max_card_amt` not between", value1, value2, "maxCardAmt");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("`comment` is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("`comment` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("`comment` =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("`comment` <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("`comment` >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("`comment` >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("`comment` <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("`comment` <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("`comment` like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("`comment` not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("`comment` in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("`comment` not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("`comment` between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("`comment` not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andSysMacIsNull() {
            addCriterion("`sys_mac` is null");
            return (Criteria) this;
        }

        public Criteria andSysMacIsNotNull() {
            addCriterion("`sys_mac` is not null");
            return (Criteria) this;
        }

        public Criteria andSysMacEqualTo(String value) {
            addCriterion("`sys_mac` =", value, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacNotEqualTo(String value) {
            addCriterion("`sys_mac` <>", value, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacGreaterThan(String value) {
            addCriterion("`sys_mac` >", value, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacGreaterThanOrEqualTo(String value) {
            addCriterion("`sys_mac` >=", value, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacLessThan(String value) {
            addCriterion("`sys_mac` <", value, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacLessThanOrEqualTo(String value) {
            addCriterion("`sys_mac` <=", value, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacLike(String value) {
            addCriterion("`sys_mac` like", value, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacNotLike(String value) {
            addCriterion("`sys_mac` not like", value, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacIn(List<String> values) {
            addCriterion("`sys_mac` in", values, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacNotIn(List<String> values) {
            addCriterion("`sys_mac` not in", values, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacBetween(String value1, String value2) {
            addCriterion("`sys_mac` between", value1, value2, "sysMac");
            return (Criteria) this;
        }

        public Criteria andSysMacNotBetween(String value1, String value2) {
            addCriterion("`sys_mac` not between", value1, value2, "sysMac");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNull() {
            addCriterion("`last_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNotNull() {
            addCriterion("`last_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdEqualTo(String value) {
            addCriterion("`last_oper_id` =", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotEqualTo(String value) {
            addCriterion("`last_oper_id` <>", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThan(String value) {
            addCriterion("`last_oper_id` >", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` >=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThan(String value) {
            addCriterion("`last_oper_id` <", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` <=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLike(String value) {
            addCriterion("`last_oper_id` like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotLike(String value) {
            addCriterion("`last_oper_id` not like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIn(List<String> values) {
            addCriterion("`last_oper_id` in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotIn(List<String> values) {
            addCriterion("`last_oper_id` not in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdBetween(String value1, String value2) {
            addCriterion("`last_oper_id` between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotBetween(String value1, String value2) {
            addCriterion("`last_oper_id` not between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_account_info
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_account_info
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}