package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BmRoleInfoExample {
    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public BmRoleInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_bm_role_info
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_bm_role_info
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("`role_id` is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("`role_id` is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("`role_id` =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("`role_id` <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("`role_id` >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`role_id` >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("`role_id` <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("`role_id` <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Integer> values) {
            addCriterion("`role_id` in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Integer> values) {
            addCriterion("`role_id` not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("`role_id` between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`role_id` not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleNmIsNull() {
            addCriterion("`role_nm` is null");
            return (Criteria) this;
        }

        public Criteria andRoleNmIsNotNull() {
            addCriterion("`role_nm` is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNmEqualTo(String value) {
            addCriterion("`role_nm` =", value, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmNotEqualTo(String value) {
            addCriterion("`role_nm` <>", value, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmGreaterThan(String value) {
            addCriterion("`role_nm` >", value, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmGreaterThanOrEqualTo(String value) {
            addCriterion("`role_nm` >=", value, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmLessThan(String value) {
            addCriterion("`role_nm` <", value, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmLessThanOrEqualTo(String value) {
            addCriterion("`role_nm` <=", value, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmLike(String value) {
            addCriterion("`role_nm` like", value, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmNotLike(String value) {
            addCriterion("`role_nm` not like", value, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmIn(List<String> values) {
            addCriterion("`role_nm` in", values, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmNotIn(List<String> values) {
            addCriterion("`role_nm` not in", values, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmBetween(String value1, String value2) {
            addCriterion("`role_nm` between", value1, value2, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleNmNotBetween(String value1, String value2) {
            addCriterion("`role_nm` not between", value1, value2, "roleNm");
            return (Criteria) this;
        }

        public Criteria andRoleStIsNull() {
            addCriterion("`role_st` is null");
            return (Criteria) this;
        }

        public Criteria andRoleStIsNotNull() {
            addCriterion("`role_st` is not null");
            return (Criteria) this;
        }

        public Criteria andRoleStEqualTo(String value) {
            addCriterion("`role_st` =", value, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStNotEqualTo(String value) {
            addCriterion("`role_st` <>", value, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStGreaterThan(String value) {
            addCriterion("`role_st` >", value, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStGreaterThanOrEqualTo(String value) {
            addCriterion("`role_st` >=", value, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStLessThan(String value) {
            addCriterion("`role_st` <", value, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStLessThanOrEqualTo(String value) {
            addCriterion("`role_st` <=", value, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStLike(String value) {
            addCriterion("`role_st` like", value, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStNotLike(String value) {
            addCriterion("`role_st` not like", value, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStIn(List<String> values) {
            addCriterion("`role_st` in", values, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStNotIn(List<String> values) {
            addCriterion("`role_st` not in", values, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStBetween(String value1, String value2) {
            addCriterion("`role_st` between", value1, value2, "roleSt");
            return (Criteria) this;
        }

        public Criteria andRoleStNotBetween(String value1, String value2) {
            addCriterion("`role_st` not between", value1, value2, "roleSt");
            return (Criteria) this;
        }

        public Criteria andGrpNoIsNull() {
            addCriterion("`grp_no` is null");
            return (Criteria) this;
        }

        public Criteria andGrpNoIsNotNull() {
            addCriterion("`grp_no` is not null");
            return (Criteria) this;
        }

        public Criteria andGrpNoEqualTo(String value) {
            addCriterion("`grp_no` =", value, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoNotEqualTo(String value) {
            addCriterion("`grp_no` <>", value, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoGreaterThan(String value) {
            addCriterion("`grp_no` >", value, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoGreaterThanOrEqualTo(String value) {
            addCriterion("`grp_no` >=", value, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoLessThan(String value) {
            addCriterion("`grp_no` <", value, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoLessThanOrEqualTo(String value) {
            addCriterion("`grp_no` <=", value, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoLike(String value) {
            addCriterion("`grp_no` like", value, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoNotLike(String value) {
            addCriterion("`grp_no` not like", value, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoIn(List<String> values) {
            addCriterion("`grp_no` in", values, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoNotIn(List<String> values) {
            addCriterion("`grp_no` not in", values, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoBetween(String value1, String value2) {
            addCriterion("`grp_no` between", value1, value2, "grpNo");
            return (Criteria) this;
        }

        public Criteria andGrpNoNotBetween(String value1, String value2) {
            addCriterion("`grp_no` not between", value1, value2, "grpNo");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("`department` is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("`department` is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("`department` =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("`department` <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("`department` >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("`department` >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("`department` <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("`department` <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("`department` like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("`department` not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("`department` in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("`department` not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("`department` between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("`department` not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_bm_role_info
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_bm_role_info
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}