package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BusCheckTaskExample {
    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public BusCheckTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_bus_check_task
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_bus_check_task
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("`task_id` is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("`task_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Integer value) {
            addCriterion("`task_id` =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Integer value) {
            addCriterion("`task_id` <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Integer value) {
            addCriterion("`task_id` >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`task_id` >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Integer value) {
            addCriterion("`task_id` <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("`task_id` <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Integer> values) {
            addCriterion("`task_id` in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Integer> values) {
            addCriterion("`task_id` not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("`task_id` between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`task_id` not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andSysIdIsNull() {
            addCriterion("`sys_id` is null");
            return (Criteria) this;
        }

        public Criteria andSysIdIsNotNull() {
            addCriterion("`sys_id` is not null");
            return (Criteria) this;
        }

        public Criteria andSysIdEqualTo(String value) {
            addCriterion("`sys_id` =", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotEqualTo(String value) {
            addCriterion("`sys_id` <>", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThan(String value) {
            addCriterion("`sys_id` >", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThanOrEqualTo(String value) {
            addCriterion("`sys_id` >=", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLessThan(String value) {
            addCriterion("`sys_id` <", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLessThanOrEqualTo(String value) {
            addCriterion("`sys_id` <=", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLike(String value) {
            addCriterion("`sys_id` like", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotLike(String value) {
            addCriterion("`sys_id` not like", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdIn(List<String> values) {
            addCriterion("`sys_id` in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotIn(List<String> values) {
            addCriterion("`sys_id` not in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdBetween(String value1, String value2) {
            addCriterion("`sys_id` between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotBetween(String value1, String value2) {
            addCriterion("`sys_id` not between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andTaskTpIsNull() {
            addCriterion("`task_tp` is null");
            return (Criteria) this;
        }

        public Criteria andTaskTpIsNotNull() {
            addCriterion("`task_tp` is not null");
            return (Criteria) this;
        }

        public Criteria andTaskTpEqualTo(String value) {
            addCriterion("`task_tp` =", value, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpNotEqualTo(String value) {
            addCriterion("`task_tp` <>", value, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpGreaterThan(String value) {
            addCriterion("`task_tp` >", value, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpGreaterThanOrEqualTo(String value) {
            addCriterion("`task_tp` >=", value, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpLessThan(String value) {
            addCriterion("`task_tp` <", value, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpLessThanOrEqualTo(String value) {
            addCriterion("`task_tp` <=", value, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpLike(String value) {
            addCriterion("`task_tp` like", value, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpNotLike(String value) {
            addCriterion("`task_tp` not like", value, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpIn(List<String> values) {
            addCriterion("`task_tp` in", values, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpNotIn(List<String> values) {
            addCriterion("`task_tp` not in", values, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpBetween(String value1, String value2) {
            addCriterion("`task_tp` between", value1, value2, "taskTp");
            return (Criteria) this;
        }

        public Criteria andTaskTpNotBetween(String value1, String value2) {
            addCriterion("`task_tp` not between", value1, value2, "taskTp");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("`oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("`oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("`oper_id` =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("`oper_id` <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("`oper_id` >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`oper_id` >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("`oper_id` <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("`oper_id` <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("`oper_id` like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("`oper_id` not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("`oper_id` in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("`oper_id` not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("`oper_id` between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("`oper_id` not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOpTpIsNull() {
            addCriterion("`op_tp` is null");
            return (Criteria) this;
        }

        public Criteria andOpTpIsNotNull() {
            addCriterion("`op_tp` is not null");
            return (Criteria) this;
        }

        public Criteria andOpTpEqualTo(String value) {
            addCriterion("`op_tp` =", value, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpNotEqualTo(String value) {
            addCriterion("`op_tp` <>", value, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpGreaterThan(String value) {
            addCriterion("`op_tp` >", value, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpGreaterThanOrEqualTo(String value) {
            addCriterion("`op_tp` >=", value, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpLessThan(String value) {
            addCriterion("`op_tp` <", value, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpLessThanOrEqualTo(String value) {
            addCriterion("`op_tp` <=", value, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpLike(String value) {
            addCriterion("`op_tp` like", value, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpNotLike(String value) {
            addCriterion("`op_tp` not like", value, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpIn(List<String> values) {
            addCriterion("`op_tp` in", values, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpNotIn(List<String> values) {
            addCriterion("`op_tp` not in", values, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpBetween(String value1, String value2) {
            addCriterion("`op_tp` between", value1, value2, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpTpNotBetween(String value1, String value2) {
            addCriterion("`op_tp` not between", value1, value2, "opTp");
            return (Criteria) this;
        }

        public Criteria andOpDtIsNull() {
            addCriterion("`op_dt` is null");
            return (Criteria) this;
        }

        public Criteria andOpDtIsNotNull() {
            addCriterion("`op_dt` is not null");
            return (Criteria) this;
        }

        public Criteria andOpDtEqualTo(String value) {
            addCriterion("`op_dt` =", value, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtNotEqualTo(String value) {
            addCriterion("`op_dt` <>", value, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtGreaterThan(String value) {
            addCriterion("`op_dt` >", value, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtGreaterThanOrEqualTo(String value) {
            addCriterion("`op_dt` >=", value, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtLessThan(String value) {
            addCriterion("`op_dt` <", value, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtLessThanOrEqualTo(String value) {
            addCriterion("`op_dt` <=", value, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtLike(String value) {
            addCriterion("`op_dt` like", value, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtNotLike(String value) {
            addCriterion("`op_dt` not like", value, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtIn(List<String> values) {
            addCriterion("`op_dt` in", values, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtNotIn(List<String> values) {
            addCriterion("`op_dt` not in", values, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtBetween(String value1, String value2) {
            addCriterion("`op_dt` between", value1, value2, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpDtNotBetween(String value1, String value2) {
            addCriterion("`op_dt` not between", value1, value2, "opDt");
            return (Criteria) this;
        }

        public Criteria andOpTmIsNull() {
            addCriterion("`op_tm` is null");
            return (Criteria) this;
        }

        public Criteria andOpTmIsNotNull() {
            addCriterion("`op_tm` is not null");
            return (Criteria) this;
        }

        public Criteria andOpTmEqualTo(String value) {
            addCriterion("`op_tm` =", value, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmNotEqualTo(String value) {
            addCriterion("`op_tm` <>", value, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmGreaterThan(String value) {
            addCriterion("`op_tm` >", value, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmGreaterThanOrEqualTo(String value) {
            addCriterion("`op_tm` >=", value, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmLessThan(String value) {
            addCriterion("`op_tm` <", value, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmLessThanOrEqualTo(String value) {
            addCriterion("`op_tm` <=", value, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmLike(String value) {
            addCriterion("`op_tm` like", value, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmNotLike(String value) {
            addCriterion("`op_tm` not like", value, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmIn(List<String> values) {
            addCriterion("`op_tm` in", values, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmNotIn(List<String> values) {
            addCriterion("`op_tm` not in", values, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmBetween(String value1, String value2) {
            addCriterion("`op_tm` between", value1, value2, "opTm");
            return (Criteria) this;
        }

        public Criteria andOpTmNotBetween(String value1, String value2) {
            addCriterion("`op_tm` not between", value1, value2, "opTm");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdIsNull() {
            addCriterion("`check_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdIsNotNull() {
            addCriterion("`check_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdEqualTo(String value) {
            addCriterion("`check_oper_id` =", value, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdNotEqualTo(String value) {
            addCriterion("`check_oper_id` <>", value, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdGreaterThan(String value) {
            addCriterion("`check_oper_id` >", value, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`check_oper_id` >=", value, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdLessThan(String value) {
            addCriterion("`check_oper_id` <", value, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdLessThanOrEqualTo(String value) {
            addCriterion("`check_oper_id` <=", value, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdLike(String value) {
            addCriterion("`check_oper_id` like", value, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdNotLike(String value) {
            addCriterion("`check_oper_id` not like", value, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdIn(List<String> values) {
            addCriterion("`check_oper_id` in", values, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdNotIn(List<String> values) {
            addCriterion("`check_oper_id` not in", values, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdBetween(String value1, String value2) {
            addCriterion("`check_oper_id` between", value1, value2, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckOperIdNotBetween(String value1, String value2) {
            addCriterion("`check_oper_id` not between", value1, value2, "checkOperId");
            return (Criteria) this;
        }

        public Criteria andCheckTmIsNull() {
            addCriterion("`check_tm` is null");
            return (Criteria) this;
        }

        public Criteria andCheckTmIsNotNull() {
            addCriterion("`check_tm` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTmEqualTo(String value) {
            addCriterion("`check_tm` =", value, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmNotEqualTo(String value) {
            addCriterion("`check_tm` <>", value, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmGreaterThan(String value) {
            addCriterion("`check_tm` >", value, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmGreaterThanOrEqualTo(String value) {
            addCriterion("`check_tm` >=", value, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmLessThan(String value) {
            addCriterion("`check_tm` <", value, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmLessThanOrEqualTo(String value) {
            addCriterion("`check_tm` <=", value, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmLike(String value) {
            addCriterion("`check_tm` like", value, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmNotLike(String value) {
            addCriterion("`check_tm` not like", value, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmIn(List<String> values) {
            addCriterion("`check_tm` in", values, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmNotIn(List<String> values) {
            addCriterion("`check_tm` not in", values, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmBetween(String value1, String value2) {
            addCriterion("`check_tm` between", value1, value2, "checkTm");
            return (Criteria) this;
        }

        public Criteria andCheckTmNotBetween(String value1, String value2) {
            addCriterion("`check_tm` not between", value1, value2, "checkTm");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoIsNull() {
            addCriterion("`content_key_info` is null");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoIsNotNull() {
            addCriterion("`content_key_info` is not null");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoEqualTo(String value) {
            addCriterion("`content_key_info` =", value, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoNotEqualTo(String value) {
            addCriterion("`content_key_info` <>", value, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoGreaterThan(String value) {
            addCriterion("`content_key_info` >", value, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoGreaterThanOrEqualTo(String value) {
            addCriterion("`content_key_info` >=", value, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoLessThan(String value) {
            addCriterion("`content_key_info` <", value, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoLessThanOrEqualTo(String value) {
            addCriterion("`content_key_info` <=", value, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoLike(String value) {
            addCriterion("`content_key_info` like", value, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoNotLike(String value) {
            addCriterion("`content_key_info` not like", value, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoIn(List<String> values) {
            addCriterion("`content_key_info` in", values, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoNotIn(List<String> values) {
            addCriterion("`content_key_info` not in", values, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoBetween(String value1, String value2) {
            addCriterion("`content_key_info` between", value1, value2, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andContentKeyInfoNotBetween(String value1, String value2) {
            addCriterion("`content_key_info` not between", value1, value2, "contentKeyInfo");
            return (Criteria) this;
        }

        public Criteria andOperCommentsIsNull() {
            addCriterion("`oper_comments` is null");
            return (Criteria) this;
        }

        public Criteria andOperCommentsIsNotNull() {
            addCriterion("`oper_comments` is not null");
            return (Criteria) this;
        }

        public Criteria andOperCommentsEqualTo(String value) {
            addCriterion("`oper_comments` =", value, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsNotEqualTo(String value) {
            addCriterion("`oper_comments` <>", value, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsGreaterThan(String value) {
            addCriterion("`oper_comments` >", value, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("`oper_comments` >=", value, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsLessThan(String value) {
            addCriterion("`oper_comments` <", value, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsLessThanOrEqualTo(String value) {
            addCriterion("`oper_comments` <=", value, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsLike(String value) {
            addCriterion("`oper_comments` like", value, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsNotLike(String value) {
            addCriterion("`oper_comments` not like", value, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsIn(List<String> values) {
            addCriterion("`oper_comments` in", values, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsNotIn(List<String> values) {
            addCriterion("`oper_comments` not in", values, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsBetween(String value1, String value2) {
            addCriterion("`oper_comments` between", value1, value2, "operComments");
            return (Criteria) this;
        }

        public Criteria andOperCommentsNotBetween(String value1, String value2) {
            addCriterion("`oper_comments` not between", value1, value2, "operComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsIsNull() {
            addCriterion("`checker_comments` is null");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsIsNotNull() {
            addCriterion("`checker_comments` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsEqualTo(String value) {
            addCriterion("`checker_comments` =", value, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsNotEqualTo(String value) {
            addCriterion("`checker_comments` <>", value, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsGreaterThan(String value) {
            addCriterion("`checker_comments` >", value, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("`checker_comments` >=", value, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsLessThan(String value) {
            addCriterion("`checker_comments` <", value, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsLessThanOrEqualTo(String value) {
            addCriterion("`checker_comments` <=", value, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsLike(String value) {
            addCriterion("`checker_comments` like", value, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsNotLike(String value) {
            addCriterion("`checker_comments` not like", value, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsIn(List<String> values) {
            addCriterion("`checker_comments` in", values, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsNotIn(List<String> values) {
            addCriterion("`checker_comments` not in", values, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsBetween(String value1, String value2) {
            addCriterion("`checker_comments` between", value1, value2, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andCheckerCommentsNotBetween(String value1, String value2) {
            addCriterion("`checker_comments` not between", value1, value2, "checkerComments");
            return (Criteria) this;
        }

        public Criteria andTaskStIsNull() {
            addCriterion("`task_st` is null");
            return (Criteria) this;
        }

        public Criteria andTaskStIsNotNull() {
            addCriterion("`task_st` is not null");
            return (Criteria) this;
        }

        public Criteria andTaskStEqualTo(String value) {
            addCriterion("`task_st` =", value, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStNotEqualTo(String value) {
            addCriterion("`task_st` <>", value, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStGreaterThan(String value) {
            addCriterion("`task_st` >", value, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStGreaterThanOrEqualTo(String value) {
            addCriterion("`task_st` >=", value, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStLessThan(String value) {
            addCriterion("`task_st` <", value, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStLessThanOrEqualTo(String value) {
            addCriterion("`task_st` <=", value, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStLike(String value) {
            addCriterion("`task_st` like", value, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStNotLike(String value) {
            addCriterion("`task_st` not like", value, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStIn(List<String> values) {
            addCriterion("`task_st` in", values, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStNotIn(List<String> values) {
            addCriterion("`task_st` not in", values, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStBetween(String value1, String value2) {
            addCriterion("`task_st` between", value1, value2, "taskSt");
            return (Criteria) this;
        }

        public Criteria andTaskStNotBetween(String value1, String value2) {
            addCriterion("`task_st` not between", value1, value2, "taskSt");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_bus_check_task
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_bus_check_task
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}