package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentAccCheckFileExample {
    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public AgentAccCheckFileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_agent_acc_check_file
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_acc_check_file
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqIdIsNull() {
            addCriterion("`seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andSeqIdIsNotNull() {
            addCriterion("`seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andSeqIdEqualTo(Integer value) {
            addCriterion("`seq_id` =", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotEqualTo(Integer value) {
            addCriterion("`seq_id` <>", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdGreaterThan(Integer value) {
            addCriterion("`seq_id` >", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`seq_id` >=", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLessThan(Integer value) {
            addCriterion("`seq_id` <", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLessThanOrEqualTo(Integer value) {
            addCriterion("`seq_id` <=", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdIn(List<Integer> values) {
            addCriterion("`seq_id` in", values, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotIn(List<Integer> values) {
            addCriterion("`seq_id` not in", values, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdBetween(Integer value1, Integer value2) {
            addCriterion("`seq_id` between", value1, value2, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`seq_id` not between", value1, value2, "seqId");
            return (Criteria) this;
        }

        public Criteria andAgentCdIsNull() {
            addCriterion("`agent_cd` is null");
            return (Criteria) this;
        }

        public Criteria andAgentCdIsNotNull() {
            addCriterion("`agent_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCdEqualTo(String value) {
            addCriterion("`agent_cd` =", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotEqualTo(String value) {
            addCriterion("`agent_cd` <>", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThan(String value) {
            addCriterion("`agent_cd` >", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_cd` >=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThan(String value) {
            addCriterion("`agent_cd` <", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThanOrEqualTo(String value) {
            addCriterion("`agent_cd` <=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLike(String value) {
            addCriterion("`agent_cd` like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotLike(String value) {
            addCriterion("`agent_cd` not like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdIn(List<String> values) {
            addCriterion("`agent_cd` in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotIn(List<String> values) {
            addCriterion("`agent_cd` not in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdBetween(String value1, String value2) {
            addCriterion("`agent_cd` between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotBetween(String value1, String value2) {
            addCriterion("`agent_cd` not between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andSettleDtIsNull() {
            addCriterion("`settle_dt` is null");
            return (Criteria) this;
        }

        public Criteria andSettleDtIsNotNull() {
            addCriterion("`settle_dt` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleDtEqualTo(String value) {
            addCriterion("`settle_dt` =", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtNotEqualTo(String value) {
            addCriterion("`settle_dt` <>", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtGreaterThan(String value) {
            addCriterion("`settle_dt` >", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_dt` >=", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtLessThan(String value) {
            addCriterion("`settle_dt` <", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtLessThanOrEqualTo(String value) {
            addCriterion("`settle_dt` <=", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtLike(String value) {
            addCriterion("`settle_dt` like", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtNotLike(String value) {
            addCriterion("`settle_dt` not like", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtIn(List<String> values) {
            addCriterion("`settle_dt` in", values, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtNotIn(List<String> values) {
            addCriterion("`settle_dt` not in", values, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtBetween(String value1, String value2) {
            addCriterion("`settle_dt` between", value1, value2, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtNotBetween(String value1, String value2) {
            addCriterion("`settle_dt` not between", value1, value2, "settleDt");
            return (Criteria) this;
        }

        public Criteria andTransNumIsNull() {
            addCriterion("`trans_num` is null");
            return (Criteria) this;
        }

        public Criteria andTransNumIsNotNull() {
            addCriterion("`trans_num` is not null");
            return (Criteria) this;
        }

        public Criteria andTransNumEqualTo(Integer value) {
            addCriterion("`trans_num` =", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumNotEqualTo(Integer value) {
            addCriterion("`trans_num` <>", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumGreaterThan(Integer value) {
            addCriterion("`trans_num` >", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("`trans_num` >=", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumLessThan(Integer value) {
            addCriterion("`trans_num` <", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumLessThanOrEqualTo(Integer value) {
            addCriterion("`trans_num` <=", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumIn(List<Integer> values) {
            addCriterion("`trans_num` in", values, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumNotIn(List<Integer> values) {
            addCriterion("`trans_num` not in", values, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumBetween(Integer value1, Integer value2) {
            addCriterion("`trans_num` between", value1, value2, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumNotBetween(Integer value1, Integer value2) {
            addCriterion("`trans_num` not between", value1, value2, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNull() {
            addCriterion("`trans_at` is null");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNotNull() {
            addCriterion("`trans_at` is not null");
            return (Criteria) this;
        }

        public Criteria andTransAtEqualTo(Long value) {
            addCriterion("`trans_at` =", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotEqualTo(Long value) {
            addCriterion("`trans_at` <>", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThan(Long value) {
            addCriterion("`trans_at` >", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`trans_at` >=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThan(Long value) {
            addCriterion("`trans_at` <", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThanOrEqualTo(Long value) {
            addCriterion("`trans_at` <=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtIn(List<Long> values) {
            addCriterion("`trans_at` in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotIn(List<Long> values) {
            addCriterion("`trans_at` not in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtBetween(Long value1, Long value2) {
            addCriterion("`trans_at` between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotBetween(Long value1, Long value2) {
            addCriterion("`trans_at` not between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtIsNull() {
            addCriterion("`settle_at` is null");
            return (Criteria) this;
        }

        public Criteria andSettleAtIsNotNull() {
            addCriterion("`settle_at` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleAtEqualTo(Long value) {
            addCriterion("`settle_at` =", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtNotEqualTo(Long value) {
            addCriterion("`settle_at` <>", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtGreaterThan(Long value) {
            addCriterion("`settle_at` >", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`settle_at` >=", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtLessThan(Long value) {
            addCriterion("`settle_at` <", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtLessThanOrEqualTo(Long value) {
            addCriterion("`settle_at` <=", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtIn(List<Long> values) {
            addCriterion("`settle_at` in", values, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtNotIn(List<Long> values) {
            addCriterion("`settle_at` not in", values, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtBetween(Long value1, Long value2) {
            addCriterion("`settle_at` between", value1, value2, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtNotBetween(Long value1, Long value2) {
            addCriterion("`settle_at` not between", value1, value2, "settleAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtIsNull() {
            addCriterion("`fee_at` is null");
            return (Criteria) this;
        }

        public Criteria andFeeAtIsNotNull() {
            addCriterion("`fee_at` is not null");
            return (Criteria) this;
        }

        public Criteria andFeeAtEqualTo(Long value) {
            addCriterion("`fee_at` =", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtNotEqualTo(Long value) {
            addCriterion("`fee_at` <>", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtGreaterThan(Long value) {
            addCriterion("`fee_at` >", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`fee_at` >=", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtLessThan(Long value) {
            addCriterion("`fee_at` <", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtLessThanOrEqualTo(Long value) {
            addCriterion("`fee_at` <=", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtIn(List<Long> values) {
            addCriterion("`fee_at` in", values, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtNotIn(List<Long> values) {
            addCriterion("`fee_at` not in", values, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtBetween(Long value1, Long value2) {
            addCriterion("`fee_at` between", value1, value2, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtNotBetween(Long value1, Long value2) {
            addCriterion("`fee_at` not between", value1, value2, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("`file_path` is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("`file_path` is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("`file_path` =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("`file_path` <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("`file_path` >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("`file_path` >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("`file_path` <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("`file_path` <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("`file_path` like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("`file_path` not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("`file_path` in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("`file_path` not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("`file_path` between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("`file_path` not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNull() {
            addCriterion("`last_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNotNull() {
            addCriterion("`last_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdEqualTo(String value) {
            addCriterion("`last_oper_id` =", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotEqualTo(String value) {
            addCriterion("`last_oper_id` <>", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThan(String value) {
            addCriterion("`last_oper_id` >", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` >=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThan(String value) {
            addCriterion("`last_oper_id` <", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` <=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLike(String value) {
            addCriterion("`last_oper_id` like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotLike(String value) {
            addCriterion("`last_oper_id` not like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIn(List<String> values) {
            addCriterion("`last_oper_id` in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotIn(List<String> values) {
            addCriterion("`last_oper_id` not in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdBetween(String value1, String value2) {
            addCriterion("`last_oper_id` between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotBetween(String value1, String value2) {
            addCriterion("`last_oper_id` not between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("`comment` is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("`comment` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("`comment` =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("`comment` <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("`comment` >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("`comment` >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("`comment` <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("`comment` <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("`comment` like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("`comment` not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("`comment` in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("`comment` not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("`comment` between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("`comment` not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_acc_check_file
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_acc_check_file
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}