package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TermInfoExample {
    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public TermInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_term_info
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_term_info
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTermIdIsNull() {
            addCriterion("`term_id` is null");
            return (Criteria) this;
        }

        public Criteria andTermIdIsNotNull() {
            addCriterion("`term_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTermIdEqualTo(Integer value) {
            addCriterion("`term_id` =", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotEqualTo(Integer value) {
            addCriterion("`term_id` <>", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdGreaterThan(Integer value) {
            addCriterion("`term_id` >", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`term_id` >=", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdLessThan(Integer value) {
            addCriterion("`term_id` <", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdLessThanOrEqualTo(Integer value) {
            addCriterion("`term_id` <=", value, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdIn(List<Integer> values) {
            addCriterion("`term_id` in", values, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotIn(List<Integer> values) {
            addCriterion("`term_id` not in", values, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdBetween(Integer value1, Integer value2) {
            addCriterion("`term_id` between", value1, value2, "termId");
            return (Criteria) this;
        }

        public Criteria andTermIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`term_id` not between", value1, value2, "termId");
            return (Criteria) this;
        }

        public Criteria andTermSnIsNull() {
            addCriterion("`term_sn` is null");
            return (Criteria) this;
        }

        public Criteria andTermSnIsNotNull() {
            addCriterion("`term_sn` is not null");
            return (Criteria) this;
        }

        public Criteria andTermSnEqualTo(String value) {
            addCriterion("`term_sn` =", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotEqualTo(String value) {
            addCriterion("`term_sn` <>", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnGreaterThan(String value) {
            addCriterion("`term_sn` >", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnGreaterThanOrEqualTo(String value) {
            addCriterion("`term_sn` >=", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLessThan(String value) {
            addCriterion("`term_sn` <", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLessThanOrEqualTo(String value) {
            addCriterion("`term_sn` <=", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLike(String value) {
            addCriterion("`term_sn` like", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotLike(String value) {
            addCriterion("`term_sn` not like", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnIn(List<String> values) {
            addCriterion("`term_sn` in", values, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotIn(List<String> values) {
            addCriterion("`term_sn` not in", values, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnBetween(String value1, String value2) {
            addCriterion("`term_sn` between", value1, value2, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotBetween(String value1, String value2) {
            addCriterion("`term_sn` not between", value1, value2, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermMnIsNull() {
            addCriterion("`term_mn` is null");
            return (Criteria) this;
        }

        public Criteria andTermMnIsNotNull() {
            addCriterion("`term_mn` is not null");
            return (Criteria) this;
        }

        public Criteria andTermMnEqualTo(String value) {
            addCriterion("`term_mn` =", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnNotEqualTo(String value) {
            addCriterion("`term_mn` <>", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnGreaterThan(String value) {
            addCriterion("`term_mn` >", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnGreaterThanOrEqualTo(String value) {
            addCriterion("`term_mn` >=", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnLessThan(String value) {
            addCriterion("`term_mn` <", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnLessThanOrEqualTo(String value) {
            addCriterion("`term_mn` <=", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnLike(String value) {
            addCriterion("`term_mn` like", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnNotLike(String value) {
            addCriterion("`term_mn` not like", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnIn(List<String> values) {
            addCriterion("`term_mn` in", values, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnNotIn(List<String> values) {
            addCriterion("`term_mn` not in", values, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnBetween(String value1, String value2) {
            addCriterion("`term_mn` between", value1, value2, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnNotBetween(String value1, String value2) {
            addCriterion("`term_mn` not between", value1, value2, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermBnIsNull() {
            addCriterion("`term_bn` is null");
            return (Criteria) this;
        }

        public Criteria andTermBnIsNotNull() {
            addCriterion("`term_bn` is not null");
            return (Criteria) this;
        }

        public Criteria andTermBnEqualTo(String value) {
            addCriterion("`term_bn` =", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnNotEqualTo(String value) {
            addCriterion("`term_bn` <>", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnGreaterThan(String value) {
            addCriterion("`term_bn` >", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnGreaterThanOrEqualTo(String value) {
            addCriterion("`term_bn` >=", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnLessThan(String value) {
            addCriterion("`term_bn` <", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnLessThanOrEqualTo(String value) {
            addCriterion("`term_bn` <=", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnLike(String value) {
            addCriterion("`term_bn` like", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnNotLike(String value) {
            addCriterion("`term_bn` not like", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnIn(List<String> values) {
            addCriterion("`term_bn` in", values, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnNotIn(List<String> values) {
            addCriterion("`term_bn` not in", values, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnBetween(String value1, String value2) {
            addCriterion("`term_bn` between", value1, value2, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnNotBetween(String value1, String value2) {
            addCriterion("`term_bn` not between", value1, value2, "termBn");
            return (Criteria) this;
        }

        public Criteria andTmkIsNull() {
            addCriterion("`tmk` is null");
            return (Criteria) this;
        }

        public Criteria andTmkIsNotNull() {
            addCriterion("`tmk` is not null");
            return (Criteria) this;
        }

        public Criteria andTmkEqualTo(String value) {
            addCriterion("`tmk` =", value, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkNotEqualTo(String value) {
            addCriterion("`tmk` <>", value, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkGreaterThan(String value) {
            addCriterion("`tmk` >", value, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkGreaterThanOrEqualTo(String value) {
            addCriterion("`tmk` >=", value, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkLessThan(String value) {
            addCriterion("`tmk` <", value, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkLessThanOrEqualTo(String value) {
            addCriterion("`tmk` <=", value, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkLike(String value) {
            addCriterion("`tmk` like", value, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkNotLike(String value) {
            addCriterion("`tmk` not like", value, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkIn(List<String> values) {
            addCriterion("`tmk` in", values, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkNotIn(List<String> values) {
            addCriterion("`tmk` not in", values, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkBetween(String value1, String value2) {
            addCriterion("`tmk` between", value1, value2, "tmk");
            return (Criteria) this;
        }

        public Criteria andTmkNotBetween(String value1, String value2) {
            addCriterion("`tmk` not between", value1, value2, "tmk");
            return (Criteria) this;
        }

        public Criteria andTakIsNull() {
            addCriterion("`tak` is null");
            return (Criteria) this;
        }

        public Criteria andTakIsNotNull() {
            addCriterion("`tak` is not null");
            return (Criteria) this;
        }

        public Criteria andTakEqualTo(String value) {
            addCriterion("`tak` =", value, "tak");
            return (Criteria) this;
        }

        public Criteria andTakNotEqualTo(String value) {
            addCriterion("`tak` <>", value, "tak");
            return (Criteria) this;
        }

        public Criteria andTakGreaterThan(String value) {
            addCriterion("`tak` >", value, "tak");
            return (Criteria) this;
        }

        public Criteria andTakGreaterThanOrEqualTo(String value) {
            addCriterion("`tak` >=", value, "tak");
            return (Criteria) this;
        }

        public Criteria andTakLessThan(String value) {
            addCriterion("`tak` <", value, "tak");
            return (Criteria) this;
        }

        public Criteria andTakLessThanOrEqualTo(String value) {
            addCriterion("`tak` <=", value, "tak");
            return (Criteria) this;
        }

        public Criteria andTakLike(String value) {
            addCriterion("`tak` like", value, "tak");
            return (Criteria) this;
        }

        public Criteria andTakNotLike(String value) {
            addCriterion("`tak` not like", value, "tak");
            return (Criteria) this;
        }

        public Criteria andTakIn(List<String> values) {
            addCriterion("`tak` in", values, "tak");
            return (Criteria) this;
        }

        public Criteria andTakNotIn(List<String> values) {
            addCriterion("`tak` not in", values, "tak");
            return (Criteria) this;
        }

        public Criteria andTakBetween(String value1, String value2) {
            addCriterion("`tak` between", value1, value2, "tak");
            return (Criteria) this;
        }

        public Criteria andTakNotBetween(String value1, String value2) {
            addCriterion("`tak` not between", value1, value2, "tak");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("`oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("`oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("`oper_id` =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("`oper_id` <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("`oper_id` >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`oper_id` >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("`oper_id` <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("`oper_id` <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("`oper_id` like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("`oper_id` not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("`oper_id` in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("`oper_id` not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("`oper_id` between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("`oper_id` not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andBatNoIsNull() {
            addCriterion("`bat_no` is null");
            return (Criteria) this;
        }

        public Criteria andBatNoIsNotNull() {
            addCriterion("`bat_no` is not null");
            return (Criteria) this;
        }

        public Criteria andBatNoEqualTo(String value) {
            addCriterion("`bat_no` =", value, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoNotEqualTo(String value) {
            addCriterion("`bat_no` <>", value, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoGreaterThan(String value) {
            addCriterion("`bat_no` >", value, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoGreaterThanOrEqualTo(String value) {
            addCriterion("`bat_no` >=", value, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoLessThan(String value) {
            addCriterion("`bat_no` <", value, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoLessThanOrEqualTo(String value) {
            addCriterion("`bat_no` <=", value, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoLike(String value) {
            addCriterion("`bat_no` like", value, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoNotLike(String value) {
            addCriterion("`bat_no` not like", value, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoIn(List<String> values) {
            addCriterion("`bat_no` in", values, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoNotIn(List<String> values) {
            addCriterion("`bat_no` not in", values, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoBetween(String value1, String value2) {
            addCriterion("`bat_no` between", value1, value2, "batNo");
            return (Criteria) this;
        }

        public Criteria andBatNoNotBetween(String value1, String value2) {
            addCriterion("`bat_no` not between", value1, value2, "batNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_term_info
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_term_info
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}