package com.icpay.payment.db.dao.mybatis.mapper;

import com.icpay.payment.db.dao.mybatis.model.RiskThreshold;
import com.icpay.payment.db.dao.mybatis.model.RiskThresholdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@Deprecated
public interface RiskThreshold_BakMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int countByExample(RiskThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int deleteByExample(RiskThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int deleteByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int insert(RiskThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int insertSelective(RiskThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    List<RiskThreshold> selectByExample(RiskThresholdExample example);
    
    List<RiskThreshold> selectByPage(RiskThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    RiskThreshold selectByPrimaryKey(Integer ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") RiskThreshold record, @Param("example") RiskThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int updateByExample(@Param("record") RiskThreshold record, @Param("example") RiskThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int updateByPrimaryKeySelective(RiskThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_risk_threshold
     *
     * @mbggenerated Thu Apr 02 21:31:54 CST 2015
     */
    int updateByPrimaryKey(RiskThreshold record);
}