package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_balance_transfer_result

 *
 * @mbg.generated
 */
public class BalanceTransferResult implements Serializable {
    /**
     * Database column : tbl_balance_transfer_result.seq_id
     *
     * @mbg.generated
     */
    private Integer seqId;

    /**
     * 余额结转日期
     * Database column : tbl_balance_transfer_result.transfer_dt
     *
     * @mbg.generated
     */
    private String transferDt;

    /**
     * 商户号(含渠道商户号)
     * Database column : tbl_balance_transfer_result.mchnt_cd
     *
     * @mbg.generated
     */
    private String mchntCd;

    /**
     * 结转金额(单位：分)
     * Database column : tbl_balance_transfer_result.transfer_at
     *
     * @mbg.generated
     */
    private Long transferAt;

    /**
     * 币别，默认156(人民币)
     * Database column : tbl_balance_transfer_result.curr_cd
     *
     * @mbg.generated
     */
    private String currCd;

    /**
     * 金額表示單位 = 0.01
     * Database column : tbl_balance_transfer_result.unit
     *
     * @mbg.generated
     */
    private BigDecimal unit;

    /**
     * 渠道编号
     * Database column : tbl_balance_transfer_result.trans_chnl
     *
     * @mbg.generated
     */
    private String transChnl;

    /**
     * 结果：1：成功，2：失败
     * Database column : tbl_balance_transfer_result.transfer_result
     *
     * @mbg.generated
     */
    private String transferResult;

    /**
     * Database column : tbl_balance_transfer_result.rec_crt_ts
     *
     * @mbg.generated
     */
    private Date recCrtTs;

    /**
     * Database column : tbl_balance_transfer_result.rec_upd_ts
     *
     * @mbg.generated
     */
    private Date recUpdTs;

    /**
     * Database column : tbl_balance_transfer_result.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * 帐户操作类型; 请参考：Constant.OPERTYPE
     * Database column : tbl_balance_transfer_result.operate_tp
     *
     * @mbg.generated
     */
    private String operateTp;

    /**
     * Database table : tbl_balance_transfer_result
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_balance_transfer_result
     *
     * @mbg.generated
     */
    public BalanceTransferResult(Integer seqId, String transferDt, String mchntCd, Long transferAt, String currCd, BigDecimal unit, String transChnl, String transferResult, Date recCrtTs, Date recUpdTs, String comments, String operateTp) {
        this.seqId = seqId;
        this.transferDt = transferDt;
        this.mchntCd = mchntCd;
        this.transferAt = transferAt;
        this.currCd = currCd;
        this.unit = unit;
        this.transChnl = transChnl;
        this.transferResult = transferResult;
        this.recCrtTs = recCrtTs;
        this.recUpdTs = recUpdTs;
        this.comments = comments;
        this.operateTp = operateTp;
    }

    /**
     * Database table : tbl_balance_transfer_result
     *
     * @mbg.generated
     */
    public BalanceTransferResult() {
        super();
    }

    /**
     * @return seq_id 
     *
     * @mbg.generated
     */
    public Integer getSeqId() {
        return seqId;
    }

    /**
     * @param seqId 
     *
     * @mbg.generated
     */
    public void setSeqId(Integer seqId) {
        this.seqId = seqId;
    }

    /**
     * 余额结转日期
     * @return transfer_dt 余额结转日期
     *
     * @mbg.generated
     */
    public String getTransferDt() {
        return transferDt;
    }

    /**
     * 余额结转日期
     * @param transferDt 余额结转日期
     *
     * @mbg.generated
     */
    public void setTransferDt(String transferDt) {
        this.transferDt = transferDt;
    }

    /**
     * 商户号(含渠道商户号)
     * @return mchnt_cd 商户号(含渠道商户号)
     *
     * @mbg.generated
     */
    public String getMchntCd() {
        return mchntCd;
    }

    /**
     * 商户号(含渠道商户号)
     * @param mchntCd 商户号(含渠道商户号)
     *
     * @mbg.generated
     */
    public void setMchntCd(String mchntCd) {
        this.mchntCd = mchntCd;
    }

    /**
     * 结转金额(单位：分)
     * @return transfer_at 结转金额(单位：分)
     *
     * @mbg.generated
     */
    public Long getTransferAt() {
        return transferAt;
    }

    /**
     * 结转金额(单位：分)
     * @param transferAt 结转金额(单位：分)
     *
     * @mbg.generated
     */
    public void setTransferAt(Long transferAt) {
        this.transferAt = transferAt;
    }

    /**
     * 币别，默认156(人民币)
     * @return curr_cd 币别，默认156(人民币)
     *
     * @mbg.generated
     */
    public String getCurrCd() {
        return currCd;
    }

    /**
     * 币别，默认156(人民币)
     * @param currCd 币别，默认156(人民币)
     *
     * @mbg.generated
     */
    public void setCurrCd(String currCd) {
        this.currCd = currCd;
    }

    /**
     * 金額表示單位 = 0.01
     * @return unit 金額表示單位 = 0.01
     *
     * @mbg.generated
     */
    public BigDecimal getUnit() {
        return unit;
    }

    /**
     * 金額表示單位 = 0.01
     * @param unit 金額表示單位 = 0.01
     *
     * @mbg.generated
     */
    public void setUnit(BigDecimal unit) {
        this.unit = unit;
    }

    /**
     * 渠道编号
     * @return trans_chnl 渠道编号
     *
     * @mbg.generated
     */
    public String getTransChnl() {
        return transChnl;
    }

    /**
     * 渠道编号
     * @param transChnl 渠道编号
     *
     * @mbg.generated
     */
    public void setTransChnl(String transChnl) {
        this.transChnl = transChnl;
    }

    /**
     * 结果：1：成功，2：失败
     * @return transfer_result 结果：1：成功，2：失败
     *
     * @mbg.generated
     */
    public String getTransferResult() {
        return transferResult;
    }

    /**
     * 结果：1：成功，2：失败
     * @param transferResult 结果：1：成功，2：失败
     *
     * @mbg.generated
     */
    public void setTransferResult(String transferResult) {
        this.transferResult = transferResult;
    }

    /**
     * @return rec_crt_ts 
     *
     * @mbg.generated
     */
    public Date getRecCrtTs() {
        return recCrtTs;
    }

    /**
     * @param recCrtTs 
     *
     * @mbg.generated
     */
    public void setRecCrtTs(Date recCrtTs) {
        this.recCrtTs = recCrtTs;
    }

    /**
     * @return rec_upd_ts 
     *
     * @mbg.generated
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * @param recUpdTs 
     *
     * @mbg.generated
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }

    /**
     * @return comments 
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * @param comments 
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * 帐户操作类型; 请参考：Constant.OPERTYPE
     * @return operate_tp 帐户操作类型; 请参考：Constant.OPERTYPE
     *
     * @mbg.generated
     */
    public String getOperateTp() {
        return operateTp;
    }

    /**
     * 帐户操作类型; 请参考：Constant.OPERTYPE
     * @param operateTp 帐户操作类型; 请参考：Constant.OPERTYPE
     *
     * @mbg.generated
     */
    public void setOperateTp(String operateTp) {
        this.operateTp = operateTp;
    }

    /**
     * Database table : tbl_balance_transfer_result
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BalanceTransferResult other = (BalanceTransferResult) that;
        return (this.getSeqId() == null ? other.getSeqId() == null : this.getSeqId().equals(other.getSeqId()))
            && (this.getTransferDt() == null ? other.getTransferDt() == null : this.getTransferDt().equals(other.getTransferDt()))
            && (this.getMchntCd() == null ? other.getMchntCd() == null : this.getMchntCd().equals(other.getMchntCd()))
            && (this.getTransferAt() == null ? other.getTransferAt() == null : this.getTransferAt().equals(other.getTransferAt()))
            && (this.getCurrCd() == null ? other.getCurrCd() == null : this.getCurrCd().equals(other.getCurrCd()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getTransChnl() == null ? other.getTransChnl() == null : this.getTransChnl().equals(other.getTransChnl()))
            && (this.getTransferResult() == null ? other.getTransferResult() == null : this.getTransferResult().equals(other.getTransferResult()))
            && (this.getRecCrtTs() == null ? other.getRecCrtTs() == null : this.getRecCrtTs().equals(other.getRecCrtTs()))
            && (this.getRecUpdTs() == null ? other.getRecUpdTs() == null : this.getRecUpdTs().equals(other.getRecUpdTs()))
            && (this.getComments() == null ? other.getComments() == null : this.getComments().equals(other.getComments()))
            && (this.getOperateTp() == null ? other.getOperateTp() == null : this.getOperateTp().equals(other.getOperateTp()));
    }

    /**
     * Database table : tbl_balance_transfer_result
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqId() == null) ? 0 : getSeqId().hashCode());
        result = prime * result + ((getTransferDt() == null) ? 0 : getTransferDt().hashCode());
        result = prime * result + ((getMchntCd() == null) ? 0 : getMchntCd().hashCode());
        result = prime * result + ((getTransferAt() == null) ? 0 : getTransferAt().hashCode());
        result = prime * result + ((getCurrCd() == null) ? 0 : getCurrCd().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getTransChnl() == null) ? 0 : getTransChnl().hashCode());
        result = prime * result + ((getTransferResult() == null) ? 0 : getTransferResult().hashCode());
        result = prime * result + ((getRecCrtTs() == null) ? 0 : getRecCrtTs().hashCode());
        result = prime * result + ((getRecUpdTs() == null) ? 0 : getRecUpdTs().hashCode());
        result = prime * result + ((getComments() == null) ? 0 : getComments().hashCode());
        result = prime * result + ((getOperateTp() == null) ? 0 : getOperateTp().hashCode());
        return result;
    }

    /**
     * Database table : tbl_balance_transfer_result
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", seqId=").append(seqId);
        sb.append(", transferDt=").append(transferDt);
        sb.append(", mchntCd=").append(mchntCd);
        sb.append(", transferAt=").append(transferAt);
        sb.append(", currCd=").append(currCd);
        sb.append(", unit=").append(unit);
        sb.append(", transChnl=").append(transChnl);
        sb.append(", transferResult=").append(transferResult);
        sb.append(", recCrtTs=").append(recCrtTs);
        sb.append(", recUpdTs=").append(recUpdTs);
        sb.append(", comments=").append(comments);
        sb.append(", operateTp=").append(operateTp);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(BalanceTransferResult source) {
        this.seqId=source.seqId;
        this.transferDt=source.transferDt;
        this.mchntCd=source.mchntCd;
        this.transferAt=source.transferAt;
        this.currCd=source.currCd;
        this.unit=source.unit;
        this.transChnl=source.transChnl;
        this.transferResult=source.transferResult;
        this.recCrtTs=source.recCrtTs;
        this.recUpdTs=source.recUpdTs;
        this.comments=source.comments;
        this.operateTp=source.operateTp;
    }
}