package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentProfitPolicyMchntExample {
    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public AgentProfitPolicyMchntExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : view_agent_profit_policy_mchnt
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_agent_profit_policy_mchnt
     * @author user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAgentCdIsNull() {
            addCriterion("`agent_cd` is null");
            return (Criteria) this;
        }

        public Criteria andAgentCdIsNotNull() {
            addCriterion("`agent_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCdEqualTo(String value) {
            addCriterion("`agent_cd` =", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotEqualTo(String value) {
            addCriterion("`agent_cd` <>", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThan(String value) {
            addCriterion("`agent_cd` >", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_cd` >=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThan(String value) {
            addCriterion("`agent_cd` <", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThanOrEqualTo(String value) {
            addCriterion("`agent_cd` <=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLike(String value) {
            addCriterion("`agent_cd` like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotLike(String value) {
            addCriterion("`agent_cd` not like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdIn(List<String> values) {
            addCriterion("`agent_cd` in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotIn(List<String> values) {
            addCriterion("`agent_cd` not in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdBetween(String value1, String value2) {
            addCriterion("`agent_cd` between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotBetween(String value1, String value2) {
            addCriterion("`agent_cd` not between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmIsNull() {
            addCriterion("`mchnt_cn_nm` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmIsNotNull() {
            addCriterion("`mchnt_cn_nm` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmEqualTo(String value) {
            addCriterion("`mchnt_cn_nm` =", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmNotEqualTo(String value) {
            addCriterion("`mchnt_cn_nm` <>", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmGreaterThan(String value) {
            addCriterion("`mchnt_cn_nm` >", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cn_nm` >=", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmLessThan(String value) {
            addCriterion("`mchnt_cn_nm` <", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cn_nm` <=", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmLike(String value) {
            addCriterion("`mchnt_cn_nm` like", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmNotLike(String value) {
            addCriterion("`mchnt_cn_nm` not like", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmIn(List<String> values) {
            addCriterion("`mchnt_cn_nm` in", values, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmNotIn(List<String> values) {
            addCriterion("`mchnt_cn_nm` not in", values, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmBetween(String value1, String value2) {
            addCriterion("`mchnt_cn_nm` between", value1, value2, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cn_nm` not between", value1, value2, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntStIsNull() {
            addCriterion("`mchnt_st` is null");
            return (Criteria) this;
        }

        public Criteria andMchntStIsNotNull() {
            addCriterion("`mchnt_st` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntStEqualTo(String value) {
            addCriterion("`mchnt_st` =", value, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStNotEqualTo(String value) {
            addCriterion("`mchnt_st` <>", value, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStGreaterThan(String value) {
            addCriterion("`mchnt_st` >", value, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_st` >=", value, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStLessThan(String value) {
            addCriterion("`mchnt_st` <", value, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_st` <=", value, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStLike(String value) {
            addCriterion("`mchnt_st` like", value, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStNotLike(String value) {
            addCriterion("`mchnt_st` not like", value, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStIn(List<String> values) {
            addCriterion("`mchnt_st` in", values, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStNotIn(List<String> values) {
            addCriterion("`mchnt_st` not in", values, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStBetween(String value1, String value2) {
            addCriterion("`mchnt_st` between", value1, value2, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andMchntStNotBetween(String value1, String value2) {
            addCriterion("`mchnt_st` not between", value1, value2, "mchntSt");
            return (Criteria) this;
        }

        public Criteria andContactMailIsNull() {
            addCriterion("`contact_mail` is null");
            return (Criteria) this;
        }

        public Criteria andContactMailIsNotNull() {
            addCriterion("`contact_mail` is not null");
            return (Criteria) this;
        }

        public Criteria andContactMailEqualTo(String value) {
            addCriterion("`contact_mail` =", value, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailNotEqualTo(String value) {
            addCriterion("`contact_mail` <>", value, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailGreaterThan(String value) {
            addCriterion("`contact_mail` >", value, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailGreaterThanOrEqualTo(String value) {
            addCriterion("`contact_mail` >=", value, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailLessThan(String value) {
            addCriterion("`contact_mail` <", value, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailLessThanOrEqualTo(String value) {
            addCriterion("`contact_mail` <=", value, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailLike(String value) {
            addCriterion("`contact_mail` like", value, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailNotLike(String value) {
            addCriterion("`contact_mail` not like", value, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailIn(List<String> values) {
            addCriterion("`contact_mail` in", values, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailNotIn(List<String> values) {
            addCriterion("`contact_mail` not in", values, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailBetween(String value1, String value2) {
            addCriterion("`contact_mail` between", value1, value2, "contactMail");
            return (Criteria) this;
        }

        public Criteria andContactMailNotBetween(String value1, String value2) {
            addCriterion("`contact_mail` not between", value1, value2, "contactMail");
            return (Criteria) this;
        }

        public Criteria andTrustDomainIsNull() {
            addCriterion("`trust_domain` is null");
            return (Criteria) this;
        }

        public Criteria andTrustDomainIsNotNull() {
            addCriterion("`trust_domain` is not null");
            return (Criteria) this;
        }

        public Criteria andTrustDomainEqualTo(String value) {
            addCriterion("`trust_domain` =", value, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainNotEqualTo(String value) {
            addCriterion("`trust_domain` <>", value, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainGreaterThan(String value) {
            addCriterion("`trust_domain` >", value, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainGreaterThanOrEqualTo(String value) {
            addCriterion("`trust_domain` >=", value, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainLessThan(String value) {
            addCriterion("`trust_domain` <", value, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainLessThanOrEqualTo(String value) {
            addCriterion("`trust_domain` <=", value, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainLike(String value) {
            addCriterion("`trust_domain` like", value, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainNotLike(String value) {
            addCriterion("`trust_domain` not like", value, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainIn(List<String> values) {
            addCriterion("`trust_domain` in", values, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainNotIn(List<String> values) {
            addCriterion("`trust_domain` not in", values, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainBetween(String value1, String value2) {
            addCriterion("`trust_domain` between", value1, value2, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andTrustDomainNotBetween(String value1, String value2) {
            addCriterion("`trust_domain` not between", value1, value2, "trustDomain");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_agent_profit_policy_mchnt
     * @author user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_agent_profit_policy_mchnt
     * @author user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}