package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_bank_txn_map

 *
 * @mbg.generated
 */
public class BankTxnMapKey implements Serializable {
    /**
     * 交易类型 
     * Database column : tbl_bank_txn_map.int_trans_cd
     *
     * @mbg.generated
     */
    private String intTransCd;

    /**
     * 银行编号
     * Database column : tbl_bank_txn_map.bank_num
     *
     * @mbg.generated
     */
    private String bankNum;

    /**
     * Database table : tbl_bank_txn_map
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_bank_txn_map
     *
     * @mbg.generated
     */
    public BankTxnMapKey(String intTransCd, String bankNum) {
        this.intTransCd = intTransCd;
        this.bankNum = bankNum;
    }

    /**
     * Database table : tbl_bank_txn_map
     *
     * @mbg.generated
     */
    public BankTxnMapKey() {
        super();
    }

    /**
     * 交易类型 
     * @return int_trans_cd 交易类型 
     *
     * @mbg.generated
     */
    public String getIntTransCd() {
        return intTransCd;
    }

    /**
     * 交易类型 
     * @param intTransCd 交易类型 
     *
     * @mbg.generated
     */
    public void setIntTransCd(String intTransCd) {
        this.intTransCd = intTransCd;
    }

    /**
     * 银行编号
     * @return bank_num 银行编号
     *
     * @mbg.generated
     */
    public String getBankNum() {
        return bankNum;
    }

    /**
     * 银行编号
     * @param bankNum 银行编号
     *
     * @mbg.generated
     */
    public void setBankNum(String bankNum) {
        this.bankNum = bankNum;
    }

    /**
     * Database table : tbl_bank_txn_map
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BankTxnMapKey other = (BankTxnMapKey) that;
        return (this.getIntTransCd() == null ? other.getIntTransCd() == null : this.getIntTransCd().equals(other.getIntTransCd()))
            && (this.getBankNum() == null ? other.getBankNum() == null : this.getBankNum().equals(other.getBankNum()));
    }

    /**
     * Database table : tbl_bank_txn_map
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIntTransCd() == null) ? 0 : getIntTransCd().hashCode());
        result = prime * result + ((getBankNum() == null) ? 0 : getBankNum().hashCode());
        return result;
    }

    /**
     * Database table : tbl_bank_txn_map
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", intTransCd=").append(intTransCd);
        sb.append(", bankNum=").append(bankNum);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(BankTxnMapKey source) {
        this.intTransCd=source.intTransCd;
        this.bankNum=source.bankNum;
    }
}