package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;
import java.util.Date;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_batch_exec_log_detail

 *
 * @mbg.generated
 */
public class BatchExecLogDetail implements Serializable {
    /**
     * Database column : tbl_batch_exec_log_detail.log_detail_id
     *
     * @mbg.generated
     */
    private String logDetailId;

    /**
     * Database column : tbl_batch_exec_log_detail.log_id
     *
     * @mbg.generated
     */
    private String logId;

    /**
     * Database column : tbl_batch_exec_log_detail.batch_no
     *
     * @mbg.generated
     */
    private Integer batchNo;

    /**
     * Database column : tbl_batch_exec_log_detail.job_no
     *
     * @mbg.generated
     */
    private Integer jobNo;

    /**
     * Database column : tbl_batch_exec_log_detail.step_no
     *
     * @mbg.generated
     */
    private Integer stepNo;

    /**
     * Database column : tbl_batch_exec_log_detail.batch_dt
     *
     * @mbg.generated
     */
    private String batchDt;

    /**
     * Database column : tbl_batch_exec_log_detail.running_dt
     *
     * @mbg.generated
     */
    private String runningDt;

    /**
     * Database column : tbl_batch_exec_log_detail.start_tm
     *
     * @mbg.generated
     */
    private String startTm;

    /**
     * Database column : tbl_batch_exec_log_detail.end_tm
     *
     * @mbg.generated
     */
    private String endTm;

    /**
     * Database column : tbl_batch_exec_log_detail.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database column : tbl_batch_exec_log_detail.exec_msg
     *
     * @mbg.generated
     */
    private String execMsg;

    /**
     * Database column : tbl_batch_exec_log_detail.err_msg
     *
     * @mbg.generated
     */
    private String errMsg;

    /**
     * Database column : tbl_batch_exec_log_detail.rec_crt_ts
     *
     * @mbg.generated
     */
    private Date recCrtTs;

    /**
     * Database column : tbl_batch_exec_log_detail.rec_upd_ts
     *
     * @mbg.generated
     */
    private Date recUpdTs;

    /**
     * Database table : tbl_batch_exec_log_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_batch_exec_log_detail
     *
     * @mbg.generated
     */
    public BatchExecLogDetail(String logDetailId, String logId, Integer batchNo, Integer jobNo, Integer stepNo, String batchDt, String runningDt, String startTm, String endTm, String status, String execMsg, String errMsg, Date recCrtTs, Date recUpdTs) {
        this.logDetailId = logDetailId;
        this.logId = logId;
        this.batchNo = batchNo;
        this.jobNo = jobNo;
        this.stepNo = stepNo;
        this.batchDt = batchDt;
        this.runningDt = runningDt;
        this.startTm = startTm;
        this.endTm = endTm;
        this.status = status;
        this.execMsg = execMsg;
        this.errMsg = errMsg;
        this.recCrtTs = recCrtTs;
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_batch_exec_log_detail
     *
     * @mbg.generated
     */
    public BatchExecLogDetail() {
        super();
    }

    /**
     * @return log_detail_id 
     *
     * @mbg.generated
     */
    public String getLogDetailId() {
        return logDetailId;
    }

    /**
     * @param logDetailId 
     *
     * @mbg.generated
     */
    public void setLogDetailId(String logDetailId) {
        this.logDetailId = logDetailId;
    }

    /**
     * @return log_id 
     *
     * @mbg.generated
     */
    public String getLogId() {
        return logId;
    }

    /**
     * @param logId 
     *
     * @mbg.generated
     */
    public void setLogId(String logId) {
        this.logId = logId;
    }

    /**
     * @return batch_no 
     *
     * @mbg.generated
     */
    public Integer getBatchNo() {
        return batchNo;
    }

    /**
     * @param batchNo 
     *
     * @mbg.generated
     */
    public void setBatchNo(Integer batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * @return job_no 
     *
     * @mbg.generated
     */
    public Integer getJobNo() {
        return jobNo;
    }

    /**
     * @param jobNo 
     *
     * @mbg.generated
     */
    public void setJobNo(Integer jobNo) {
        this.jobNo = jobNo;
    }

    /**
     * @return step_no 
     *
     * @mbg.generated
     */
    public Integer getStepNo() {
        return stepNo;
    }

    /**
     * @param stepNo 
     *
     * @mbg.generated
     */
    public void setStepNo(Integer stepNo) {
        this.stepNo = stepNo;
    }

    /**
     * @return batch_dt 
     *
     * @mbg.generated
     */
    public String getBatchDt() {
        return batchDt;
    }

    /**
     * @param batchDt 
     *
     * @mbg.generated
     */
    public void setBatchDt(String batchDt) {
        this.batchDt = batchDt;
    }

    /**
     * @return running_dt 
     *
     * @mbg.generated
     */
    public String getRunningDt() {
        return runningDt;
    }

    /**
     * @param runningDt 
     *
     * @mbg.generated
     */
    public void setRunningDt(String runningDt) {
        this.runningDt = runningDt;
    }

    /**
     * @return start_tm 
     *
     * @mbg.generated
     */
    public String getStartTm() {
        return startTm;
    }

    /**
     * @param startTm 
     *
     * @mbg.generated
     */
    public void setStartTm(String startTm) {
        this.startTm = startTm;
    }

    /**
     * @return end_tm 
     *
     * @mbg.generated
     */
    public String getEndTm() {
        return endTm;
    }

    /**
     * @param endTm 
     *
     * @mbg.generated
     */
    public void setEndTm(String endTm) {
        this.endTm = endTm;
    }

    /**
     * @return status 
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status 
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * @return exec_msg 
     *
     * @mbg.generated
     */
    public String getExecMsg() {
        return execMsg;
    }

    /**
     * @param execMsg 
     *
     * @mbg.generated
     */
    public void setExecMsg(String execMsg) {
        this.execMsg = execMsg;
    }

    /**
     * @return err_msg 
     *
     * @mbg.generated
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * @param errMsg 
     *
     * @mbg.generated
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }

    /**
     * @return rec_crt_ts 
     *
     * @mbg.generated
     */
    public Date getRecCrtTs() {
        return recCrtTs;
    }

    /**
     * @param recCrtTs 
     *
     * @mbg.generated
     */
    public void setRecCrtTs(Date recCrtTs) {
        this.recCrtTs = recCrtTs;
    }

    /**
     * @return rec_upd_ts 
     *
     * @mbg.generated
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * @param recUpdTs 
     *
     * @mbg.generated
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_batch_exec_log_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BatchExecLogDetail other = (BatchExecLogDetail) that;
        return (this.getLogDetailId() == null ? other.getLogDetailId() == null : this.getLogDetailId().equals(other.getLogDetailId()))
            && (this.getLogId() == null ? other.getLogId() == null : this.getLogId().equals(other.getLogId()))
            && (this.getBatchNo() == null ? other.getBatchNo() == null : this.getBatchNo().equals(other.getBatchNo()))
            && (this.getJobNo() == null ? other.getJobNo() == null : this.getJobNo().equals(other.getJobNo()))
            && (this.getStepNo() == null ? other.getStepNo() == null : this.getStepNo().equals(other.getStepNo()))
            && (this.getBatchDt() == null ? other.getBatchDt() == null : this.getBatchDt().equals(other.getBatchDt()))
            && (this.getRunningDt() == null ? other.getRunningDt() == null : this.getRunningDt().equals(other.getRunningDt()))
            && (this.getStartTm() == null ? other.getStartTm() == null : this.getStartTm().equals(other.getStartTm()))
            && (this.getEndTm() == null ? other.getEndTm() == null : this.getEndTm().equals(other.getEndTm()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getExecMsg() == null ? other.getExecMsg() == null : this.getExecMsg().equals(other.getExecMsg()))
            && (this.getErrMsg() == null ? other.getErrMsg() == null : this.getErrMsg().equals(other.getErrMsg()))
            && (this.getRecCrtTs() == null ? other.getRecCrtTs() == null : this.getRecCrtTs().equals(other.getRecCrtTs()))
            && (this.getRecUpdTs() == null ? other.getRecUpdTs() == null : this.getRecUpdTs().equals(other.getRecUpdTs()));
    }

    /**
     * Database table : tbl_batch_exec_log_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogDetailId() == null) ? 0 : getLogDetailId().hashCode());
        result = prime * result + ((getLogId() == null) ? 0 : getLogId().hashCode());
        result = prime * result + ((getBatchNo() == null) ? 0 : getBatchNo().hashCode());
        result = prime * result + ((getJobNo() == null) ? 0 : getJobNo().hashCode());
        result = prime * result + ((getStepNo() == null) ? 0 : getStepNo().hashCode());
        result = prime * result + ((getBatchDt() == null) ? 0 : getBatchDt().hashCode());
        result = prime * result + ((getRunningDt() == null) ? 0 : getRunningDt().hashCode());
        result = prime * result + ((getStartTm() == null) ? 0 : getStartTm().hashCode());
        result = prime * result + ((getEndTm() == null) ? 0 : getEndTm().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getExecMsg() == null) ? 0 : getExecMsg().hashCode());
        result = prime * result + ((getErrMsg() == null) ? 0 : getErrMsg().hashCode());
        result = prime * result + ((getRecCrtTs() == null) ? 0 : getRecCrtTs().hashCode());
        result = prime * result + ((getRecUpdTs() == null) ? 0 : getRecUpdTs().hashCode());
        return result;
    }

    /**
     * Database table : tbl_batch_exec_log_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", logDetailId=").append(logDetailId);
        sb.append(", logId=").append(logId);
        sb.append(", batchNo=").append(batchNo);
        sb.append(", jobNo=").append(jobNo);
        sb.append(", stepNo=").append(stepNo);
        sb.append(", batchDt=").append(batchDt);
        sb.append(", runningDt=").append(runningDt);
        sb.append(", startTm=").append(startTm);
        sb.append(", endTm=").append(endTm);
        sb.append(", status=").append(status);
        sb.append(", execMsg=").append(execMsg);
        sb.append(", errMsg=").append(errMsg);
        sb.append(", recCrtTs=").append(recCrtTs);
        sb.append(", recUpdTs=").append(recUpdTs);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(BatchExecLogDetail source) {
        this.logDetailId=source.logDetailId;
        this.logId=source.logId;
        this.batchNo=source.batchNo;
        this.jobNo=source.jobNo;
        this.stepNo=source.stepNo;
        this.batchDt=source.batchDt;
        this.runningDt=source.runningDt;
        this.startTm=source.startTm;
        this.endTm=source.endTm;
        this.status=source.status;
        this.execMsg=source.execMsg;
        this.errMsg=source.errMsg;
        this.recCrtTs=source.recCrtTs;
        this.recUpdTs=source.recUpdTs;
    }
}