package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;
import java.util.Date;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_cash_pool_info

 *
 * @mbg.generated
 */
public class CashPoolInfo implements Serializable {
    /**
     * 资金池编号
     * Database column : tbl_cash_pool_info.pool_id
     *
     * @mbg.generated
     */
    private String poolId;

    /**
     * 资金池名称
     * Database column : tbl_cash_pool_info.pool_desc
     *
     * @mbg.generated
     */
    private String poolDesc;

    /**
     * 交易类型(0010=消费/支付交易，5210=代付交易)
     * Database column : tbl_cash_pool_info.int_trans_cd
     *
     * @mbg.generated
     */
    private String intTransCd;

    /**
     * 币别
     * Database column : tbl_cash_pool_info.curr_cd
     *
     * @mbg.generated
     */
    private String currCd;

    /**
     * 状态(1=有效)
     * Database column : tbl_cash_pool_info.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * 备注
     * Database column : tbl_cash_pool_info.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * Database column : tbl_cash_pool_info.rec_crt_ts
     *
     * @mbg.generated
     */
    private Date recCrtTs;

    /**
     * Database column : tbl_cash_pool_info.rec_upd_ts
     *
     * @mbg.generated
     */
    private Date recUpdTs;

    /**
     * Database column : tbl_cash_pool_info.last_oper_id
     *
     * @mbg.generated
     */
    private String lastOperId;

    /**
     * Database table : tbl_cash_pool_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_cash_pool_info
     *
     * @mbg.generated
     */
    public CashPoolInfo(String poolId, String poolDesc, String intTransCd, String currCd, String state, String comment, Date recCrtTs, Date recUpdTs, String lastOperId) {
        this.poolId = poolId;
        this.poolDesc = poolDesc;
        this.intTransCd = intTransCd;
        this.currCd = currCd;
        this.state = state;
        this.comment = comment;
        this.recCrtTs = recCrtTs;
        this.recUpdTs = recUpdTs;
        this.lastOperId = lastOperId;
    }

    /**
     * Database table : tbl_cash_pool_info
     *
     * @mbg.generated
     */
    public CashPoolInfo() {
        super();
    }

    /**
     * 资金池编号
     * @return pool_id 资金池编号
     *
     * @mbg.generated
     */
    public String getPoolId() {
        return poolId;
    }

    /**
     * 资金池编号
     * @param poolId 资金池编号
     *
     * @mbg.generated
     */
    public void setPoolId(String poolId) {
        this.poolId = poolId;
    }

    /**
     * 资金池名称
     * @return pool_desc 资金池名称
     *
     * @mbg.generated
     */
    public String getPoolDesc() {
        return poolDesc;
    }

    /**
     * 资金池名称
     * @param poolDesc 资金池名称
     *
     * @mbg.generated
     */
    public void setPoolDesc(String poolDesc) {
        this.poolDesc = poolDesc;
    }

    /**
     * 交易类型(0010=消费/支付交易，5210=代付交易)
     * @return int_trans_cd 交易类型(0010=消费/支付交易，5210=代付交易)
     *
     * @mbg.generated
     */
    public String getIntTransCd() {
        return intTransCd;
    }

    /**
     * 交易类型(0010=消费/支付交易，5210=代付交易)
     * @param intTransCd 交易类型(0010=消费/支付交易，5210=代付交易)
     *
     * @mbg.generated
     */
    public void setIntTransCd(String intTransCd) {
        this.intTransCd = intTransCd;
    }

    /**
     * 币别
     * @return curr_cd 币别
     *
     * @mbg.generated
     */
    public String getCurrCd() {
        return currCd;
    }

    /**
     * 币别
     * @param currCd 币别
     *
     * @mbg.generated
     */
    public void setCurrCd(String currCd) {
        this.currCd = currCd;
    }

    /**
     * 状态(1=有效)
     * @return state 状态(1=有效)
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * 状态(1=有效)
     * @param state 状态(1=有效)
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * 备注
     * @return comment 备注
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * 备注
     * @param comment 备注
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * @return rec_crt_ts 
     *
     * @mbg.generated
     */
    public Date getRecCrtTs() {
        return recCrtTs;
    }

    /**
     * @param recCrtTs 
     *
     * @mbg.generated
     */
    public void setRecCrtTs(Date recCrtTs) {
        this.recCrtTs = recCrtTs;
    }

    /**
     * @return rec_upd_ts 
     *
     * @mbg.generated
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * @param recUpdTs 
     *
     * @mbg.generated
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }

    /**
     * @return last_oper_id 
     *
     * @mbg.generated
     */
    public String getLastOperId() {
        return lastOperId;
    }

    /**
     * @param lastOperId 
     *
     * @mbg.generated
     */
    public void setLastOperId(String lastOperId) {
        this.lastOperId = lastOperId;
    }

    /**
     * Database table : tbl_cash_pool_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CashPoolInfo other = (CashPoolInfo) that;
        return (this.getPoolId() == null ? other.getPoolId() == null : this.getPoolId().equals(other.getPoolId()))
            && (this.getPoolDesc() == null ? other.getPoolDesc() == null : this.getPoolDesc().equals(other.getPoolDesc()))
            && (this.getIntTransCd() == null ? other.getIntTransCd() == null : this.getIntTransCd().equals(other.getIntTransCd()))
            && (this.getCurrCd() == null ? other.getCurrCd() == null : this.getCurrCd().equals(other.getCurrCd()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getRecCrtTs() == null ? other.getRecCrtTs() == null : this.getRecCrtTs().equals(other.getRecCrtTs()))
            && (this.getRecUpdTs() == null ? other.getRecUpdTs() == null : this.getRecUpdTs().equals(other.getRecUpdTs()))
            && (this.getLastOperId() == null ? other.getLastOperId() == null : this.getLastOperId().equals(other.getLastOperId()));
    }

    /**
     * Database table : tbl_cash_pool_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPoolId() == null) ? 0 : getPoolId().hashCode());
        result = prime * result + ((getPoolDesc() == null) ? 0 : getPoolDesc().hashCode());
        result = prime * result + ((getIntTransCd() == null) ? 0 : getIntTransCd().hashCode());
        result = prime * result + ((getCurrCd() == null) ? 0 : getCurrCd().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getRecCrtTs() == null) ? 0 : getRecCrtTs().hashCode());
        result = prime * result + ((getRecUpdTs() == null) ? 0 : getRecUpdTs().hashCode());
        result = prime * result + ((getLastOperId() == null) ? 0 : getLastOperId().hashCode());
        return result;
    }

    /**
     * Database table : tbl_cash_pool_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", poolId=").append(poolId);
        sb.append(", poolDesc=").append(poolDesc);
        sb.append(", intTransCd=").append(intTransCd);
        sb.append(", currCd=").append(currCd);
        sb.append(", state=").append(state);
        sb.append(", comment=").append(comment);
        sb.append(", recCrtTs=").append(recCrtTs);
        sb.append(", recUpdTs=").append(recUpdTs);
        sb.append(", lastOperId=").append(lastOperId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(CashPoolInfo source) {
        this.poolId=source.poolId;
        this.poolDesc=source.poolDesc;
        this.intTransCd=source.intTransCd;
        this.currCd=source.currCd;
        this.state=source.state;
        this.comment=source.comment;
        this.recCrtTs=source.recCrtTs;
        this.recUpdTs=source.recUpdTs;
        this.lastOperId=source.lastOperId;
    }
}