package com.icpay.payment.db.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChnlMchntAccountFlowExample {
    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public ChnlMchntAccountFlowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_flow01
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_flow01
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqIdIsNull() {
            addCriterion("`seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andSeqIdIsNotNull() {
            addCriterion("`seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andSeqIdEqualTo(Long value) {
            addCriterion("`seq_id` =", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotEqualTo(Long value) {
            addCriterion("`seq_id` <>", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdGreaterThan(Long value) {
            addCriterion("`seq_id` >", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`seq_id` >=", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLessThan(Long value) {
            addCriterion("`seq_id` <", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLessThanOrEqualTo(Long value) {
            addCriterion("`seq_id` <=", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdIn(List<Long> values) {
            addCriterion("`seq_id` in", values, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotIn(List<Long> values) {
            addCriterion("`seq_id` not in", values, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdBetween(Long value1, Long value2) {
            addCriterion("`seq_id` between", value1, value2, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotBetween(Long value1, Long value2) {
            addCriterion("`seq_id` not between", value1, value2, "seqId");
            return (Criteria) this;
        }

        public Criteria andChnlIdIsNull() {
            addCriterion("`chnl_id` is null");
            return (Criteria) this;
        }

        public Criteria andChnlIdIsNotNull() {
            addCriterion("`chnl_id` is not null");
            return (Criteria) this;
        }

        public Criteria andChnlIdEqualTo(String value) {
            addCriterion("`chnl_id` =", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotEqualTo(String value) {
            addCriterion("`chnl_id` <>", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThan(String value) {
            addCriterion("`chnl_id` >", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThanOrEqualTo(String value) {
            addCriterion("`chnl_id` >=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThan(String value) {
            addCriterion("`chnl_id` <", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThanOrEqualTo(String value) {
            addCriterion("`chnl_id` <=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLike(String value) {
            addCriterion("`chnl_id` like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotLike(String value) {
            addCriterion("`chnl_id` not like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdIn(List<String> values) {
            addCriterion("`chnl_id` in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotIn(List<String> values) {
            addCriterion("`chnl_id` not in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdBetween(String value1, String value2) {
            addCriterion("`chnl_id` between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotBetween(String value1, String value2) {
            addCriterion("`chnl_id` not between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNull() {
            addCriterion("`trans_at` is null");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNotNull() {
            addCriterion("`trans_at` is not null");
            return (Criteria) this;
        }

        public Criteria andTransAtEqualTo(Long value) {
            addCriterion("`trans_at` =", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotEqualTo(Long value) {
            addCriterion("`trans_at` <>", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThan(Long value) {
            addCriterion("`trans_at` >", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`trans_at` >=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThan(Long value) {
            addCriterion("`trans_at` <", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThanOrEqualTo(Long value) {
            addCriterion("`trans_at` <=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtIn(List<Long> values) {
            addCriterion("`trans_at` in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotIn(List<Long> values) {
            addCriterion("`trans_at` not in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtBetween(Long value1, Long value2) {
            addCriterion("`trans_at` between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotBetween(Long value1, Long value2) {
            addCriterion("`trans_at` not between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransFeeIsNull() {
            addCriterion("`trans_fee` is null");
            return (Criteria) this;
        }

        public Criteria andTransFeeIsNotNull() {
            addCriterion("`trans_fee` is not null");
            return (Criteria) this;
        }

        public Criteria andTransFeeEqualTo(Long value) {
            addCriterion("`trans_fee` =", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeNotEqualTo(Long value) {
            addCriterion("`trans_fee` <>", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeGreaterThan(Long value) {
            addCriterion("`trans_fee` >", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeGreaterThanOrEqualTo(Long value) {
            addCriterion("`trans_fee` >=", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeLessThan(Long value) {
            addCriterion("`trans_fee` <", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeLessThanOrEqualTo(Long value) {
            addCriterion("`trans_fee` <=", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeIn(List<Long> values) {
            addCriterion("`trans_fee` in", values, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeNotIn(List<Long> values) {
            addCriterion("`trans_fee` not in", values, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeBetween(Long value1, Long value2) {
            addCriterion("`trans_fee` between", value1, value2, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeNotBetween(Long value1, Long value2) {
            addCriterion("`trans_fee` not between", value1, value2, "transFee");
            return (Criteria) this;
        }

        public Criteria andCurrCdIsNull() {
            addCriterion("`curr_cd` is null");
            return (Criteria) this;
        }

        public Criteria andCurrCdIsNotNull() {
            addCriterion("`curr_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andCurrCdEqualTo(String value) {
            addCriterion("`curr_cd` =", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotEqualTo(String value) {
            addCriterion("`curr_cd` <>", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdGreaterThan(String value) {
            addCriterion("`curr_cd` >", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdGreaterThanOrEqualTo(String value) {
            addCriterion("`curr_cd` >=", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLessThan(String value) {
            addCriterion("`curr_cd` <", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLessThanOrEqualTo(String value) {
            addCriterion("`curr_cd` <=", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLike(String value) {
            addCriterion("`curr_cd` like", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotLike(String value) {
            addCriterion("`curr_cd` not like", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdIn(List<String> values) {
            addCriterion("`curr_cd` in", values, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotIn(List<String> values) {
            addCriterion("`curr_cd` not in", values, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdBetween(String value1, String value2) {
            addCriterion("`curr_cd` between", value1, value2, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotBetween(String value1, String value2) {
            addCriterion("`curr_cd` not between", value1, value2, "currCd");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("`unit` is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("`unit` is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(BigDecimal value) {
            addCriterion("`unit` =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(BigDecimal value) {
            addCriterion("`unit` <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(BigDecimal value) {
            addCriterion("`unit` >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`unit` >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(BigDecimal value) {
            addCriterion("`unit` <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`unit` <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<BigDecimal> values) {
            addCriterion("`unit` in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<BigDecimal> values) {
            addCriterion("`unit` not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`unit` between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`unit` not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andOperateTpIsNull() {
            addCriterion("`operate_tp` is null");
            return (Criteria) this;
        }

        public Criteria andOperateTpIsNotNull() {
            addCriterion("`operate_tp` is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTpEqualTo(String value) {
            addCriterion("`operate_tp` =", value, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpNotEqualTo(String value) {
            addCriterion("`operate_tp` <>", value, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpGreaterThan(String value) {
            addCriterion("`operate_tp` >", value, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpGreaterThanOrEqualTo(String value) {
            addCriterion("`operate_tp` >=", value, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpLessThan(String value) {
            addCriterion("`operate_tp` <", value, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpLessThanOrEqualTo(String value) {
            addCriterion("`operate_tp` <=", value, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpLike(String value) {
            addCriterion("`operate_tp` like", value, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpNotLike(String value) {
            addCriterion("`operate_tp` not like", value, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpIn(List<String> values) {
            addCriterion("`operate_tp` in", values, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpNotIn(List<String> values) {
            addCriterion("`operate_tp` not in", values, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpBetween(String value1, String value2) {
            addCriterion("`operate_tp` between", value1, value2, "operateTp");
            return (Criteria) this;
        }

        public Criteria andOperateTpNotBetween(String value1, String value2) {
            addCriterion("`operate_tp` not between", value1, value2, "operateTp");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIsNull() {
            addCriterion("`available_balance` is null");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIsNotNull() {
            addCriterion("`available_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceEqualTo(Long value) {
            addCriterion("`available_balance` =", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotEqualTo(Long value) {
            addCriterion("`available_balance` <>", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceGreaterThan(Long value) {
            addCriterion("`available_balance` >", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`available_balance` >=", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceLessThan(Long value) {
            addCriterion("`available_balance` <", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceLessThanOrEqualTo(Long value) {
            addCriterion("`available_balance` <=", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIn(List<Long> values) {
            addCriterion("`available_balance` in", values, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotIn(List<Long> values) {
            addCriterion("`available_balance` not in", values, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceBetween(Long value1, Long value2) {
            addCriterion("`available_balance` between", value1, value2, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotBetween(Long value1, Long value2) {
            addCriterion("`available_balance` not between", value1, value2, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIsNull() {
            addCriterion("`frozen_t1_balance` is null");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIsNotNull() {
            addCriterion("`frozen_t1_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` =", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` <>", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceGreaterThan(Long value) {
            addCriterion("`frozen_t1_balance` >", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` >=", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceLessThan(Long value) {
            addCriterion("`frozen_t1_balance` <", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceLessThanOrEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` <=", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIn(List<Long> values) {
            addCriterion("`frozen_t1_balance` in", values, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotIn(List<Long> values) {
            addCriterion("`frozen_t1_balance` not in", values, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceBetween(Long value1, Long value2) {
            addCriterion("`frozen_t1_balance` between", value1, value2, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotBetween(Long value1, Long value2) {
            addCriterion("`frozen_t1_balance` not between", value1, value2, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIsNull() {
            addCriterion("`frozen_balance` is null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIsNotNull() {
            addCriterion("`frozen_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceEqualTo(Long value) {
            addCriterion("`frozen_balance` =", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotEqualTo(Long value) {
            addCriterion("`frozen_balance` <>", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceGreaterThan(Long value) {
            addCriterion("`frozen_balance` >", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`frozen_balance` >=", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceLessThan(Long value) {
            addCriterion("`frozen_balance` <", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceLessThanOrEqualTo(Long value) {
            addCriterion("`frozen_balance` <=", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIn(List<Long> values) {
            addCriterion("`frozen_balance` in", values, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotIn(List<Long> values) {
            addCriterion("`frozen_balance` not in", values, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceBetween(Long value1, Long value2) {
            addCriterion("`frozen_balance` between", value1, value2, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotBetween(Long value1, Long value2) {
            addCriterion("`frozen_balance` not between", value1, value2, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaIsNull() {
            addCriterion("`available_balance_delta` is null");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaIsNotNull() {
            addCriterion("`available_balance_delta` is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaEqualTo(Long value) {
            addCriterion("`available_balance_delta` =", value, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaNotEqualTo(Long value) {
            addCriterion("`available_balance_delta` <>", value, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaGreaterThan(Long value) {
            addCriterion("`available_balance_delta` >", value, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaGreaterThanOrEqualTo(Long value) {
            addCriterion("`available_balance_delta` >=", value, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaLessThan(Long value) {
            addCriterion("`available_balance_delta` <", value, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaLessThanOrEqualTo(Long value) {
            addCriterion("`available_balance_delta` <=", value, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaIn(List<Long> values) {
            addCriterion("`available_balance_delta` in", values, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaNotIn(List<Long> values) {
            addCriterion("`available_balance_delta` not in", values, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaBetween(Long value1, Long value2) {
            addCriterion("`available_balance_delta` between", value1, value2, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceDeltaNotBetween(Long value1, Long value2) {
            addCriterion("`available_balance_delta` not between", value1, value2, "availableBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaIsNull() {
            addCriterion("`frozen_t1_balance_delta` is null");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaIsNotNull() {
            addCriterion("`frozen_t1_balance_delta` is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaEqualTo(Long value) {
            addCriterion("`frozen_t1_balance_delta` =", value, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaNotEqualTo(Long value) {
            addCriterion("`frozen_t1_balance_delta` <>", value, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaGreaterThan(Long value) {
            addCriterion("`frozen_t1_balance_delta` >", value, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaGreaterThanOrEqualTo(Long value) {
            addCriterion("`frozen_t1_balance_delta` >=", value, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaLessThan(Long value) {
            addCriterion("`frozen_t1_balance_delta` <", value, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaLessThanOrEqualTo(Long value) {
            addCriterion("`frozen_t1_balance_delta` <=", value, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaIn(List<Long> values) {
            addCriterion("`frozen_t1_balance_delta` in", values, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaNotIn(List<Long> values) {
            addCriterion("`frozen_t1_balance_delta` not in", values, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaBetween(Long value1, Long value2) {
            addCriterion("`frozen_t1_balance_delta` between", value1, value2, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceDeltaNotBetween(Long value1, Long value2) {
            addCriterion("`frozen_t1_balance_delta` not between", value1, value2, "frozenT1BalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaIsNull() {
            addCriterion("`frozen_balance_delta` is null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaIsNotNull() {
            addCriterion("`frozen_balance_delta` is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaEqualTo(Long value) {
            addCriterion("`frozen_balance_delta` =", value, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaNotEqualTo(Long value) {
            addCriterion("`frozen_balance_delta` <>", value, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaGreaterThan(Long value) {
            addCriterion("`frozen_balance_delta` >", value, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaGreaterThanOrEqualTo(Long value) {
            addCriterion("`frozen_balance_delta` >=", value, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaLessThan(Long value) {
            addCriterion("`frozen_balance_delta` <", value, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaLessThanOrEqualTo(Long value) {
            addCriterion("`frozen_balance_delta` <=", value, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaIn(List<Long> values) {
            addCriterion("`frozen_balance_delta` in", values, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaNotIn(List<Long> values) {
            addCriterion("`frozen_balance_delta` not in", values, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaBetween(Long value1, Long value2) {
            addCriterion("`frozen_balance_delta` between", value1, value2, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceDeltaNotBetween(Long value1, Long value2) {
            addCriterion("`frozen_balance_delta` not between", value1, value2, "frozenBalanceDelta");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIsNull() {
            addCriterion("`trans_seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIsNotNull() {
            addCriterion("`trans_seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdEqualTo(String value) {
            addCriterion("`trans_seq_id` =", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotEqualTo(String value) {
            addCriterion("`trans_seq_id` <>", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdGreaterThan(String value) {
            addCriterion("`trans_seq_id` >", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_seq_id` >=", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLessThan(String value) {
            addCriterion("`trans_seq_id` <", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLessThanOrEqualTo(String value) {
            addCriterion("`trans_seq_id` <=", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLike(String value) {
            addCriterion("`trans_seq_id` like", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotLike(String value) {
            addCriterion("`trans_seq_id` not like", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIn(List<String> values) {
            addCriterion("`trans_seq_id` in", values, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotIn(List<String> values) {
            addCriterion("`trans_seq_id` not in", values, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdBetween(String value1, String value2) {
            addCriterion("`trans_seq_id` between", value1, value2, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotBetween(String value1, String value2) {
            addCriterion("`trans_seq_id` not between", value1, value2, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransDtIsNull() {
            addCriterion("`trans_dt` is null");
            return (Criteria) this;
        }

        public Criteria andTransDtIsNotNull() {
            addCriterion("`trans_dt` is not null");
            return (Criteria) this;
        }

        public Criteria andTransDtEqualTo(String value) {
            addCriterion("`trans_dt` =", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotEqualTo(String value) {
            addCriterion("`trans_dt` <>", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtGreaterThan(String value) {
            addCriterion("`trans_dt` >", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_dt` >=", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLessThan(String value) {
            addCriterion("`trans_dt` <", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLessThanOrEqualTo(String value) {
            addCriterion("`trans_dt` <=", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLike(String value) {
            addCriterion("`trans_dt` like", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotLike(String value) {
            addCriterion("`trans_dt` not like", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtIn(List<String> values) {
            addCriterion("`trans_dt` in", values, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotIn(List<String> values) {
            addCriterion("`trans_dt` not in", values, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtBetween(String value1, String value2) {
            addCriterion("`trans_dt` between", value1, value2, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotBetween(String value1, String value2) {
            addCriterion("`trans_dt` not between", value1, value2, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransTmIsNull() {
            addCriterion("`trans_tm` is null");
            return (Criteria) this;
        }

        public Criteria andTransTmIsNotNull() {
            addCriterion("`trans_tm` is not null");
            return (Criteria) this;
        }

        public Criteria andTransTmEqualTo(String value) {
            addCriterion("`trans_tm` =", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmNotEqualTo(String value) {
            addCriterion("`trans_tm` <>", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmGreaterThan(String value) {
            addCriterion("`trans_tm` >", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_tm` >=", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmLessThan(String value) {
            addCriterion("`trans_tm` <", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmLessThanOrEqualTo(String value) {
            addCriterion("`trans_tm` <=", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmLike(String value) {
            addCriterion("`trans_tm` like", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmNotLike(String value) {
            addCriterion("`trans_tm` not like", value, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmIn(List<String> values) {
            addCriterion("`trans_tm` in", values, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmNotIn(List<String> values) {
            addCriterion("`trans_tm` not in", values, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmBetween(String value1, String value2) {
            addCriterion("`trans_tm` between", value1, value2, "transTm");
            return (Criteria) this;
        }

        public Criteria andTransTmNotBetween(String value1, String value2) {
            addCriterion("`trans_tm` not between", value1, value2, "transTm");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("`note` is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("`note` is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("`note` =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("`note` <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("`note` >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("`note` >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("`note` <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("`note` <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("`note` like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("`note` not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("`note` in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("`note` not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("`note` between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("`note` not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNull() {
            addCriterion("`relation_id` is null");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNotNull() {
            addCriterion("`relation_id` is not null");
            return (Criteria) this;
        }

        public Criteria andRelationIdEqualTo(String value) {
            addCriterion("`relation_id` =", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotEqualTo(String value) {
            addCriterion("`relation_id` <>", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThan(String value) {
            addCriterion("`relation_id` >", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThanOrEqualTo(String value) {
            addCriterion("`relation_id` >=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThan(String value) {
            addCriterion("`relation_id` <", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThanOrEqualTo(String value) {
            addCriterion("`relation_id` <=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLike(String value) {
            addCriterion("`relation_id` like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotLike(String value) {
            addCriterion("`relation_id` not like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdIn(List<String> values) {
            addCriterion("`relation_id` in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotIn(List<String> values) {
            addCriterion("`relation_id` not in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdBetween(String value1, String value2) {
            addCriterion("`relation_id` between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotBetween(String value1, String value2) {
            addCriterion("`relation_id` not between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("`tags` is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("`tags` is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("`tags` =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("`tags` <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("`tags` >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("`tags` >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("`tags` <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("`tags` <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("`tags` like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("`tags` not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("`tags` in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("`tags` not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("`tags` between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("`tags` not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNull() {
            addCriterion("`last_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNotNull() {
            addCriterion("`last_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdEqualTo(String value) {
            addCriterion("`last_oper_id` =", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotEqualTo(String value) {
            addCriterion("`last_oper_id` <>", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThan(String value) {
            addCriterion("`last_oper_id` >", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` >=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThan(String value) {
            addCriterion("`last_oper_id` <", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` <=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLike(String value) {
            addCriterion("`last_oper_id` like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotLike(String value) {
            addCriterion("`last_oper_id` not like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIn(List<String> values) {
            addCriterion("`last_oper_id` in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotIn(List<String> values) {
            addCriterion("`last_oper_id` not in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdBetween(String value1, String value2) {
            addCriterion("`last_oper_id` between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotBetween(String value1, String value2) {
            addCriterion("`last_oper_id` not between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_flow01
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_flow01
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}