package com.icpay.payment.db.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChnlMchntAccountInfoExample {
    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public ChnlMchntAccountInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_info
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_info
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChnlIdIsNull() {
            addCriterion("`chnl_id` is null");
            return (Criteria) this;
        }

        public Criteria andChnlIdIsNotNull() {
            addCriterion("`chnl_id` is not null");
            return (Criteria) this;
        }

        public Criteria andChnlIdEqualTo(String value) {
            addCriterion("`chnl_id` =", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotEqualTo(String value) {
            addCriterion("`chnl_id` <>", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThan(String value) {
            addCriterion("`chnl_id` >", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThanOrEqualTo(String value) {
            addCriterion("`chnl_id` >=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThan(String value) {
            addCriterion("`chnl_id` <", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThanOrEqualTo(String value) {
            addCriterion("`chnl_id` <=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLike(String value) {
            addCriterion("`chnl_id` like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotLike(String value) {
            addCriterion("`chnl_id` not like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdIn(List<String> values) {
            addCriterion("`chnl_id` in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotIn(List<String> values) {
            addCriterion("`chnl_id` not in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdBetween(String value1, String value2) {
            addCriterion("`chnl_id` between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotBetween(String value1, String value2) {
            addCriterion("`chnl_id` not between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdIsNull() {
            addCriterion("`curr_cd` is null");
            return (Criteria) this;
        }

        public Criteria andCurrCdIsNotNull() {
            addCriterion("`curr_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andCurrCdEqualTo(String value) {
            addCriterion("`curr_cd` =", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotEqualTo(String value) {
            addCriterion("`curr_cd` <>", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdGreaterThan(String value) {
            addCriterion("`curr_cd` >", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdGreaterThanOrEqualTo(String value) {
            addCriterion("`curr_cd` >=", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLessThan(String value) {
            addCriterion("`curr_cd` <", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLessThanOrEqualTo(String value) {
            addCriterion("`curr_cd` <=", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLike(String value) {
            addCriterion("`curr_cd` like", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotLike(String value) {
            addCriterion("`curr_cd` not like", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdIn(List<String> values) {
            addCriterion("`curr_cd` in", values, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotIn(List<String> values) {
            addCriterion("`curr_cd` not in", values, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdBetween(String value1, String value2) {
            addCriterion("`curr_cd` between", value1, value2, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotBetween(String value1, String value2) {
            addCriterion("`curr_cd` not between", value1, value2, "currCd");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("`unit` is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("`unit` is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(BigDecimal value) {
            addCriterion("`unit` =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(BigDecimal value) {
            addCriterion("`unit` <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(BigDecimal value) {
            addCriterion("`unit` >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`unit` >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(BigDecimal value) {
            addCriterion("`unit` <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`unit` <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<BigDecimal> values) {
            addCriterion("`unit` in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<BigDecimal> values) {
            addCriterion("`unit` not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`unit` between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`unit` not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIsNull() {
            addCriterion("`available_balance` is null");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIsNotNull() {
            addCriterion("`available_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceEqualTo(Long value) {
            addCriterion("`available_balance` =", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotEqualTo(Long value) {
            addCriterion("`available_balance` <>", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceGreaterThan(Long value) {
            addCriterion("`available_balance` >", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`available_balance` >=", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceLessThan(Long value) {
            addCriterion("`available_balance` <", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceLessThanOrEqualTo(Long value) {
            addCriterion("`available_balance` <=", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIn(List<Long> values) {
            addCriterion("`available_balance` in", values, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotIn(List<Long> values) {
            addCriterion("`available_balance` not in", values, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceBetween(Long value1, Long value2) {
            addCriterion("`available_balance` between", value1, value2, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotBetween(Long value1, Long value2) {
            addCriterion("`available_balance` not between", value1, value2, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceIsNull() {
            addCriterion("`obligated_balance` is null");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceIsNotNull() {
            addCriterion("`obligated_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceEqualTo(Long value) {
            addCriterion("`obligated_balance` =", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceNotEqualTo(Long value) {
            addCriterion("`obligated_balance` <>", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceGreaterThan(Long value) {
            addCriterion("`obligated_balance` >", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`obligated_balance` >=", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceLessThan(Long value) {
            addCriterion("`obligated_balance` <", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceLessThanOrEqualTo(Long value) {
            addCriterion("`obligated_balance` <=", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceIn(List<Long> values) {
            addCriterion("`obligated_balance` in", values, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceNotIn(List<Long> values) {
            addCriterion("`obligated_balance` not in", values, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceBetween(Long value1, Long value2) {
            addCriterion("`obligated_balance` between", value1, value2, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceNotBetween(Long value1, Long value2) {
            addCriterion("`obligated_balance` not between", value1, value2, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIsNull() {
            addCriterion("`frozen_t1_balance` is null");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIsNotNull() {
            addCriterion("`frozen_t1_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` =", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` <>", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceGreaterThan(Long value) {
            addCriterion("`frozen_t1_balance` >", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` >=", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceLessThan(Long value) {
            addCriterion("`frozen_t1_balance` <", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceLessThanOrEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` <=", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIn(List<Long> values) {
            addCriterion("`frozen_t1_balance` in", values, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotIn(List<Long> values) {
            addCriterion("`frozen_t1_balance` not in", values, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceBetween(Long value1, Long value2) {
            addCriterion("`frozen_t1_balance` between", value1, value2, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotBetween(Long value1, Long value2) {
            addCriterion("`frozen_t1_balance` not between", value1, value2, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIsNull() {
            addCriterion("`frozen_balance` is null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIsNotNull() {
            addCriterion("`frozen_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceEqualTo(Long value) {
            addCriterion("`frozen_balance` =", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotEqualTo(Long value) {
            addCriterion("`frozen_balance` <>", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceGreaterThan(Long value) {
            addCriterion("`frozen_balance` >", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`frozen_balance` >=", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceLessThan(Long value) {
            addCriterion("`frozen_balance` <", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceLessThanOrEqualTo(Long value) {
            addCriterion("`frozen_balance` <=", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIn(List<Long> values) {
            addCriterion("`frozen_balance` in", values, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotIn(List<Long> values) {
            addCriterion("`frozen_balance` not in", values, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceBetween(Long value1, Long value2) {
            addCriterion("`frozen_balance` between", value1, value2, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotBetween(Long value1, Long value2) {
            addCriterion("`frozen_balance` not between", value1, value2, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountIsNull() {
            addCriterion("`next_t1_trans_amount` is null");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountIsNotNull() {
            addCriterion("`next_t1_trans_amount` is not null");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountEqualTo(Long value) {
            addCriterion("`next_t1_trans_amount` =", value, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountNotEqualTo(Long value) {
            addCriterion("`next_t1_trans_amount` <>", value, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountGreaterThan(Long value) {
            addCriterion("`next_t1_trans_amount` >", value, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("`next_t1_trans_amount` >=", value, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountLessThan(Long value) {
            addCriterion("`next_t1_trans_amount` <", value, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountLessThanOrEqualTo(Long value) {
            addCriterion("`next_t1_trans_amount` <=", value, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountIn(List<Long> values) {
            addCriterion("`next_t1_trans_amount` in", values, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountNotIn(List<Long> values) {
            addCriterion("`next_t1_trans_amount` not in", values, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountBetween(Long value1, Long value2) {
            addCriterion("`next_t1_trans_amount` between", value1, value2, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andNextT1TransAmountNotBetween(Long value1, Long value2) {
            addCriterion("`next_t1_trans_amount` not between", value1, value2, "nextT1TransAmount");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtIsNull() {
            addCriterion("`dayTxnAmt` is null");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtIsNotNull() {
            addCriterion("`dayTxnAmt` is not null");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtEqualTo(Long value) {
            addCriterion("`dayTxnAmt` =", value, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtNotEqualTo(Long value) {
            addCriterion("`dayTxnAmt` <>", value, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtGreaterThan(Long value) {
            addCriterion("`dayTxnAmt` >", value, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtGreaterThanOrEqualTo(Long value) {
            addCriterion("`dayTxnAmt` >=", value, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtLessThan(Long value) {
            addCriterion("`dayTxnAmt` <", value, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtLessThanOrEqualTo(Long value) {
            addCriterion("`dayTxnAmt` <=", value, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtIn(List<Long> values) {
            addCriterion("`dayTxnAmt` in", values, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtNotIn(List<Long> values) {
            addCriterion("`dayTxnAmt` not in", values, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtBetween(Long value1, Long value2) {
            addCriterion("`dayTxnAmt` between", value1, value2, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnamtNotBetween(Long value1, Long value2) {
            addCriterion("`dayTxnAmt` not between", value1, value2, "daytxnamt");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeIsNull() {
            addCriterion("`dayTxnFee` is null");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeIsNotNull() {
            addCriterion("`dayTxnFee` is not null");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeEqualTo(Long value) {
            addCriterion("`dayTxnFee` =", value, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeNotEqualTo(Long value) {
            addCriterion("`dayTxnFee` <>", value, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeGreaterThan(Long value) {
            addCriterion("`dayTxnFee` >", value, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeGreaterThanOrEqualTo(Long value) {
            addCriterion("`dayTxnFee` >=", value, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeLessThan(Long value) {
            addCriterion("`dayTxnFee` <", value, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeLessThanOrEqualTo(Long value) {
            addCriterion("`dayTxnFee` <=", value, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeIn(List<Long> values) {
            addCriterion("`dayTxnFee` in", values, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeNotIn(List<Long> values) {
            addCriterion("`dayTxnFee` not in", values, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeBetween(Long value1, Long value2) {
            addCriterion("`dayTxnFee` between", value1, value2, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxnfeeNotBetween(Long value1, Long value2) {
            addCriterion("`dayTxnFee` not between", value1, value2, "daytxnfee");
            return (Criteria) this;
        }

        public Criteria andDaytxncountIsNull() {
            addCriterion("`dayTxnCount` is null");
            return (Criteria) this;
        }

        public Criteria andDaytxncountIsNotNull() {
            addCriterion("`dayTxnCount` is not null");
            return (Criteria) this;
        }

        public Criteria andDaytxncountEqualTo(Integer value) {
            addCriterion("`dayTxnCount` =", value, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountNotEqualTo(Integer value) {
            addCriterion("`dayTxnCount` <>", value, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountGreaterThan(Integer value) {
            addCriterion("`dayTxnCount` >", value, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountGreaterThanOrEqualTo(Integer value) {
            addCriterion("`dayTxnCount` >=", value, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountLessThan(Integer value) {
            addCriterion("`dayTxnCount` <", value, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountLessThanOrEqualTo(Integer value) {
            addCriterion("`dayTxnCount` <=", value, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountIn(List<Integer> values) {
            addCriterion("`dayTxnCount` in", values, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountNotIn(List<Integer> values) {
            addCriterion("`dayTxnCount` not in", values, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountBetween(Integer value1, Integer value2) {
            addCriterion("`dayTxnCount` between", value1, value2, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaytxncountNotBetween(Integer value1, Integer value2) {
            addCriterion("`dayTxnCount` not between", value1, value2, "daytxncount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtIsNull() {
            addCriterion("`dayWithdrawAmt` is null");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtIsNotNull() {
            addCriterion("`dayWithdrawAmt` is not null");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtEqualTo(Long value) {
            addCriterion("`dayWithdrawAmt` =", value, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtNotEqualTo(Long value) {
            addCriterion("`dayWithdrawAmt` <>", value, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtGreaterThan(Long value) {
            addCriterion("`dayWithdrawAmt` >", value, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtGreaterThanOrEqualTo(Long value) {
            addCriterion("`dayWithdrawAmt` >=", value, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtLessThan(Long value) {
            addCriterion("`dayWithdrawAmt` <", value, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtLessThanOrEqualTo(Long value) {
            addCriterion("`dayWithdrawAmt` <=", value, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtIn(List<Long> values) {
            addCriterion("`dayWithdrawAmt` in", values, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtNotIn(List<Long> values) {
            addCriterion("`dayWithdrawAmt` not in", values, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtBetween(Long value1, Long value2) {
            addCriterion("`dayWithdrawAmt` between", value1, value2, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawamtNotBetween(Long value1, Long value2) {
            addCriterion("`dayWithdrawAmt` not between", value1, value2, "daywithdrawamt");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeIsNull() {
            addCriterion("`dayWithdrawFee` is null");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeIsNotNull() {
            addCriterion("`dayWithdrawFee` is not null");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeEqualTo(Long value) {
            addCriterion("`dayWithdrawFee` =", value, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeNotEqualTo(Long value) {
            addCriterion("`dayWithdrawFee` <>", value, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeGreaterThan(Long value) {
            addCriterion("`dayWithdrawFee` >", value, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeGreaterThanOrEqualTo(Long value) {
            addCriterion("`dayWithdrawFee` >=", value, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeLessThan(Long value) {
            addCriterion("`dayWithdrawFee` <", value, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeLessThanOrEqualTo(Long value) {
            addCriterion("`dayWithdrawFee` <=", value, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeIn(List<Long> values) {
            addCriterion("`dayWithdrawFee` in", values, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeNotIn(List<Long> values) {
            addCriterion("`dayWithdrawFee` not in", values, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeBetween(Long value1, Long value2) {
            addCriterion("`dayWithdrawFee` between", value1, value2, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawfeeNotBetween(Long value1, Long value2) {
            addCriterion("`dayWithdrawFee` not between", value1, value2, "daywithdrawfee");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountIsNull() {
            addCriterion("`dayWithdrawCount` is null");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountIsNotNull() {
            addCriterion("`dayWithdrawCount` is not null");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountEqualTo(Integer value) {
            addCriterion("`dayWithdrawCount` =", value, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountNotEqualTo(Integer value) {
            addCriterion("`dayWithdrawCount` <>", value, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountGreaterThan(Integer value) {
            addCriterion("`dayWithdrawCount` >", value, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("`dayWithdrawCount` >=", value, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountLessThan(Integer value) {
            addCriterion("`dayWithdrawCount` <", value, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountLessThanOrEqualTo(Integer value) {
            addCriterion("`dayWithdrawCount` <=", value, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountIn(List<Integer> values) {
            addCriterion("`dayWithdrawCount` in", values, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountNotIn(List<Integer> values) {
            addCriterion("`dayWithdrawCount` not in", values, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountBetween(Integer value1, Integer value2) {
            addCriterion("`dayWithdrawCount` between", value1, value2, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andDaywithdrawcountNotBetween(Integer value1, Integer value2) {
            addCriterion("`dayWithdrawCount` not between", value1, value2, "daywithdrawcount");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("`tags` is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("`tags` is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("`tags` =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("`tags` <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("`tags` >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("`tags` >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("`tags` <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("`tags` <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("`tags` like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("`tags` not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("`tags` in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("`tags` not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("`tags` between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("`tags` not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_info
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_info
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}