package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChnlMchntAccountHourExample {
    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public ChnlMchntAccountHourExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_hour
     * @author USER
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHourIdIsNull() {
            addCriterion("`hour_id` is null");
            return (Criteria) this;
        }

        public Criteria andHourIdIsNotNull() {
            addCriterion("`hour_id` is not null");
            return (Criteria) this;
        }

        public Criteria andHourIdEqualTo(Integer value) {
            addCriterion("`hour_id` =", value, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdNotEqualTo(Integer value) {
            addCriterion("`hour_id` <>", value, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdGreaterThan(Integer value) {
            addCriterion("`hour_id` >", value, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`hour_id` >=", value, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdLessThan(Integer value) {
            addCriterion("`hour_id` <", value, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdLessThanOrEqualTo(Integer value) {
            addCriterion("`hour_id` <=", value, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdIn(List<Integer> values) {
            addCriterion("`hour_id` in", values, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdNotIn(List<Integer> values) {
            addCriterion("`hour_id` not in", values, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdBetween(Integer value1, Integer value2) {
            addCriterion("`hour_id` between", value1, value2, "hourId");
            return (Criteria) this;
        }

        public Criteria andHourIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`hour_id` not between", value1, value2, "hourId");
            return (Criteria) this;
        }

        public Criteria andTransDtIsNull() {
            addCriterion("`trans_dt` is null");
            return (Criteria) this;
        }

        public Criteria andTransDtIsNotNull() {
            addCriterion("`trans_dt` is not null");
            return (Criteria) this;
        }

        public Criteria andTransDtEqualTo(String value) {
            addCriterion("`trans_dt` =", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotEqualTo(String value) {
            addCriterion("`trans_dt` <>", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtGreaterThan(String value) {
            addCriterion("`trans_dt` >", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_dt` >=", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLessThan(String value) {
            addCriterion("`trans_dt` <", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLessThanOrEqualTo(String value) {
            addCriterion("`trans_dt` <=", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtLike(String value) {
            addCriterion("`trans_dt` like", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotLike(String value) {
            addCriterion("`trans_dt` not like", value, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtIn(List<String> values) {
            addCriterion("`trans_dt` in", values, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotIn(List<String> values) {
            addCriterion("`trans_dt` not in", values, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtBetween(String value1, String value2) {
            addCriterion("`trans_dt` between", value1, value2, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransDtNotBetween(String value1, String value2) {
            addCriterion("`trans_dt` not between", value1, value2, "transDt");
            return (Criteria) this;
        }

        public Criteria andTransHourIsNull() {
            addCriterion("`trans_hour` is null");
            return (Criteria) this;
        }

        public Criteria andTransHourIsNotNull() {
            addCriterion("`trans_hour` is not null");
            return (Criteria) this;
        }

        public Criteria andTransHourEqualTo(String value) {
            addCriterion("`trans_hour` =", value, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourNotEqualTo(String value) {
            addCriterion("`trans_hour` <>", value, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourGreaterThan(String value) {
            addCriterion("`trans_hour` >", value, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_hour` >=", value, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourLessThan(String value) {
            addCriterion("`trans_hour` <", value, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourLessThanOrEqualTo(String value) {
            addCriterion("`trans_hour` <=", value, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourLike(String value) {
            addCriterion("`trans_hour` like", value, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourNotLike(String value) {
            addCriterion("`trans_hour` not like", value, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourIn(List<String> values) {
            addCriterion("`trans_hour` in", values, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourNotIn(List<String> values) {
            addCriterion("`trans_hour` not in", values, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourBetween(String value1, String value2) {
            addCriterion("`trans_hour` between", value1, value2, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransHourNotBetween(String value1, String value2) {
            addCriterion("`trans_hour` not between", value1, value2, "transHour");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNull() {
            addCriterion("`trans_at` is null");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNotNull() {
            addCriterion("`trans_at` is not null");
            return (Criteria) this;
        }

        public Criteria andTransAtEqualTo(Long value) {
            addCriterion("`trans_at` =", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotEqualTo(Long value) {
            addCriterion("`trans_at` <>", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThan(Long value) {
            addCriterion("`trans_at` >", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`trans_at` >=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThan(Long value) {
            addCriterion("`trans_at` <", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThanOrEqualTo(Long value) {
            addCriterion("`trans_at` <=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtIn(List<Long> values) {
            addCriterion("`trans_at` in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotIn(List<Long> values) {
            addCriterion("`trans_at` not in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtBetween(Long value1, Long value2) {
            addCriterion("`trans_at` between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotBetween(Long value1, Long value2) {
            addCriterion("`trans_at` not between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtIsNull() {
            addCriterion("`withdraw_at` is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtIsNotNull() {
            addCriterion("`withdraw_at` is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtEqualTo(Long value) {
            addCriterion("`withdraw_at` =", value, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtNotEqualTo(Long value) {
            addCriterion("`withdraw_at` <>", value, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtGreaterThan(Long value) {
            addCriterion("`withdraw_at` >", value, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`withdraw_at` >=", value, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtLessThan(Long value) {
            addCriterion("`withdraw_at` <", value, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtLessThanOrEqualTo(Long value) {
            addCriterion("`withdraw_at` <=", value, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtIn(List<Long> values) {
            addCriterion("`withdraw_at` in", values, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtNotIn(List<Long> values) {
            addCriterion("`withdraw_at` not in", values, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtBetween(Long value1, Long value2) {
            addCriterion("`withdraw_at` between", value1, value2, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andWithdrawAtNotBetween(Long value1, Long value2) {
            addCriterion("`withdraw_at` not between", value1, value2, "withdrawAt");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIsNull() {
            addCriterion("`available_balance` is null");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIsNotNull() {
            addCriterion("`available_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceEqualTo(Long value) {
            addCriterion("`available_balance` =", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotEqualTo(Long value) {
            addCriterion("`available_balance` <>", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceGreaterThan(Long value) {
            addCriterion("`available_balance` >", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`available_balance` >=", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceLessThan(Long value) {
            addCriterion("`available_balance` <", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceLessThanOrEqualTo(Long value) {
            addCriterion("`available_balance` <=", value, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceIn(List<Long> values) {
            addCriterion("`available_balance` in", values, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotIn(List<Long> values) {
            addCriterion("`available_balance` not in", values, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceBetween(Long value1, Long value2) {
            addCriterion("`available_balance` between", value1, value2, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andAvailableBalanceNotBetween(Long value1, Long value2) {
            addCriterion("`available_balance` not between", value1, value2, "availableBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceIsNull() {
            addCriterion("`obligated_balance` is null");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceIsNotNull() {
            addCriterion("`obligated_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceEqualTo(Long value) {
            addCriterion("`obligated_balance` =", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceNotEqualTo(Long value) {
            addCriterion("`obligated_balance` <>", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceGreaterThan(Long value) {
            addCriterion("`obligated_balance` >", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`obligated_balance` >=", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceLessThan(Long value) {
            addCriterion("`obligated_balance` <", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceLessThanOrEqualTo(Long value) {
            addCriterion("`obligated_balance` <=", value, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceIn(List<Long> values) {
            addCriterion("`obligated_balance` in", values, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceNotIn(List<Long> values) {
            addCriterion("`obligated_balance` not in", values, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceBetween(Long value1, Long value2) {
            addCriterion("`obligated_balance` between", value1, value2, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andObligatedBalanceNotBetween(Long value1, Long value2) {
            addCriterion("`obligated_balance` not between", value1, value2, "obligatedBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIsNull() {
            addCriterion("`frozen_t1_balance` is null");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIsNotNull() {
            addCriterion("`frozen_t1_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` =", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` <>", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceGreaterThan(Long value) {
            addCriterion("`frozen_t1_balance` >", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` >=", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceLessThan(Long value) {
            addCriterion("`frozen_t1_balance` <", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceLessThanOrEqualTo(Long value) {
            addCriterion("`frozen_t1_balance` <=", value, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceIn(List<Long> values) {
            addCriterion("`frozen_t1_balance` in", values, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotIn(List<Long> values) {
            addCriterion("`frozen_t1_balance` not in", values, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceBetween(Long value1, Long value2) {
            addCriterion("`frozen_t1_balance` between", value1, value2, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenT1BalanceNotBetween(Long value1, Long value2) {
            addCriterion("`frozen_t1_balance` not between", value1, value2, "frozenT1Balance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIsNull() {
            addCriterion("`frozen_balance` is null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIsNotNull() {
            addCriterion("`frozen_balance` is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceEqualTo(Long value) {
            addCriterion("`frozen_balance` =", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotEqualTo(Long value) {
            addCriterion("`frozen_balance` <>", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceGreaterThan(Long value) {
            addCriterion("`frozen_balance` >", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceGreaterThanOrEqualTo(Long value) {
            addCriterion("`frozen_balance` >=", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceLessThan(Long value) {
            addCriterion("`frozen_balance` <", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceLessThanOrEqualTo(Long value) {
            addCriterion("`frozen_balance` <=", value, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceIn(List<Long> values) {
            addCriterion("`frozen_balance` in", values, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotIn(List<Long> values) {
            addCriterion("`frozen_balance` not in", values, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceBetween(Long value1, Long value2) {
            addCriterion("`frozen_balance` between", value1, value2, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andFrozenBalanceNotBetween(Long value1, Long value2) {
            addCriterion("`frozen_balance` not between", value1, value2, "frozenBalance");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("`comment` is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("`comment` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("`comment` =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("`comment` <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("`comment` >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("`comment` >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("`comment` <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("`comment` <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("`comment` like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("`comment` not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("`comment` in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("`comment` not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("`comment` between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("`comment` not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNull() {
            addCriterion("`last_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNotNull() {
            addCriterion("`last_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdEqualTo(String value) {
            addCriterion("`last_oper_id` =", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotEqualTo(String value) {
            addCriterion("`last_oper_id` <>", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThan(String value) {
            addCriterion("`last_oper_id` >", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` >=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThan(String value) {
            addCriterion("`last_oper_id` <", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` <=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLike(String value) {
            addCriterion("`last_oper_id` like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotLike(String value) {
            addCriterion("`last_oper_id` not like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIn(List<String> values) {
            addCriterion("`last_oper_id` in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotIn(List<String> values) {
            addCriterion("`last_oper_id` not in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdBetween(String value1, String value2) {
            addCriterion("`last_oper_id` between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotBetween(String value1, String value2) {
            addCriterion("`last_oper_id` not between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_hour
     * @author USER
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_mchnt_account_hour
     * @author USER
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}