package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;
import java.util.Date;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_chnl_mchnt_account_hour
 * @author USER
 *
 * @mbg.generated
 */
public class ChnlMchntAccountHour extends ChnlMchntAccountHourKey implements Serializable {
    /**
     * 充值总额
     * Database column : tbl_chnl_mchnt_account_hour.trans_at
     *
     * @mbg.generated
     */
    private Long transAt;

    /**
     * 代付总额
     * Database column : tbl_chnl_mchnt_account_hour.withdraw_at
     *
     * @mbg.generated
     */
    private Long withdrawAt;

    /**
     * 渠道D0可代付余额
     * Database column : tbl_chnl_mchnt_account_hour.available_balance
     *
     * @mbg.generated
     */
    private Long availableBalance;

    /**
     * 保留余额
     * Database column : tbl_chnl_mchnt_account_hour.obligated_balance
     *
     * @mbg.generated
     */
    private Long obligatedBalance;

    /**
     * 渠道D1余额
     * Database column : tbl_chnl_mchnt_account_hour.frozen_t1_balance
     *
     * @mbg.generated
     */
    private Long frozenT1Balance;

    /**
     * 渠道冻结金额
     * Database column : tbl_chnl_mchnt_account_hour.frozen_balance
     *
     * @mbg.generated
     */
    private Long frozenBalance;

    /**
     * 备注
     * Database column : tbl_chnl_mchnt_account_hour.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * 最后操作人员
     * Database column : tbl_chnl_mchnt_account_hour.last_oper_id
     *
     * @mbg.generated
     */
    private String lastOperId;

    /**
     * 创建时间
     * Database column : tbl_chnl_mchnt_account_hour.rec_crt_ts
     *
     * @mbg.generated
     */
    private Date recCrtTs;

    /**
     * 最近更新时间
     * Database column : tbl_chnl_mchnt_account_hour.rec_upd_ts
     *
     * @mbg.generated
     */
    private Date recUpdTs;

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public ChnlMchntAccountHour(Integer hourId, String transDt, String transHour, Long transAt, Long withdrawAt, Long availableBalance, Long obligatedBalance, Long frozenT1Balance, Long frozenBalance, String comment, String lastOperId, Date recCrtTs, Date recUpdTs) {
        super(hourId, transDt, transHour);
        this.transAt = transAt;
        this.withdrawAt = withdrawAt;
        this.availableBalance = availableBalance;
        this.obligatedBalance = obligatedBalance;
        this.frozenT1Balance = frozenT1Balance;
        this.frozenBalance = frozenBalance;
        this.comment = comment;
        this.lastOperId = lastOperId;
        this.recCrtTs = recCrtTs;
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    public ChnlMchntAccountHour() {
        super();
    }

    /**
     * 充值总额
     * @return trans_at 充值总额
     *
     * @mbg.generated
     */
    public Long getTransAt() {
        return transAt;
    }

    /**
     * 充值总额
     * @param transAt 充值总额
     *
     * @mbg.generated
     */
    public void setTransAt(Long transAt) {
        this.transAt = transAt;
    }

    /**
     * 代付总额
     * @return withdraw_at 代付总额
     *
     * @mbg.generated
     */
    public Long getWithdrawAt() {
        return withdrawAt;
    }

    /**
     * 代付总额
     * @param withdrawAt 代付总额
     *
     * @mbg.generated
     */
    public void setWithdrawAt(Long withdrawAt) {
        this.withdrawAt = withdrawAt;
    }

    /**
     * 渠道D0可代付余额
     * @return available_balance 渠道D0可代付余额
     *
     * @mbg.generated
     */
    public Long getAvailableBalance() {
        return availableBalance;
    }

    /**
     * 渠道D0可代付余额
     * @param availableBalance 渠道D0可代付余额
     *
     * @mbg.generated
     */
    public void setAvailableBalance(Long availableBalance) {
        this.availableBalance = availableBalance;
    }

    /**
     * 保留余额
     * @return obligated_balance 保留余额
     *
     * @mbg.generated
     */
    public Long getObligatedBalance() {
        return obligatedBalance;
    }

    /**
     * 保留余额
     * @param obligatedBalance 保留余额
     *
     * @mbg.generated
     */
    public void setObligatedBalance(Long obligatedBalance) {
        this.obligatedBalance = obligatedBalance;
    }

    /**
     * 渠道D1余额
     * @return frozen_t1_balance 渠道D1余额
     *
     * @mbg.generated
     */
    public Long getFrozenT1Balance() {
        return frozenT1Balance;
    }

    /**
     * 渠道D1余额
     * @param frozenT1Balance 渠道D1余额
     *
     * @mbg.generated
     */
    public void setFrozenT1Balance(Long frozenT1Balance) {
        this.frozenT1Balance = frozenT1Balance;
    }

    /**
     * 渠道冻结金额
     * @return frozen_balance 渠道冻结金额
     *
     * @mbg.generated
     */
    public Long getFrozenBalance() {
        return frozenBalance;
    }

    /**
     * 渠道冻结金额
     * @param frozenBalance 渠道冻结金额
     *
     * @mbg.generated
     */
    public void setFrozenBalance(Long frozenBalance) {
        this.frozenBalance = frozenBalance;
    }

    /**
     * 备注
     * @return comment 备注
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * 备注
     * @param comment 备注
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * 最后操作人员
     * @return last_oper_id 最后操作人员
     *
     * @mbg.generated
     */
    public String getLastOperId() {
        return lastOperId;
    }

    /**
     * 最后操作人员
     * @param lastOperId 最后操作人员
     *
     * @mbg.generated
     */
    public void setLastOperId(String lastOperId) {
        this.lastOperId = lastOperId;
    }

    /**
     * 创建时间
     * @return rec_crt_ts 创建时间
     *
     * @mbg.generated
     */
    public Date getRecCrtTs() {
        return recCrtTs;
    }

    /**
     * 创建时间
     * @param recCrtTs 创建时间
     *
     * @mbg.generated
     */
    public void setRecCrtTs(Date recCrtTs) {
        this.recCrtTs = recCrtTs;
    }

    /**
     * 最近更新时间
     * @return rec_upd_ts 最近更新时间
     *
     * @mbg.generated
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * 最近更新时间
     * @param recUpdTs 最近更新时间
     *
     * @mbg.generated
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChnlMchntAccountHour other = (ChnlMchntAccountHour) that;
        return (this.getHourId() == null ? other.getHourId() == null : this.getHourId().equals(other.getHourId()))
            && (this.getTransDt() == null ? other.getTransDt() == null : this.getTransDt().equals(other.getTransDt()))
            && (this.getTransHour() == null ? other.getTransHour() == null : this.getTransHour().equals(other.getTransHour()))
            && (this.getTransAt() == null ? other.getTransAt() == null : this.getTransAt().equals(other.getTransAt()))
            && (this.getWithdrawAt() == null ? other.getWithdrawAt() == null : this.getWithdrawAt().equals(other.getWithdrawAt()))
            && (this.getAvailableBalance() == null ? other.getAvailableBalance() == null : this.getAvailableBalance().equals(other.getAvailableBalance()))
            && (this.getObligatedBalance() == null ? other.getObligatedBalance() == null : this.getObligatedBalance().equals(other.getObligatedBalance()))
            && (this.getFrozenT1Balance() == null ? other.getFrozenT1Balance() == null : this.getFrozenT1Balance().equals(other.getFrozenT1Balance()))
            && (this.getFrozenBalance() == null ? other.getFrozenBalance() == null : this.getFrozenBalance().equals(other.getFrozenBalance()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getLastOperId() == null ? other.getLastOperId() == null : this.getLastOperId().equals(other.getLastOperId()))
            && (this.getRecCrtTs() == null ? other.getRecCrtTs() == null : this.getRecCrtTs().equals(other.getRecCrtTs()))
            && (this.getRecUpdTs() == null ? other.getRecUpdTs() == null : this.getRecUpdTs().equals(other.getRecUpdTs()));
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHourId() == null) ? 0 : getHourId().hashCode());
        result = prime * result + ((getTransDt() == null) ? 0 : getTransDt().hashCode());
        result = prime * result + ((getTransHour() == null) ? 0 : getTransHour().hashCode());
        result = prime * result + ((getTransAt() == null) ? 0 : getTransAt().hashCode());
        result = prime * result + ((getWithdrawAt() == null) ? 0 : getWithdrawAt().hashCode());
        result = prime * result + ((getAvailableBalance() == null) ? 0 : getAvailableBalance().hashCode());
        result = prime * result + ((getObligatedBalance() == null) ? 0 : getObligatedBalance().hashCode());
        result = prime * result + ((getFrozenT1Balance() == null) ? 0 : getFrozenT1Balance().hashCode());
        result = prime * result + ((getFrozenBalance() == null) ? 0 : getFrozenBalance().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getLastOperId() == null) ? 0 : getLastOperId().hashCode());
        result = prime * result + ((getRecCrtTs() == null) ? 0 : getRecCrtTs().hashCode());
        result = prime * result + ((getRecUpdTs() == null) ? 0 : getRecUpdTs().hashCode());
        return result;
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(getSuperToString());
        sb.append(", transAt=").append(transAt);
        sb.append(", withdrawAt=").append(withdrawAt);
        sb.append(", availableBalance=").append(availableBalance);
        sb.append(", obligatedBalance=").append(obligatedBalance);
        sb.append(", frozenT1Balance=").append(frozenT1Balance);
        sb.append(", frozenBalance=").append(frozenBalance);
        sb.append(", comment=").append(comment);
        sb.append(", lastOperId=").append(lastOperId);
        sb.append(", recCrtTs=").append(recCrtTs);
        sb.append(", recUpdTs=").append(recUpdTs);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Database table : tbl_chnl_mchnt_account_hour
     *
     * @mbg.generated
     */
    private String getSuperToString() {
        String s = super.toString();
        String superCls = super.getClass().getSimpleName();
        if (!(s.contains("[Hash=") && s.contains(superCls))) return "";
        int end=-1;
        int start = s.indexOf("[Hash=");
        if (start>=0) {
            	start = s.indexOf(", ", start);
            	if (start>=0) {
                		end = s.lastIndexOf(']');
                		if (end>0) 
                			return ", "+s.substring(start+2, end)+"";
                	}
            }
            return "";
        }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(ChnlMchntAccountHour source) {
        super.cloneFrom(source);
        this.transAt=source.transAt;
        this.withdrawAt=source.withdrawAt;
        this.availableBalance=source.availableBalance;
        this.obligatedBalance=source.obligatedBalance;
        this.frozenT1Balance=source.frozenT1Balance;
        this.frozenBalance=source.frozenBalance;
        this.comment=source.comment;
        this.lastOperId=source.lastOperId;
        this.recCrtTs=source.recCrtTs;
        this.recUpdTs=source.recUpdTs;
    }
}