package com.icpay.payment.db.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DailyProfitResultViewExample {
    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public DailyProfitResultViewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : view_daily_profit_result
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_daily_profit_result
     * @author Vicky
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSettleDateIsNull() {
            addCriterion("`settle_date` is null");
            return (Criteria) this;
        }

        public Criteria andSettleDateIsNotNull() {
            addCriterion("`settle_date` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleDateEqualTo(String value) {
            addCriterion("`settle_date` =", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotEqualTo(String value) {
            addCriterion("`settle_date` <>", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateGreaterThan(String value) {
            addCriterion("`settle_date` >", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_date` >=", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLessThan(String value) {
            addCriterion("`settle_date` <", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLessThanOrEqualTo(String value) {
            addCriterion("`settle_date` <=", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateLike(String value) {
            addCriterion("`settle_date` like", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotLike(String value) {
            addCriterion("`settle_date` not like", value, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateIn(List<String> values) {
            addCriterion("`settle_date` in", values, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotIn(List<String> values) {
            addCriterion("`settle_date` not in", values, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateBetween(String value1, String value2) {
            addCriterion("`settle_date` between", value1, value2, "settleDate");
            return (Criteria) this;
        }

        public Criteria andSettleDateNotBetween(String value1, String value2) {
            addCriterion("`settle_date` not between", value1, value2, "settleDate");
            return (Criteria) this;
        }

        public Criteria andChnlIdIsNull() {
            addCriterion("`chnl_id` is null");
            return (Criteria) this;
        }

        public Criteria andChnlIdIsNotNull() {
            addCriterion("`chnl_id` is not null");
            return (Criteria) this;
        }

        public Criteria andChnlIdEqualTo(String value) {
            addCriterion("`chnl_id` =", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotEqualTo(String value) {
            addCriterion("`chnl_id` <>", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThan(String value) {
            addCriterion("`chnl_id` >", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThanOrEqualTo(String value) {
            addCriterion("`chnl_id` >=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThan(String value) {
            addCriterion("`chnl_id` <", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThanOrEqualTo(String value) {
            addCriterion("`chnl_id` <=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLike(String value) {
            addCriterion("`chnl_id` like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotLike(String value) {
            addCriterion("`chnl_id` not like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdIn(List<String> values) {
            addCriterion("`chnl_id` in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotIn(List<String> values) {
            addCriterion("`chnl_id` not in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdBetween(String value1, String value2) {
            addCriterion("`chnl_id` between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotBetween(String value1, String value2) {
            addCriterion("`chnl_id` not between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmIsNull() {
            addCriterion("`mchnt_cn_nm` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmIsNotNull() {
            addCriterion("`mchnt_cn_nm` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmEqualTo(String value) {
            addCriterion("`mchnt_cn_nm` =", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmNotEqualTo(String value) {
            addCriterion("`mchnt_cn_nm` <>", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmGreaterThan(String value) {
            addCriterion("`mchnt_cn_nm` >", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cn_nm` >=", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmLessThan(String value) {
            addCriterion("`mchnt_cn_nm` <", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cn_nm` <=", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmLike(String value) {
            addCriterion("`mchnt_cn_nm` like", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmNotLike(String value) {
            addCriterion("`mchnt_cn_nm` not like", value, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmIn(List<String> values) {
            addCriterion("`mchnt_cn_nm` in", values, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmNotIn(List<String> values) {
            addCriterion("`mchnt_cn_nm` not in", values, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmBetween(String value1, String value2) {
            addCriterion("`mchnt_cn_nm` between", value1, value2, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andMchntCnNmNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cn_nm` not between", value1, value2, "mchntCnNm");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumIsNull() {
            addCriterion("`txn_amt_sum` is null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumIsNotNull() {
            addCriterion("`txn_amt_sum` is not null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumEqualTo(BigDecimal value) {
            addCriterion("`txn_amt_sum` =", value, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumNotEqualTo(BigDecimal value) {
            addCriterion("`txn_amt_sum` <>", value, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumGreaterThan(BigDecimal value) {
            addCriterion("`txn_amt_sum` >", value, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`txn_amt_sum` >=", value, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumLessThan(BigDecimal value) {
            addCriterion("`txn_amt_sum` <", value, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`txn_amt_sum` <=", value, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumIn(List<BigDecimal> values) {
            addCriterion("`txn_amt_sum` in", values, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumNotIn(List<BigDecimal> values) {
            addCriterion("`txn_amt_sum` not in", values, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`txn_amt_sum` between", value1, value2, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andTxnAmtSumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`txn_amt_sum` not between", value1, value2, "txnAmtSum");
            return (Criteria) this;
        }

        public Criteria andAgentProfitIsNull() {
            addCriterion("`agent_profit` is null");
            return (Criteria) this;
        }

        public Criteria andAgentProfitIsNotNull() {
            addCriterion("`agent_profit` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentProfitEqualTo(BigDecimal value) {
            addCriterion("`agent_profit` =", value, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitNotEqualTo(BigDecimal value) {
            addCriterion("`agent_profit` <>", value, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitGreaterThan(BigDecimal value) {
            addCriterion("`agent_profit` >", value, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`agent_profit` >=", value, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitLessThan(BigDecimal value) {
            addCriterion("`agent_profit` <", value, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`agent_profit` <=", value, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitIn(List<BigDecimal> values) {
            addCriterion("`agent_profit` in", values, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitNotIn(List<BigDecimal> values) {
            addCriterion("`agent_profit` not in", values, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`agent_profit` between", value1, value2, "agentProfit");
            return (Criteria) this;
        }

        public Criteria andAgentProfitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`agent_profit` not between", value1, value2, "agentProfit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_daily_profit_result
     * @author Vicky
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_daily_profit_result
     * @author Vicky
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}