package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;
import java.util.Date;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_settle_res_file

 *
 * @mbg.generated
 */
public class SettleResFile implements Serializable {
    /**
     * Database column : tbl_settle_res_file.seq_id
     *
     * @mbg.generated
     */
    private Integer seqId;

    /**
     * Database column : tbl_settle_res_file.settle_dt
     *
     * @mbg.generated
     */
    private String settleDt;

    /**
     * Database column : tbl_settle_res_file.settle_bt
     *
     * @mbg.generated
     */
    private Integer settleBt;

    /**
     * Database column : tbl_settle_res_file.settle_num
     *
     * @mbg.generated
     */
    private Integer settleNum;

    /**
     * Database column : tbl_settle_res_file.trans_at
     *
     * @mbg.generated
     */
    private Long transAt;

    /**
     * Database column : tbl_settle_res_file.settle_at
     *
     * @mbg.generated
     */
    private Long settleAt;

    /**
     * Database column : tbl_settle_res_file.fee_at
     *
     * @mbg.generated
     */
    private Long feeAt;

    /**
     * Database column : tbl_settle_res_file.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     * Database column : tbl_settle_res_file.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * Database column : tbl_settle_res_file.last_oper_id
     *
     * @mbg.generated
     */
    private String lastOperId;

    /**
     * Database column : tbl_settle_res_file.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * Database column : tbl_settle_res_file.rec_crt_ts
     *
     * @mbg.generated
     */
    private Date recCrtTs;

    /**
     * Database column : tbl_settle_res_file.rec_upd_ts
     *
     * @mbg.generated
     */
    private Date recUpdTs;

    /**
     * Database table : tbl_settle_res_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_settle_res_file
     *
     * @mbg.generated
     */
    public SettleResFile(Integer seqId, String settleDt, Integer settleBt, Integer settleNum, Long transAt, Long settleAt, Long feeAt, String filePath, String state, String lastOperId, String comment, Date recCrtTs, Date recUpdTs) {
        this.seqId = seqId;
        this.settleDt = settleDt;
        this.settleBt = settleBt;
        this.settleNum = settleNum;
        this.transAt = transAt;
        this.settleAt = settleAt;
        this.feeAt = feeAt;
        this.filePath = filePath;
        this.state = state;
        this.lastOperId = lastOperId;
        this.comment = comment;
        this.recCrtTs = recCrtTs;
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_settle_res_file
     *
     * @mbg.generated
     */
    public SettleResFile() {
        super();
    }

    /**
     * @return seq_id 
     *
     * @mbg.generated
     */
    public Integer getSeqId() {
        return seqId;
    }

    /**
     * @param seqId 
     *
     * @mbg.generated
     */
    public void setSeqId(Integer seqId) {
        this.seqId = seqId;
    }

    /**
     * @return settle_dt 
     *
     * @mbg.generated
     */
    public String getSettleDt() {
        return settleDt;
    }

    /**
     * @param settleDt 
     *
     * @mbg.generated
     */
    public void setSettleDt(String settleDt) {
        this.settleDt = settleDt;
    }

    /**
     * @return settle_bt 
     *
     * @mbg.generated
     */
    public Integer getSettleBt() {
        return settleBt;
    }

    /**
     * @param settleBt 
     *
     * @mbg.generated
     */
    public void setSettleBt(Integer settleBt) {
        this.settleBt = settleBt;
    }

    /**
     * @return settle_num 
     *
     * @mbg.generated
     */
    public Integer getSettleNum() {
        return settleNum;
    }

    /**
     * @param settleNum 
     *
     * @mbg.generated
     */
    public void setSettleNum(Integer settleNum) {
        this.settleNum = settleNum;
    }

    /**
     * @return trans_at 
     *
     * @mbg.generated
     */
    public Long getTransAt() {
        return transAt;
    }

    /**
     * @param transAt 
     *
     * @mbg.generated
     */
    public void setTransAt(Long transAt) {
        this.transAt = transAt;
    }

    /**
     * @return settle_at 
     *
     * @mbg.generated
     */
    public Long getSettleAt() {
        return settleAt;
    }

    /**
     * @param settleAt 
     *
     * @mbg.generated
     */
    public void setSettleAt(Long settleAt) {
        this.settleAt = settleAt;
    }

    /**
     * @return fee_at 
     *
     * @mbg.generated
     */
    public Long getFeeAt() {
        return feeAt;
    }

    /**
     * @param feeAt 
     *
     * @mbg.generated
     */
    public void setFeeAt(Long feeAt) {
        this.feeAt = feeAt;
    }

    /**
     * @return file_path 
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * @param filePath 
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * @return state 
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * @param state 
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * @return last_oper_id 
     *
     * @mbg.generated
     */
    public String getLastOperId() {
        return lastOperId;
    }

    /**
     * @param lastOperId 
     *
     * @mbg.generated
     */
    public void setLastOperId(String lastOperId) {
        this.lastOperId = lastOperId;
    }

    /**
     * @return comment 
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * @param comment 
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * @return rec_crt_ts 
     *
     * @mbg.generated
     */
    public Date getRecCrtTs() {
        return recCrtTs;
    }

    /**
     * @param recCrtTs 
     *
     * @mbg.generated
     */
    public void setRecCrtTs(Date recCrtTs) {
        this.recCrtTs = recCrtTs;
    }

    /**
     * @return rec_upd_ts 
     *
     * @mbg.generated
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * @param recUpdTs 
     *
     * @mbg.generated
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_settle_res_file
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SettleResFile other = (SettleResFile) that;
        return (this.getSeqId() == null ? other.getSeqId() == null : this.getSeqId().equals(other.getSeqId()))
            && (this.getSettleDt() == null ? other.getSettleDt() == null : this.getSettleDt().equals(other.getSettleDt()))
            && (this.getSettleBt() == null ? other.getSettleBt() == null : this.getSettleBt().equals(other.getSettleBt()))
            && (this.getSettleNum() == null ? other.getSettleNum() == null : this.getSettleNum().equals(other.getSettleNum()))
            && (this.getTransAt() == null ? other.getTransAt() == null : this.getTransAt().equals(other.getTransAt()))
            && (this.getSettleAt() == null ? other.getSettleAt() == null : this.getSettleAt().equals(other.getSettleAt()))
            && (this.getFeeAt() == null ? other.getFeeAt() == null : this.getFeeAt().equals(other.getFeeAt()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getLastOperId() == null ? other.getLastOperId() == null : this.getLastOperId().equals(other.getLastOperId()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getRecCrtTs() == null ? other.getRecCrtTs() == null : this.getRecCrtTs().equals(other.getRecCrtTs()))
            && (this.getRecUpdTs() == null ? other.getRecUpdTs() == null : this.getRecUpdTs().equals(other.getRecUpdTs()));
    }

    /**
     * Database table : tbl_settle_res_file
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSeqId() == null) ? 0 : getSeqId().hashCode());
        result = prime * result + ((getSettleDt() == null) ? 0 : getSettleDt().hashCode());
        result = prime * result + ((getSettleBt() == null) ? 0 : getSettleBt().hashCode());
        result = prime * result + ((getSettleNum() == null) ? 0 : getSettleNum().hashCode());
        result = prime * result + ((getTransAt() == null) ? 0 : getTransAt().hashCode());
        result = prime * result + ((getSettleAt() == null) ? 0 : getSettleAt().hashCode());
        result = prime * result + ((getFeeAt() == null) ? 0 : getFeeAt().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getLastOperId() == null) ? 0 : getLastOperId().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getRecCrtTs() == null) ? 0 : getRecCrtTs().hashCode());
        result = prime * result + ((getRecUpdTs() == null) ? 0 : getRecUpdTs().hashCode());
        return result;
    }

    /**
     * Database table : tbl_settle_res_file
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", seqId=").append(seqId);
        sb.append(", settleDt=").append(settleDt);
        sb.append(", settleBt=").append(settleBt);
        sb.append(", settleNum=").append(settleNum);
        sb.append(", transAt=").append(transAt);
        sb.append(", settleAt=").append(settleAt);
        sb.append(", feeAt=").append(feeAt);
        sb.append(", filePath=").append(filePath);
        sb.append(", state=").append(state);
        sb.append(", lastOperId=").append(lastOperId);
        sb.append(", comment=").append(comment);
        sb.append(", recCrtTs=").append(recCrtTs);
        sb.append(", recUpdTs=").append(recUpdTs);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(SettleResFile source) {
        this.seqId=source.seqId;
        this.settleDt=source.settleDt;
        this.settleBt=source.settleBt;
        this.settleNum=source.settleNum;
        this.transAt=source.transAt;
        this.settleAt=source.settleAt;
        this.feeAt=source.feeAt;
        this.filePath=source.filePath;
        this.state=source.state;
        this.lastOperId=source.lastOperId;
        this.comment=source.comment;
        this.recCrtTs=source.recCrtTs;
        this.recUpdTs=source.recUpdTs;
    }
}