package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;
import java.util.Date;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_telegram_merchatid
 * @author USER
 *
 * @mbg.generated
 */
public class TelegramMerchatid implements Serializable {
    /**
     * Database column : tbl_telegram_merchatid.mchnt_cd
     *
     * @mbg.generated
     */
    private String mchntCd;

    /**
     * Database column : tbl_telegram_merchatid.chat_id
     *
     * @mbg.generated
     */
    private String chatId;

    /**
     * Database column : tbl_telegram_merchatid.chat_type
     *
     * @mbg.generated
     */
    private String chatType;

    /**
     * Database column : tbl_telegram_merchatid.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * Database column : tbl_telegram_merchatid.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * Database column : tbl_telegram_merchatid.rec_crt_ts
     *
     * @mbg.generated
     */
    private Date recCrtTs;

    /**
     * Database column : tbl_telegram_merchatid.rec_upd_ts
     *
     * @mbg.generated
     */
    private Date recUpdTs;

    /**
     * Database table : tbl_telegram_merchatid
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_telegram_merchatid
     *
     * @mbg.generated
     */
    public TelegramMerchatid(String mchntCd, String chatId, String chatType, String state, String comments, Date recCrtTs, Date recUpdTs) {
        this.mchntCd = mchntCd;
        this.chatId = chatId;
        this.chatType = chatType;
        this.state = state;
        this.comments = comments;
        this.recCrtTs = recCrtTs;
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_telegram_merchatid
     *
     * @mbg.generated
     */
    public TelegramMerchatid() {
        super();
    }

    /**
     * @return mchnt_cd 
     *
     * @mbg.generated
     */
    public String getMchntCd() {
        return mchntCd;
    }

    /**
     * @param mchntCd 
     *
     * @mbg.generated
     */
    public void setMchntCd(String mchntCd) {
        this.mchntCd = mchntCd;
    }

    /**
     * @return chat_id 
     *
     * @mbg.generated
     */
    public String getChatId() {
        return chatId;
    }

    /**
     * @param chatId 
     *
     * @mbg.generated
     */
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    /**
     * @return chat_type 
     *
     * @mbg.generated
     */
    public String getChatType() {
        return chatType;
    }

    /**
     * @param chatType 
     *
     * @mbg.generated
     */
    public void setChatType(String chatType) {
        this.chatType = chatType;
    }

    /**
     * @return state 
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * @param state 
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * @return comments 
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * @param comments 
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * @return rec_crt_ts 
     *
     * @mbg.generated
     */
    public Date getRecCrtTs() {
        return recCrtTs;
    }

    /**
     * @param recCrtTs 
     *
     * @mbg.generated
     */
    public void setRecCrtTs(Date recCrtTs) {
        this.recCrtTs = recCrtTs;
    }

    /**
     * @return rec_upd_ts 
     *
     * @mbg.generated
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * @param recUpdTs 
     *
     * @mbg.generated
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_telegram_merchatid
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TelegramMerchatid other = (TelegramMerchatid) that;
        return (this.getMchntCd() == null ? other.getMchntCd() == null : this.getMchntCd().equals(other.getMchntCd()))
            && (this.getChatId() == null ? other.getChatId() == null : this.getChatId().equals(other.getChatId()))
            && (this.getChatType() == null ? other.getChatType() == null : this.getChatType().equals(other.getChatType()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getComments() == null ? other.getComments() == null : this.getComments().equals(other.getComments()))
            && (this.getRecCrtTs() == null ? other.getRecCrtTs() == null : this.getRecCrtTs().equals(other.getRecCrtTs()))
            && (this.getRecUpdTs() == null ? other.getRecUpdTs() == null : this.getRecUpdTs().equals(other.getRecUpdTs()));
    }

    /**
     * Database table : tbl_telegram_merchatid
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMchntCd() == null) ? 0 : getMchntCd().hashCode());
        result = prime * result + ((getChatId() == null) ? 0 : getChatId().hashCode());
        result = prime * result + ((getChatType() == null) ? 0 : getChatType().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getComments() == null) ? 0 : getComments().hashCode());
        result = prime * result + ((getRecCrtTs() == null) ? 0 : getRecCrtTs().hashCode());
        result = prime * result + ((getRecUpdTs() == null) ? 0 : getRecUpdTs().hashCode());
        return result;
    }

    /**
     * Database table : tbl_telegram_merchatid
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", mchntCd=").append(mchntCd);
        sb.append(", chatId=").append(chatId);
        sb.append(", chatType=").append(chatType);
        sb.append(", state=").append(state);
        sb.append(", comments=").append(comments);
        sb.append(", recCrtTs=").append(recCrtTs);
        sb.append(", recUpdTs=").append(recUpdTs);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(TelegramMerchatid source) {
        this.mchntCd=source.mchntCd;
        this.chatId=source.chatId;
        this.chatType=source.chatType;
        this.state=source.state;
        this.comments=source.comments;
        this.recCrtTs=source.recCrtTs;
        this.recUpdTs=source.recUpdTs;
    }
}