package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TracelogExample {
    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public TracelogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_tracelog_01
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_tracelog_01
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogIdIsNull() {
            addCriterion("`log_id` is null");
            return (Criteria) this;
        }

        public Criteria andLogIdIsNotNull() {
            addCriterion("`log_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLogIdEqualTo(Long value) {
            addCriterion("`log_id` =", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotEqualTo(Long value) {
            addCriterion("`log_id` <>", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThan(Long value) {
            addCriterion("`log_id` >", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`log_id` >=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThan(Long value) {
            addCriterion("`log_id` <", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThanOrEqualTo(Long value) {
            addCriterion("`log_id` <=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdIn(List<Long> values) {
            addCriterion("`log_id` in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotIn(List<Long> values) {
            addCriterion("`log_id` not in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdBetween(Long value1, Long value2) {
            addCriterion("`log_id` between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotBetween(Long value1, Long value2) {
            addCriterion("`log_id` not between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdIsNull() {
            addCriterion("`order_seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdIsNotNull() {
            addCriterion("`order_seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdEqualTo(String value) {
            addCriterion("`order_seq_id` =", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdNotEqualTo(String value) {
            addCriterion("`order_seq_id` <>", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdGreaterThan(String value) {
            addCriterion("`order_seq_id` >", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdGreaterThanOrEqualTo(String value) {
            addCriterion("`order_seq_id` >=", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdLessThan(String value) {
            addCriterion("`order_seq_id` <", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdLessThanOrEqualTo(String value) {
            addCriterion("`order_seq_id` <=", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdLike(String value) {
            addCriterion("`order_seq_id` like", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdNotLike(String value) {
            addCriterion("`order_seq_id` not like", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdIn(List<String> values) {
            addCriterion("`order_seq_id` in", values, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdNotIn(List<String> values) {
            addCriterion("`order_seq_id` not in", values, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdBetween(String value1, String value2) {
            addCriterion("`order_seq_id` between", value1, value2, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdNotBetween(String value1, String value2) {
            addCriterion("`order_seq_id` not between", value1, value2, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIsNull() {
            addCriterion("`trans_seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIsNotNull() {
            addCriterion("`trans_seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdEqualTo(String value) {
            addCriterion("`trans_seq_id` =", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotEqualTo(String value) {
            addCriterion("`trans_seq_id` <>", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdGreaterThan(String value) {
            addCriterion("`trans_seq_id` >", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_seq_id` >=", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLessThan(String value) {
            addCriterion("`trans_seq_id` <", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLessThanOrEqualTo(String value) {
            addCriterion("`trans_seq_id` <=", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLike(String value) {
            addCriterion("`trans_seq_id` like", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotLike(String value) {
            addCriterion("`trans_seq_id` not like", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIn(List<String> values) {
            addCriterion("`trans_seq_id` in", values, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotIn(List<String> values) {
            addCriterion("`trans_seq_id` not in", values, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdBetween(String value1, String value2) {
            addCriterion("`trans_seq_id` between", value1, value2, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotBetween(String value1, String value2) {
            addCriterion("`trans_seq_id` not between", value1, value2, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIsNull() {
            addCriterion("`int_trans_cd` is null");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIsNotNull() {
            addCriterion("`int_trans_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andIntTransCdEqualTo(String value) {
            addCriterion("`int_trans_cd` =", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotEqualTo(String value) {
            addCriterion("`int_trans_cd` <>", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdGreaterThan(String value) {
            addCriterion("`int_trans_cd` >", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdGreaterThanOrEqualTo(String value) {
            addCriterion("`int_trans_cd` >=", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLessThan(String value) {
            addCriterion("`int_trans_cd` <", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLessThanOrEqualTo(String value) {
            addCriterion("`int_trans_cd` <=", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLike(String value) {
            addCriterion("`int_trans_cd` like", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotLike(String value) {
            addCriterion("`int_trans_cd` not like", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIn(List<String> values) {
            addCriterion("`int_trans_cd` in", values, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotIn(List<String> values) {
            addCriterion("`int_trans_cd` not in", values, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdBetween(String value1, String value2) {
            addCriterion("`int_trans_cd` between", value1, value2, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotBetween(String value1, String value2) {
            addCriterion("`int_trans_cd` not between", value1, value2, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andTermSnIsNull() {
            addCriterion("`term_sn` is null");
            return (Criteria) this;
        }

        public Criteria andTermSnIsNotNull() {
            addCriterion("`term_sn` is not null");
            return (Criteria) this;
        }

        public Criteria andTermSnEqualTo(String value) {
            addCriterion("`term_sn` =", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotEqualTo(String value) {
            addCriterion("`term_sn` <>", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnGreaterThan(String value) {
            addCriterion("`term_sn` >", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnGreaterThanOrEqualTo(String value) {
            addCriterion("`term_sn` >=", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLessThan(String value) {
            addCriterion("`term_sn` <", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLessThanOrEqualTo(String value) {
            addCriterion("`term_sn` <=", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLike(String value) {
            addCriterion("`term_sn` like", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotLike(String value) {
            addCriterion("`term_sn` not like", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnIn(List<String> values) {
            addCriterion("`term_sn` in", values, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotIn(List<String> values) {
            addCriterion("`term_sn` not in", values, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnBetween(String value1, String value2) {
            addCriterion("`term_sn` between", value1, value2, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotBetween(String value1, String value2) {
            addCriterion("`term_sn` not between", value1, value2, "termSn");
            return (Criteria) this;
        }

        public Criteria andExtTransDtIsNull() {
            addCriterion("`ext_trans_dt` is null");
            return (Criteria) this;
        }

        public Criteria andExtTransDtIsNotNull() {
            addCriterion("`ext_trans_dt` is not null");
            return (Criteria) this;
        }

        public Criteria andExtTransDtEqualTo(String value) {
            addCriterion("`ext_trans_dt` =", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtNotEqualTo(String value) {
            addCriterion("`ext_trans_dt` <>", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtGreaterThan(String value) {
            addCriterion("`ext_trans_dt` >", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtGreaterThanOrEqualTo(String value) {
            addCriterion("`ext_trans_dt` >=", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtLessThan(String value) {
            addCriterion("`ext_trans_dt` <", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtLessThanOrEqualTo(String value) {
            addCriterion("`ext_trans_dt` <=", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtLike(String value) {
            addCriterion("`ext_trans_dt` like", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtNotLike(String value) {
            addCriterion("`ext_trans_dt` not like", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtIn(List<String> values) {
            addCriterion("`ext_trans_dt` in", values, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtNotIn(List<String> values) {
            addCriterion("`ext_trans_dt` not in", values, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtBetween(String value1, String value2) {
            addCriterion("`ext_trans_dt` between", value1, value2, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtNotBetween(String value1, String value2) {
            addCriterion("`ext_trans_dt` not between", value1, value2, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransTmIsNull() {
            addCriterion("`ext_trans_tm` is null");
            return (Criteria) this;
        }

        public Criteria andExtTransTmIsNotNull() {
            addCriterion("`ext_trans_tm` is not null");
            return (Criteria) this;
        }

        public Criteria andExtTransTmEqualTo(String value) {
            addCriterion("`ext_trans_tm` =", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmNotEqualTo(String value) {
            addCriterion("`ext_trans_tm` <>", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmGreaterThan(String value) {
            addCriterion("`ext_trans_tm` >", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmGreaterThanOrEqualTo(String value) {
            addCriterion("`ext_trans_tm` >=", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmLessThan(String value) {
            addCriterion("`ext_trans_tm` <", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmLessThanOrEqualTo(String value) {
            addCriterion("`ext_trans_tm` <=", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmLike(String value) {
            addCriterion("`ext_trans_tm` like", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmNotLike(String value) {
            addCriterion("`ext_trans_tm` not like", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmIn(List<String> values) {
            addCriterion("`ext_trans_tm` in", values, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmNotIn(List<String> values) {
            addCriterion("`ext_trans_tm` not in", values, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmBetween(String value1, String value2) {
            addCriterion("`ext_trans_tm` between", value1, value2, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmNotBetween(String value1, String value2) {
            addCriterion("`ext_trans_tm` not between", value1, value2, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("`order_id` is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("`order_id` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("`order_id` =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("`order_id` <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("`order_id` >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("`order_id` >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("`order_id` <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("`order_id` <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("`order_id` like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("`order_id` not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("`order_id` in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("`order_id` not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("`order_id` between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("`order_id` not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdIsNull() {
            addCriterion("`chnl_mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdIsNotNull() {
            addCriterion("`chnl_mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdEqualTo(String value) {
            addCriterion("`chnl_mchnt_cd` =", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdNotEqualTo(String value) {
            addCriterion("`chnl_mchnt_cd` <>", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdGreaterThan(String value) {
            addCriterion("`chnl_mchnt_cd` >", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`chnl_mchnt_cd` >=", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdLessThan(String value) {
            addCriterion("`chnl_mchnt_cd` <", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`chnl_mchnt_cd` <=", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdLike(String value) {
            addCriterion("`chnl_mchnt_cd` like", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdNotLike(String value) {
            addCriterion("`chnl_mchnt_cd` not like", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdIn(List<String> values) {
            addCriterion("`chnl_mchnt_cd` in", values, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdNotIn(List<String> values) {
            addCriterion("`chnl_mchnt_cd` not in", values, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdBetween(String value1, String value2) {
            addCriterion("`chnl_mchnt_cd` between", value1, value2, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdNotBetween(String value1, String value2) {
            addCriterion("`chnl_mchnt_cd` not between", value1, value2, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdIsNull() {
            addCriterion("`chnl_term_cd` is null");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdIsNotNull() {
            addCriterion("`chnl_term_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdEqualTo(String value) {
            addCriterion("`chnl_term_cd` =", value, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdNotEqualTo(String value) {
            addCriterion("`chnl_term_cd` <>", value, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdGreaterThan(String value) {
            addCriterion("`chnl_term_cd` >", value, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdGreaterThanOrEqualTo(String value) {
            addCriterion("`chnl_term_cd` >=", value, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdLessThan(String value) {
            addCriterion("`chnl_term_cd` <", value, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdLessThanOrEqualTo(String value) {
            addCriterion("`chnl_term_cd` <=", value, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdLike(String value) {
            addCriterion("`chnl_term_cd` like", value, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdNotLike(String value) {
            addCriterion("`chnl_term_cd` not like", value, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdIn(List<String> values) {
            addCriterion("`chnl_term_cd` in", values, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdNotIn(List<String> values) {
            addCriterion("`chnl_term_cd` not in", values, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdBetween(String value1, String value2) {
            addCriterion("`chnl_term_cd` between", value1, value2, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andChnlTermCdNotBetween(String value1, String value2) {
            addCriterion("`chnl_term_cd` not between", value1, value2, "chnlTermCd");
            return (Criteria) this;
        }

        public Criteria andTransChnlIsNull() {
            addCriterion("`trans_chnl` is null");
            return (Criteria) this;
        }

        public Criteria andTransChnlIsNotNull() {
            addCriterion("`trans_chnl` is not null");
            return (Criteria) this;
        }

        public Criteria andTransChnlEqualTo(String value) {
            addCriterion("`trans_chnl` =", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlNotEqualTo(String value) {
            addCriterion("`trans_chnl` <>", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlGreaterThan(String value) {
            addCriterion("`trans_chnl` >", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_chnl` >=", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlLessThan(String value) {
            addCriterion("`trans_chnl` <", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlLessThanOrEqualTo(String value) {
            addCriterion("`trans_chnl` <=", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlLike(String value) {
            addCriterion("`trans_chnl` like", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlNotLike(String value) {
            addCriterion("`trans_chnl` not like", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlIn(List<String> values) {
            addCriterion("`trans_chnl` in", values, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlNotIn(List<String> values) {
            addCriterion("`trans_chnl` not in", values, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlBetween(String value1, String value2) {
            addCriterion("`trans_chnl` between", value1, value2, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlNotBetween(String value1, String value2) {
            addCriterion("`trans_chnl` not between", value1, value2, "transChnl");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdIsNull() {
            addCriterion("`cups_rsp_cd` is null");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdIsNotNull() {
            addCriterion("`cups_rsp_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdEqualTo(String value) {
            addCriterion("`cups_rsp_cd` =", value, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdNotEqualTo(String value) {
            addCriterion("`cups_rsp_cd` <>", value, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdGreaterThan(String value) {
            addCriterion("`cups_rsp_cd` >", value, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdGreaterThanOrEqualTo(String value) {
            addCriterion("`cups_rsp_cd` >=", value, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdLessThan(String value) {
            addCriterion("`cups_rsp_cd` <", value, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdLessThanOrEqualTo(String value) {
            addCriterion("`cups_rsp_cd` <=", value, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdLike(String value) {
            addCriterion("`cups_rsp_cd` like", value, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdNotLike(String value) {
            addCriterion("`cups_rsp_cd` not like", value, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdIn(List<String> values) {
            addCriterion("`cups_rsp_cd` in", values, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdNotIn(List<String> values) {
            addCriterion("`cups_rsp_cd` not in", values, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdBetween(String value1, String value2) {
            addCriterion("`cups_rsp_cd` between", value1, value2, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andCupsRspCdNotBetween(String value1, String value2) {
            addCriterion("`cups_rsp_cd` not between", value1, value2, "cupsRspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdIsNull() {
            addCriterion("`rsp_cd` is null");
            return (Criteria) this;
        }

        public Criteria andRspCdIsNotNull() {
            addCriterion("`rsp_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andRspCdEqualTo(String value) {
            addCriterion("`rsp_cd` =", value, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdNotEqualTo(String value) {
            addCriterion("`rsp_cd` <>", value, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdGreaterThan(String value) {
            addCriterion("`rsp_cd` >", value, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdGreaterThanOrEqualTo(String value) {
            addCriterion("`rsp_cd` >=", value, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdLessThan(String value) {
            addCriterion("`rsp_cd` <", value, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdLessThanOrEqualTo(String value) {
            addCriterion("`rsp_cd` <=", value, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdLike(String value) {
            addCriterion("`rsp_cd` like", value, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdNotLike(String value) {
            addCriterion("`rsp_cd` not like", value, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdIn(List<String> values) {
            addCriterion("`rsp_cd` in", values, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdNotIn(List<String> values) {
            addCriterion("`rsp_cd` not in", values, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdBetween(String value1, String value2) {
            addCriterion("`rsp_cd` between", value1, value2, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspCdNotBetween(String value1, String value2) {
            addCriterion("`rsp_cd` not between", value1, value2, "rspCd");
            return (Criteria) this;
        }

        public Criteria andRspMsgIsNull() {
            addCriterion("`rsp_msg` is null");
            return (Criteria) this;
        }

        public Criteria andRspMsgIsNotNull() {
            addCriterion("`rsp_msg` is not null");
            return (Criteria) this;
        }

        public Criteria andRspMsgEqualTo(String value) {
            addCriterion("`rsp_msg` =", value, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgNotEqualTo(String value) {
            addCriterion("`rsp_msg` <>", value, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgGreaterThan(String value) {
            addCriterion("`rsp_msg` >", value, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgGreaterThanOrEqualTo(String value) {
            addCriterion("`rsp_msg` >=", value, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgLessThan(String value) {
            addCriterion("`rsp_msg` <", value, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgLessThanOrEqualTo(String value) {
            addCriterion("`rsp_msg` <=", value, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgLike(String value) {
            addCriterion("`rsp_msg` like", value, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgNotLike(String value) {
            addCriterion("`rsp_msg` not like", value, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgIn(List<String> values) {
            addCriterion("`rsp_msg` in", values, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgNotIn(List<String> values) {
            addCriterion("`rsp_msg` not in", values, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgBetween(String value1, String value2) {
            addCriterion("`rsp_msg` between", value1, value2, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andRspMsgNotBetween(String value1, String value2) {
            addCriterion("`rsp_msg` not between", value1, value2, "rspMsg");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNull() {
            addCriterion("`order_state` is null");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNotNull() {
            addCriterion("`order_state` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStateEqualTo(String value) {
            addCriterion("`order_state` =", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotEqualTo(String value) {
            addCriterion("`order_state` <>", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThan(String value) {
            addCriterion("`order_state` >", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThanOrEqualTo(String value) {
            addCriterion("`order_state` >=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThan(String value) {
            addCriterion("`order_state` <", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThanOrEqualTo(String value) {
            addCriterion("`order_state` <=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLike(String value) {
            addCriterion("`order_state` like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotLike(String value) {
            addCriterion("`order_state` not like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateIn(List<String> values) {
            addCriterion("`order_state` in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotIn(List<String> values) {
            addCriterion("`order_state` not in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateBetween(String value1, String value2) {
            addCriterion("`order_state` between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotBetween(String value1, String value2) {
            addCriterion("`order_state` not between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andLogTsIsNull() {
            addCriterion("`log_ts` is null");
            return (Criteria) this;
        }

        public Criteria andLogTsIsNotNull() {
            addCriterion("`log_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andLogTsEqualTo(Date value) {
            addCriterion("`log_ts` =", value, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsNotEqualTo(Date value) {
            addCriterion("`log_ts` <>", value, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsGreaterThan(Date value) {
            addCriterion("`log_ts` >", value, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`log_ts` >=", value, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsLessThan(Date value) {
            addCriterion("`log_ts` <", value, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsLessThanOrEqualTo(Date value) {
            addCriterion("`log_ts` <=", value, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsIn(List<Date> values) {
            addCriterion("`log_ts` in", values, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsNotIn(List<Date> values) {
            addCriterion("`log_ts` not in", values, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsBetween(Date value1, Date value2) {
            addCriterion("`log_ts` between", value1, value2, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogTsNotBetween(Date value1, Date value2) {
            addCriterion("`log_ts` not between", value1, value2, "logTs");
            return (Criteria) this;
        }

        public Criteria andLogDateIsNull() {
            addCriterion("`log_date` is null");
            return (Criteria) this;
        }

        public Criteria andLogDateIsNotNull() {
            addCriterion("`log_date` is not null");
            return (Criteria) this;
        }

        public Criteria andLogDateEqualTo(String value) {
            addCriterion("`log_date` =", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotEqualTo(String value) {
            addCriterion("`log_date` <>", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateGreaterThan(String value) {
            addCriterion("`log_date` >", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateGreaterThanOrEqualTo(String value) {
            addCriterion("`log_date` >=", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLessThan(String value) {
            addCriterion("`log_date` <", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLessThanOrEqualTo(String value) {
            addCriterion("`log_date` <=", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLike(String value) {
            addCriterion("`log_date` like", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotLike(String value) {
            addCriterion("`log_date` not like", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateIn(List<String> values) {
            addCriterion("`log_date` in", values, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotIn(List<String> values) {
            addCriterion("`log_date` not in", values, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateBetween(String value1, String value2) {
            addCriterion("`log_date` between", value1, value2, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotBetween(String value1, String value2) {
            addCriterion("`log_date` not between", value1, value2, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogTimeIsNull() {
            addCriterion("`log_time` is null");
            return (Criteria) this;
        }

        public Criteria andLogTimeIsNotNull() {
            addCriterion("`log_time` is not null");
            return (Criteria) this;
        }

        public Criteria andLogTimeEqualTo(String value) {
            addCriterion("`log_time` =", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeNotEqualTo(String value) {
            addCriterion("`log_time` <>", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeGreaterThan(String value) {
            addCriterion("`log_time` >", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeGreaterThanOrEqualTo(String value) {
            addCriterion("`log_time` >=", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeLessThan(String value) {
            addCriterion("`log_time` <", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeLessThanOrEqualTo(String value) {
            addCriterion("`log_time` <=", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeLike(String value) {
            addCriterion("`log_time` like", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeNotLike(String value) {
            addCriterion("`log_time` not like", value, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeIn(List<String> values) {
            addCriterion("`log_time` in", values, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeNotIn(List<String> values) {
            addCriterion("`log_time` not in", values, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeBetween(String value1, String value2) {
            addCriterion("`log_time` between", value1, value2, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogTimeNotBetween(String value1, String value2) {
            addCriterion("`log_time` not between", value1, value2, "logTime");
            return (Criteria) this;
        }

        public Criteria andLogNodeIsNull() {
            addCriterion("`log_node` is null");
            return (Criteria) this;
        }

        public Criteria andLogNodeIsNotNull() {
            addCriterion("`log_node` is not null");
            return (Criteria) this;
        }

        public Criteria andLogNodeEqualTo(String value) {
            addCriterion("`log_node` =", value, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeNotEqualTo(String value) {
            addCriterion("`log_node` <>", value, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeGreaterThan(String value) {
            addCriterion("`log_node` >", value, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeGreaterThanOrEqualTo(String value) {
            addCriterion("`log_node` >=", value, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeLessThan(String value) {
            addCriterion("`log_node` <", value, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeLessThanOrEqualTo(String value) {
            addCriterion("`log_node` <=", value, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeLike(String value) {
            addCriterion("`log_node` like", value, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeNotLike(String value) {
            addCriterion("`log_node` not like", value, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeIn(List<String> values) {
            addCriterion("`log_node` in", values, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeNotIn(List<String> values) {
            addCriterion("`log_node` not in", values, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeBetween(String value1, String value2) {
            addCriterion("`log_node` between", value1, value2, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogNodeNotBetween(String value1, String value2) {
            addCriterion("`log_node` not between", value1, value2, "logNode");
            return (Criteria) this;
        }

        public Criteria andLogRoleIsNull() {
            addCriterion("`log_role` is null");
            return (Criteria) this;
        }

        public Criteria andLogRoleIsNotNull() {
            addCriterion("`log_role` is not null");
            return (Criteria) this;
        }

        public Criteria andLogRoleEqualTo(String value) {
            addCriterion("`log_role` =", value, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleNotEqualTo(String value) {
            addCriterion("`log_role` <>", value, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleGreaterThan(String value) {
            addCriterion("`log_role` >", value, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleGreaterThanOrEqualTo(String value) {
            addCriterion("`log_role` >=", value, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleLessThan(String value) {
            addCriterion("`log_role` <", value, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleLessThanOrEqualTo(String value) {
            addCriterion("`log_role` <=", value, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleLike(String value) {
            addCriterion("`log_role` like", value, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleNotLike(String value) {
            addCriterion("`log_role` not like", value, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleIn(List<String> values) {
            addCriterion("`log_role` in", values, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleNotIn(List<String> values) {
            addCriterion("`log_role` not in", values, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleBetween(String value1, String value2) {
            addCriterion("`log_role` between", value1, value2, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogRoleNotBetween(String value1, String value2) {
            addCriterion("`log_role` not between", value1, value2, "logRole");
            return (Criteria) this;
        }

        public Criteria andLogLevelIsNull() {
            addCriterion("`log_level` is null");
            return (Criteria) this;
        }

        public Criteria andLogLevelIsNotNull() {
            addCriterion("`log_level` is not null");
            return (Criteria) this;
        }

        public Criteria andLogLevelEqualTo(String value) {
            addCriterion("`log_level` =", value, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelNotEqualTo(String value) {
            addCriterion("`log_level` <>", value, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelGreaterThan(String value) {
            addCriterion("`log_level` >", value, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`log_level` >=", value, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelLessThan(String value) {
            addCriterion("`log_level` <", value, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelLessThanOrEqualTo(String value) {
            addCriterion("`log_level` <=", value, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelLike(String value) {
            addCriterion("`log_level` like", value, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelNotLike(String value) {
            addCriterion("`log_level` not like", value, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelIn(List<String> values) {
            addCriterion("`log_level` in", values, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelNotIn(List<String> values) {
            addCriterion("`log_level` not in", values, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelBetween(String value1, String value2) {
            addCriterion("`log_level` between", value1, value2, "logLevel");
            return (Criteria) this;
        }

        public Criteria andLogLevelNotBetween(String value1, String value2) {
            addCriterion("`log_level` not between", value1, value2, "logLevel");
            return (Criteria) this;
        }

        public Criteria andExClsIsNull() {
            addCriterion("`ex_cls` is null");
            return (Criteria) this;
        }

        public Criteria andExClsIsNotNull() {
            addCriterion("`ex_cls` is not null");
            return (Criteria) this;
        }

        public Criteria andExClsEqualTo(String value) {
            addCriterion("`ex_cls` =", value, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsNotEqualTo(String value) {
            addCriterion("`ex_cls` <>", value, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsGreaterThan(String value) {
            addCriterion("`ex_cls` >", value, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsGreaterThanOrEqualTo(String value) {
            addCriterion("`ex_cls` >=", value, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsLessThan(String value) {
            addCriterion("`ex_cls` <", value, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsLessThanOrEqualTo(String value) {
            addCriterion("`ex_cls` <=", value, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsLike(String value) {
            addCriterion("`ex_cls` like", value, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsNotLike(String value) {
            addCriterion("`ex_cls` not like", value, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsIn(List<String> values) {
            addCriterion("`ex_cls` in", values, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsNotIn(List<String> values) {
            addCriterion("`ex_cls` not in", values, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsBetween(String value1, String value2) {
            addCriterion("`ex_cls` between", value1, value2, "exCls");
            return (Criteria) this;
        }

        public Criteria andExClsNotBetween(String value1, String value2) {
            addCriterion("`ex_cls` not between", value1, value2, "exCls");
            return (Criteria) this;
        }

        public Criteria andLogCodeIsNull() {
            addCriterion("`log_code` is null");
            return (Criteria) this;
        }

        public Criteria andLogCodeIsNotNull() {
            addCriterion("`log_code` is not null");
            return (Criteria) this;
        }

        public Criteria andLogCodeEqualTo(String value) {
            addCriterion("`log_code` =", value, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeNotEqualTo(String value) {
            addCriterion("`log_code` <>", value, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeGreaterThan(String value) {
            addCriterion("`log_code` >", value, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeGreaterThanOrEqualTo(String value) {
            addCriterion("`log_code` >=", value, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeLessThan(String value) {
            addCriterion("`log_code` <", value, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeLessThanOrEqualTo(String value) {
            addCriterion("`log_code` <=", value, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeLike(String value) {
            addCriterion("`log_code` like", value, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeNotLike(String value) {
            addCriterion("`log_code` not like", value, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeIn(List<String> values) {
            addCriterion("`log_code` in", values, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeNotIn(List<String> values) {
            addCriterion("`log_code` not in", values, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeBetween(String value1, String value2) {
            addCriterion("`log_code` between", value1, value2, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogCodeNotBetween(String value1, String value2) {
            addCriterion("`log_code` not between", value1, value2, "logCode");
            return (Criteria) this;
        }

        public Criteria andLogMsgIsNull() {
            addCriterion("`log_msg` is null");
            return (Criteria) this;
        }

        public Criteria andLogMsgIsNotNull() {
            addCriterion("`log_msg` is not null");
            return (Criteria) this;
        }

        public Criteria andLogMsgEqualTo(String value) {
            addCriterion("`log_msg` =", value, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgNotEqualTo(String value) {
            addCriterion("`log_msg` <>", value, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgGreaterThan(String value) {
            addCriterion("`log_msg` >", value, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgGreaterThanOrEqualTo(String value) {
            addCriterion("`log_msg` >=", value, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgLessThan(String value) {
            addCriterion("`log_msg` <", value, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgLessThanOrEqualTo(String value) {
            addCriterion("`log_msg` <=", value, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgLike(String value) {
            addCriterion("`log_msg` like", value, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgNotLike(String value) {
            addCriterion("`log_msg` not like", value, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgIn(List<String> values) {
            addCriterion("`log_msg` in", values, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgNotIn(List<String> values) {
            addCriterion("`log_msg` not in", values, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgBetween(String value1, String value2) {
            addCriterion("`log_msg` between", value1, value2, "logMsg");
            return (Criteria) this;
        }

        public Criteria andLogMsgNotBetween(String value1, String value2) {
            addCriterion("`log_msg` not between", value1, value2, "logMsg");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("`tags` is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("`tags` is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("`tags` =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("`tags` <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("`tags` >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("`tags` >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("`tags` <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("`tags` <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("`tags` like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("`tags` not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("`tags` in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("`tags` not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("`tags` between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("`tags` not between", value1, value2, "tags");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_tracelog_01
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_tracelog_01
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}