package com.icpay.payment.db.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TxnProfitSettleExample {
    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public TxnProfitSettleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : view_txn_profit_settle
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_txn_profit_settle
     * @author robin
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIntTransCdIsNull() {
            addCriterion("`int_trans_cd` is null");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIsNotNull() {
            addCriterion("`int_trans_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andIntTransCdEqualTo(String value) {
            addCriterion("`int_trans_cd` =", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotEqualTo(String value) {
            addCriterion("`int_trans_cd` <>", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdGreaterThan(String value) {
            addCriterion("`int_trans_cd` >", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdGreaterThanOrEqualTo(String value) {
            addCriterion("`int_trans_cd` >=", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLessThan(String value) {
            addCriterion("`int_trans_cd` <", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLessThanOrEqualTo(String value) {
            addCriterion("`int_trans_cd` <=", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLike(String value) {
            addCriterion("`int_trans_cd` like", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotLike(String value) {
            addCriterion("`int_trans_cd` not like", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIn(List<String> values) {
            addCriterion("`int_trans_cd` in", values, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotIn(List<String> values) {
            addCriterion("`int_trans_cd` not in", values, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdBetween(String value1, String value2) {
            addCriterion("`int_trans_cd` between", value1, value2, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotBetween(String value1, String value2) {
            addCriterion("`int_trans_cd` not between", value1, value2, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andTransChnlIsNull() {
            addCriterion("`trans_chnl` is null");
            return (Criteria) this;
        }

        public Criteria andTransChnlIsNotNull() {
            addCriterion("`trans_chnl` is not null");
            return (Criteria) this;
        }

        public Criteria andTransChnlEqualTo(String value) {
            addCriterion("`trans_chnl` =", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlNotEqualTo(String value) {
            addCriterion("`trans_chnl` <>", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlGreaterThan(String value) {
            addCriterion("`trans_chnl` >", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_chnl` >=", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlLessThan(String value) {
            addCriterion("`trans_chnl` <", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlLessThanOrEqualTo(String value) {
            addCriterion("`trans_chnl` <=", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlLike(String value) {
            addCriterion("`trans_chnl` like", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlNotLike(String value) {
            addCriterion("`trans_chnl` not like", value, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlIn(List<String> values) {
            addCriterion("`trans_chnl` in", values, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlNotIn(List<String> values) {
            addCriterion("`trans_chnl` not in", values, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlBetween(String value1, String value2) {
            addCriterion("`trans_chnl` between", value1, value2, "transChnl");
            return (Criteria) this;
        }

        public Criteria andTransChnlNotBetween(String value1, String value2) {
            addCriterion("`trans_chnl` not between", value1, value2, "transChnl");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdIsNull() {
            addCriterion("`chnl_mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdIsNotNull() {
            addCriterion("`chnl_mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdEqualTo(String value) {
            addCriterion("`chnl_mchnt_cd` =", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdNotEqualTo(String value) {
            addCriterion("`chnl_mchnt_cd` <>", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdGreaterThan(String value) {
            addCriterion("`chnl_mchnt_cd` >", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`chnl_mchnt_cd` >=", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdLessThan(String value) {
            addCriterion("`chnl_mchnt_cd` <", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`chnl_mchnt_cd` <=", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdLike(String value) {
            addCriterion("`chnl_mchnt_cd` like", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdNotLike(String value) {
            addCriterion("`chnl_mchnt_cd` not like", value, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdIn(List<String> values) {
            addCriterion("`chnl_mchnt_cd` in", values, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdNotIn(List<String> values) {
            addCriterion("`chnl_mchnt_cd` not in", values, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdBetween(String value1, String value2) {
            addCriterion("`chnl_mchnt_cd` between", value1, value2, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andChnlMchntCdNotBetween(String value1, String value2) {
            addCriterion("`chnl_mchnt_cd` not between", value1, value2, "chnlMchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andSumAmtIsNull() {
            addCriterion("`sum_amt` is null");
            return (Criteria) this;
        }

        public Criteria andSumAmtIsNotNull() {
            addCriterion("`sum_amt` is not null");
            return (Criteria) this;
        }

        public Criteria andSumAmtEqualTo(BigDecimal value) {
            addCriterion("`sum_amt` =", value, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtNotEqualTo(BigDecimal value) {
            addCriterion("`sum_amt` <>", value, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtGreaterThan(BigDecimal value) {
            addCriterion("`sum_amt` >", value, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`sum_amt` >=", value, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtLessThan(BigDecimal value) {
            addCriterion("`sum_amt` <", value, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`sum_amt` <=", value, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtIn(List<BigDecimal> values) {
            addCriterion("`sum_amt` in", values, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtNotIn(List<BigDecimal> values) {
            addCriterion("`sum_amt` not in", values, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`sum_amt` between", value1, value2, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`sum_amt` not between", value1, value2, "sumAmt");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeIsNull() {
            addCriterion("`sum_trans_fee` is null");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeIsNotNull() {
            addCriterion("`sum_trans_fee` is not null");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee` =", value, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeNotEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee` <>", value, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeGreaterThan(BigDecimal value) {
            addCriterion("`sum_trans_fee` >", value, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee` >=", value, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeLessThan(BigDecimal value) {
            addCriterion("`sum_trans_fee` <", value, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee` <=", value, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeIn(List<BigDecimal> values) {
            addCriterion("`sum_trans_fee` in", values, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeNotIn(List<BigDecimal> values) {
            addCriterion("`sum_trans_fee` not in", values, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`sum_trans_fee` between", value1, value2, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`sum_trans_fee` not between", value1, value2, "sumTransFee");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlIsNull() {
            addCriterion("`sum_trans_fee_chnl` is null");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlIsNotNull() {
            addCriterion("`sum_trans_fee_chnl` is not null");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee_chnl` =", value, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlNotEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee_chnl` <>", value, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlGreaterThan(BigDecimal value) {
            addCriterion("`sum_trans_fee_chnl` >", value, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee_chnl` >=", value, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlLessThan(BigDecimal value) {
            addCriterion("`sum_trans_fee_chnl` <", value, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee_chnl` <=", value, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlIn(List<BigDecimal> values) {
            addCriterion("`sum_trans_fee_chnl` in", values, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlNotIn(List<BigDecimal> values) {
            addCriterion("`sum_trans_fee_chnl` not in", values, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`sum_trans_fee_chnl` between", value1, value2, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeChnlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`sum_trans_fee_chnl` not between", value1, value2, "sumTransFeeChnl");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaIsNull() {
            addCriterion("`sum_trans_fee_delta` is null");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaIsNotNull() {
            addCriterion("`sum_trans_fee_delta` is not null");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee_delta` =", value, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaNotEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee_delta` <>", value, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaGreaterThan(BigDecimal value) {
            addCriterion("`sum_trans_fee_delta` >", value, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee_delta` >=", value, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaLessThan(BigDecimal value) {
            addCriterion("`sum_trans_fee_delta` <", value, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`sum_trans_fee_delta` <=", value, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaIn(List<BigDecimal> values) {
            addCriterion("`sum_trans_fee_delta` in", values, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaNotIn(List<BigDecimal> values) {
            addCriterion("`sum_trans_fee_delta` not in", values, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`sum_trans_fee_delta` between", value1, value2, "sumTransFeeDelta");
            return (Criteria) this;
        }

        public Criteria andSumTransFeeDeltaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`sum_trans_fee_delta` not between", value1, value2, "sumTransFeeDelta");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_txn_profit_settle
     * @author robin
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_txn_profit_settle
     * @author robin
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}