package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommonMapExample {
    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public CommonMapExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_common_map
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_common_map
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCategoryIsNull() {
            addCriterion("`category` is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("`category` is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("`category` =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("`category` <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("`category` >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("`category` >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("`category` <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("`category` <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("`category` like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("`category` not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("`category` in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("`category` not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("`category` between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("`category` not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andValIsNull() {
            addCriterion("`val` is null");
            return (Criteria) this;
        }

        public Criteria andValIsNotNull() {
            addCriterion("`val` is not null");
            return (Criteria) this;
        }

        public Criteria andValEqualTo(String value) {
            addCriterion("`val` =", value, "val");
            return (Criteria) this;
        }

        public Criteria andValNotEqualTo(String value) {
            addCriterion("`val` <>", value, "val");
            return (Criteria) this;
        }

        public Criteria andValGreaterThan(String value) {
            addCriterion("`val` >", value, "val");
            return (Criteria) this;
        }

        public Criteria andValGreaterThanOrEqualTo(String value) {
            addCriterion("`val` >=", value, "val");
            return (Criteria) this;
        }

        public Criteria andValLessThan(String value) {
            addCriterion("`val` <", value, "val");
            return (Criteria) this;
        }

        public Criteria andValLessThanOrEqualTo(String value) {
            addCriterion("`val` <=", value, "val");
            return (Criteria) this;
        }

        public Criteria andValLike(String value) {
            addCriterion("`val` like", value, "val");
            return (Criteria) this;
        }

        public Criteria andValNotLike(String value) {
            addCriterion("`val` not like", value, "val");
            return (Criteria) this;
        }

        public Criteria andValIn(List<String> values) {
            addCriterion("`val` in", values, "val");
            return (Criteria) this;
        }

        public Criteria andValNotIn(List<String> values) {
            addCriterion("`val` not in", values, "val");
            return (Criteria) this;
        }

        public Criteria andValBetween(String value1, String value2) {
            addCriterion("`val` between", value1, value2, "val");
            return (Criteria) this;
        }

        public Criteria andValNotBetween(String value1, String value2) {
            addCriterion("`val` not between", value1, value2, "val");
            return (Criteria) this;
        }

        public Criteria andValTypeIsNull() {
            addCriterion("`val_type` is null");
            return (Criteria) this;
        }

        public Criteria andValTypeIsNotNull() {
            addCriterion("`val_type` is not null");
            return (Criteria) this;
        }

        public Criteria andValTypeEqualTo(String value) {
            addCriterion("`val_type` =", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeNotEqualTo(String value) {
            addCriterion("`val_type` <>", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeGreaterThan(String value) {
            addCriterion("`val_type` >", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`val_type` >=", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeLessThan(String value) {
            addCriterion("`val_type` <", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeLessThanOrEqualTo(String value) {
            addCriterion("`val_type` <=", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeLike(String value) {
            addCriterion("`val_type` like", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeNotLike(String value) {
            addCriterion("`val_type` not like", value, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeIn(List<String> values) {
            addCriterion("`val_type` in", values, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeNotIn(List<String> values) {
            addCriterion("`val_type` not in", values, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeBetween(String value1, String value2) {
            addCriterion("`val_type` between", value1, value2, "valType");
            return (Criteria) this;
        }

        public Criteria andValTypeNotBetween(String value1, String value2) {
            addCriterion("`val_type` not between", value1, value2, "valType");
            return (Criteria) this;
        }

        public Criteria andValClassIsNull() {
            addCriterion("`val_class` is null");
            return (Criteria) this;
        }

        public Criteria andValClassIsNotNull() {
            addCriterion("`val_class` is not null");
            return (Criteria) this;
        }

        public Criteria andValClassEqualTo(String value) {
            addCriterion("`val_class` =", value, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassNotEqualTo(String value) {
            addCriterion("`val_class` <>", value, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassGreaterThan(String value) {
            addCriterion("`val_class` >", value, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassGreaterThanOrEqualTo(String value) {
            addCriterion("`val_class` >=", value, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassLessThan(String value) {
            addCriterion("`val_class` <", value, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassLessThanOrEqualTo(String value) {
            addCriterion("`val_class` <=", value, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassLike(String value) {
            addCriterion("`val_class` like", value, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassNotLike(String value) {
            addCriterion("`val_class` not like", value, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassIn(List<String> values) {
            addCriterion("`val_class` in", values, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassNotIn(List<String> values) {
            addCriterion("`val_class` not in", values, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassBetween(String value1, String value2) {
            addCriterion("`val_class` between", value1, value2, "valClass");
            return (Criteria) this;
        }

        public Criteria andValClassNotBetween(String value1, String value2) {
            addCriterion("`val_class` not between", value1, value2, "valClass");
            return (Criteria) this;
        }

        public Criteria andTsCreateIsNull() {
            addCriterion("`ts_create` is null");
            return (Criteria) this;
        }

        public Criteria andTsCreateIsNotNull() {
            addCriterion("`ts_create` is not null");
            return (Criteria) this;
        }

        public Criteria andTsCreateEqualTo(Date value) {
            addCriterion("`ts_create` =", value, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateNotEqualTo(Date value) {
            addCriterion("`ts_create` <>", value, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateGreaterThan(Date value) {
            addCriterion("`ts_create` >", value, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("`ts_create` >=", value, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateLessThan(Date value) {
            addCriterion("`ts_create` <", value, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateLessThanOrEqualTo(Date value) {
            addCriterion("`ts_create` <=", value, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateIn(List<Date> values) {
            addCriterion("`ts_create` in", values, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateNotIn(List<Date> values) {
            addCriterion("`ts_create` not in", values, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateBetween(Date value1, Date value2) {
            addCriterion("`ts_create` between", value1, value2, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsCreateNotBetween(Date value1, Date value2) {
            addCriterion("`ts_create` not between", value1, value2, "tsCreate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateIsNull() {
            addCriterion("`ts_update` is null");
            return (Criteria) this;
        }

        public Criteria andTsUpdateIsNotNull() {
            addCriterion("`ts_update` is not null");
            return (Criteria) this;
        }

        public Criteria andTsUpdateEqualTo(Date value) {
            addCriterion("`ts_update` =", value, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateNotEqualTo(Date value) {
            addCriterion("`ts_update` <>", value, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateGreaterThan(Date value) {
            addCriterion("`ts_update` >", value, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("`ts_update` >=", value, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateLessThan(Date value) {
            addCriterion("`ts_update` <", value, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateLessThanOrEqualTo(Date value) {
            addCriterion("`ts_update` <=", value, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateIn(List<Date> values) {
            addCriterion("`ts_update` in", values, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateNotIn(List<Date> values) {
            addCriterion("`ts_update` not in", values, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateBetween(Date value1, Date value2) {
            addCriterion("`ts_update` between", value1, value2, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsUpdateNotBetween(Date value1, Date value2) {
            addCriterion("`ts_update` not between", value1, value2, "tsUpdate");
            return (Criteria) this;
        }

        public Criteria andTsRefIsNull() {
            addCriterion("`ts_ref` is null");
            return (Criteria) this;
        }

        public Criteria andTsRefIsNotNull() {
            addCriterion("`ts_ref` is not null");
            return (Criteria) this;
        }

        public Criteria andTsRefEqualTo(Date value) {
            addCriterion("`ts_ref` =", value, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefNotEqualTo(Date value) {
            addCriterion("`ts_ref` <>", value, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefGreaterThan(Date value) {
            addCriterion("`ts_ref` >", value, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefGreaterThanOrEqualTo(Date value) {
            addCriterion("`ts_ref` >=", value, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefLessThan(Date value) {
            addCriterion("`ts_ref` <", value, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefLessThanOrEqualTo(Date value) {
            addCriterion("`ts_ref` <=", value, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefIn(List<Date> values) {
            addCriterion("`ts_ref` in", values, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefNotIn(List<Date> values) {
            addCriterion("`ts_ref` not in", values, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefBetween(Date value1, Date value2) {
            addCriterion("`ts_ref` between", value1, value2, "tsRef");
            return (Criteria) this;
        }

        public Criteria andTsRefNotBetween(Date value1, Date value2) {
            addCriterion("`ts_ref` not between", value1, value2, "tsRef");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIsNull() {
            addCriterion("`expire_time` is null");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIsNotNull() {
            addCriterion("`expire_time` is not null");
            return (Criteria) this;
        }

        public Criteria andExpireTimeEqualTo(Integer value) {
            addCriterion("`expire_time` =", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotEqualTo(Integer value) {
            addCriterion("`expire_time` <>", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeGreaterThan(Integer value) {
            addCriterion("`expire_time` >", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("`expire_time` >=", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeLessThan(Integer value) {
            addCriterion("`expire_time` <", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeLessThanOrEqualTo(Integer value) {
            addCriterion("`expire_time` <=", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIn(List<Integer> values) {
            addCriterion("`expire_time` in", values, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotIn(List<Integer> values) {
            addCriterion("`expire_time` not in", values, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeBetween(Integer value1, Integer value2) {
            addCriterion("`expire_time` between", value1, value2, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("`expire_time` not between", value1, value2, "expireTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_common_map
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_common_map
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}