package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MerSettleTaskLogExample {
    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public MerSettleTaskLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_mer_settle_task_log
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_mer_settle_task_log
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSeqIdIsNull() {
            addCriterion("`seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andSeqIdIsNotNull() {
            addCriterion("`seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andSeqIdEqualTo(Integer value) {
            addCriterion("`seq_id` =", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotEqualTo(Integer value) {
            addCriterion("`seq_id` <>", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdGreaterThan(Integer value) {
            addCriterion("`seq_id` >", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`seq_id` >=", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLessThan(Integer value) {
            addCriterion("`seq_id` <", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdLessThanOrEqualTo(Integer value) {
            addCriterion("`seq_id` <=", value, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdIn(List<Integer> values) {
            addCriterion("`seq_id` in", values, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotIn(List<Integer> values) {
            addCriterion("`seq_id` not in", values, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdBetween(Integer value1, Integer value2) {
            addCriterion("`seq_id` between", value1, value2, "seqId");
            return (Criteria) this;
        }

        public Criteria andSeqIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`seq_id` not between", value1, value2, "seqId");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andSettleAccountIsNull() {
            addCriterion("`settle_account` is null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountIsNotNull() {
            addCriterion("`settle_account` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountEqualTo(String value) {
            addCriterion("`settle_account` =", value, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNotEqualTo(String value) {
            addCriterion("`settle_account` <>", value, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountGreaterThan(String value) {
            addCriterion("`settle_account` >", value, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_account` >=", value, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountLessThan(String value) {
            addCriterion("`settle_account` <", value, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountLessThanOrEqualTo(String value) {
            addCriterion("`settle_account` <=", value, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountLike(String value) {
            addCriterion("`settle_account` like", value, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNotLike(String value) {
            addCriterion("`settle_account` not like", value, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountIn(List<String> values) {
            addCriterion("`settle_account` in", values, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNotIn(List<String> values) {
            addCriterion("`settle_account` not in", values, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBetween(String value1, String value2) {
            addCriterion("`settle_account` between", value1, value2, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNotBetween(String value1, String value2) {
            addCriterion("`settle_account` not between", value1, value2, "settleAccount");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameIsNull() {
            addCriterion("`settle_account_name` is null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameIsNotNull() {
            addCriterion("`settle_account_name` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameEqualTo(String value) {
            addCriterion("`settle_account_name` =", value, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameNotEqualTo(String value) {
            addCriterion("`settle_account_name` <>", value, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameGreaterThan(String value) {
            addCriterion("`settle_account_name` >", value, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_account_name` >=", value, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameLessThan(String value) {
            addCriterion("`settle_account_name` <", value, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameLessThanOrEqualTo(String value) {
            addCriterion("`settle_account_name` <=", value, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameLike(String value) {
            addCriterion("`settle_account_name` like", value, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameNotLike(String value) {
            addCriterion("`settle_account_name` not like", value, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameIn(List<String> values) {
            addCriterion("`settle_account_name` in", values, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameNotIn(List<String> values) {
            addCriterion("`settle_account_name` not in", values, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameBetween(String value1, String value2) {
            addCriterion("`settle_account_name` between", value1, value2, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountNameNotBetween(String value1, String value2) {
            addCriterion("`settle_account_name` not between", value1, value2, "settleAccountName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoIsNull() {
            addCriterion("`settle_account_area_info` is null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoIsNotNull() {
            addCriterion("`settle_account_area_info` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoEqualTo(String value) {
            addCriterion("`settle_account_area_info` =", value, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoNotEqualTo(String value) {
            addCriterion("`settle_account_area_info` <>", value, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoGreaterThan(String value) {
            addCriterion("`settle_account_area_info` >", value, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_account_area_info` >=", value, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoLessThan(String value) {
            addCriterion("`settle_account_area_info` <", value, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoLessThanOrEqualTo(String value) {
            addCriterion("`settle_account_area_info` <=", value, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoLike(String value) {
            addCriterion("`settle_account_area_info` like", value, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoNotLike(String value) {
            addCriterion("`settle_account_area_info` not like", value, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoIn(List<String> values) {
            addCriterion("`settle_account_area_info` in", values, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoNotIn(List<String> values) {
            addCriterion("`settle_account_area_info` not in", values, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoBetween(String value1, String value2) {
            addCriterion("`settle_account_area_info` between", value1, value2, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountAreaInfoNotBetween(String value1, String value2) {
            addCriterion("`settle_account_area_info` not between", value1, value2, "settleAccountAreaInfo");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameIsNull() {
            addCriterion("`settle_account_bank_name` is null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameIsNotNull() {
            addCriterion("`settle_account_bank_name` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameEqualTo(String value) {
            addCriterion("`settle_account_bank_name` =", value, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameNotEqualTo(String value) {
            addCriterion("`settle_account_bank_name` <>", value, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameGreaterThan(String value) {
            addCriterion("`settle_account_bank_name` >", value, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_account_bank_name` >=", value, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameLessThan(String value) {
            addCriterion("`settle_account_bank_name` <", value, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameLessThanOrEqualTo(String value) {
            addCriterion("`settle_account_bank_name` <=", value, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameLike(String value) {
            addCriterion("`settle_account_bank_name` like", value, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameNotLike(String value) {
            addCriterion("`settle_account_bank_name` not like", value, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameIn(List<String> values) {
            addCriterion("`settle_account_bank_name` in", values, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameNotIn(List<String> values) {
            addCriterion("`settle_account_bank_name` not in", values, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameBetween(String value1, String value2) {
            addCriterion("`settle_account_bank_name` between", value1, value2, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankNameNotBetween(String value1, String value2) {
            addCriterion("`settle_account_bank_name` not between", value1, value2, "settleAccountBankName");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeIsNull() {
            addCriterion("`settle_account_bank_code` is null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeIsNotNull() {
            addCriterion("`settle_account_bank_code` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeEqualTo(String value) {
            addCriterion("`settle_account_bank_code` =", value, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeNotEqualTo(String value) {
            addCriterion("`settle_account_bank_code` <>", value, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeGreaterThan(String value) {
            addCriterion("`settle_account_bank_code` >", value, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_account_bank_code` >=", value, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeLessThan(String value) {
            addCriterion("`settle_account_bank_code` <", value, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeLessThanOrEqualTo(String value) {
            addCriterion("`settle_account_bank_code` <=", value, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeLike(String value) {
            addCriterion("`settle_account_bank_code` like", value, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeNotLike(String value) {
            addCriterion("`settle_account_bank_code` not like", value, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeIn(List<String> values) {
            addCriterion("`settle_account_bank_code` in", values, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeNotIn(List<String> values) {
            addCriterion("`settle_account_bank_code` not in", values, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeBetween(String value1, String value2) {
            addCriterion("`settle_account_bank_code` between", value1, value2, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleAccountBankCodeNotBetween(String value1, String value2) {
            addCriterion("`settle_account_bank_code` not between", value1, value2, "settleAccountBankCode");
            return (Criteria) this;
        }

        public Criteria andSettleDtIsNull() {
            addCriterion("`settle_dt` is null");
            return (Criteria) this;
        }

        public Criteria andSettleDtIsNotNull() {
            addCriterion("`settle_dt` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleDtEqualTo(String value) {
            addCriterion("`settle_dt` =", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtNotEqualTo(String value) {
            addCriterion("`settle_dt` <>", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtGreaterThan(String value) {
            addCriterion("`settle_dt` >", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_dt` >=", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtLessThan(String value) {
            addCriterion("`settle_dt` <", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtLessThanOrEqualTo(String value) {
            addCriterion("`settle_dt` <=", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtLike(String value) {
            addCriterion("`settle_dt` like", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtNotLike(String value) {
            addCriterion("`settle_dt` not like", value, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtIn(List<String> values) {
            addCriterion("`settle_dt` in", values, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtNotIn(List<String> values) {
            addCriterion("`settle_dt` not in", values, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtBetween(String value1, String value2) {
            addCriterion("`settle_dt` between", value1, value2, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleDtNotBetween(String value1, String value2) {
            addCriterion("`settle_dt` not between", value1, value2, "settleDt");
            return (Criteria) this;
        }

        public Criteria andSettleBtIsNull() {
            addCriterion("`settle_bt` is null");
            return (Criteria) this;
        }

        public Criteria andSettleBtIsNotNull() {
            addCriterion("`settle_bt` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleBtEqualTo(Integer value) {
            addCriterion("`settle_bt` =", value, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtNotEqualTo(Integer value) {
            addCriterion("`settle_bt` <>", value, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtGreaterThan(Integer value) {
            addCriterion("`settle_bt` >", value, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtGreaterThanOrEqualTo(Integer value) {
            addCriterion("`settle_bt` >=", value, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtLessThan(Integer value) {
            addCriterion("`settle_bt` <", value, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtLessThanOrEqualTo(Integer value) {
            addCriterion("`settle_bt` <=", value, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtIn(List<Integer> values) {
            addCriterion("`settle_bt` in", values, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtNotIn(List<Integer> values) {
            addCriterion("`settle_bt` not in", values, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtBetween(Integer value1, Integer value2) {
            addCriterion("`settle_bt` between", value1, value2, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettleBtNotBetween(Integer value1, Integer value2) {
            addCriterion("`settle_bt` not between", value1, value2, "settleBt");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIsNull() {
            addCriterion("`settle_period` is null");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIsNotNull() {
            addCriterion("`settle_period` is not null");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodEqualTo(String value) {
            addCriterion("`settle_period` =", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotEqualTo(String value) {
            addCriterion("`settle_period` <>", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodGreaterThan(String value) {
            addCriterion("`settle_period` >", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_period` >=", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLessThan(String value) {
            addCriterion("`settle_period` <", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLessThanOrEqualTo(String value) {
            addCriterion("`settle_period` <=", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLike(String value) {
            addCriterion("`settle_period` like", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotLike(String value) {
            addCriterion("`settle_period` not like", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIn(List<String> values) {
            addCriterion("`settle_period` in", values, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotIn(List<String> values) {
            addCriterion("`settle_period` not in", values, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodBetween(String value1, String value2) {
            addCriterion("`settle_period` between", value1, value2, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotBetween(String value1, String value2) {
            addCriterion("`settle_period` not between", value1, value2, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andTransNumIsNull() {
            addCriterion("`trans_num` is null");
            return (Criteria) this;
        }

        public Criteria andTransNumIsNotNull() {
            addCriterion("`trans_num` is not null");
            return (Criteria) this;
        }

        public Criteria andTransNumEqualTo(Integer value) {
            addCriterion("`trans_num` =", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumNotEqualTo(Integer value) {
            addCriterion("`trans_num` <>", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumGreaterThan(Integer value) {
            addCriterion("`trans_num` >", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("`trans_num` >=", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumLessThan(Integer value) {
            addCriterion("`trans_num` <", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumLessThanOrEqualTo(Integer value) {
            addCriterion("`trans_num` <=", value, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumIn(List<Integer> values) {
            addCriterion("`trans_num` in", values, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumNotIn(List<Integer> values) {
            addCriterion("`trans_num` not in", values, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumBetween(Integer value1, Integer value2) {
            addCriterion("`trans_num` between", value1, value2, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransNumNotBetween(Integer value1, Integer value2) {
            addCriterion("`trans_num` not between", value1, value2, "transNum");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNull() {
            addCriterion("`trans_at` is null");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNotNull() {
            addCriterion("`trans_at` is not null");
            return (Criteria) this;
        }

        public Criteria andTransAtEqualTo(Long value) {
            addCriterion("`trans_at` =", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotEqualTo(Long value) {
            addCriterion("`trans_at` <>", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThan(Long value) {
            addCriterion("`trans_at` >", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`trans_at` >=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThan(Long value) {
            addCriterion("`trans_at` <", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThanOrEqualTo(Long value) {
            addCriterion("`trans_at` <=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtIn(List<Long> values) {
            addCriterion("`trans_at` in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotIn(List<Long> values) {
            addCriterion("`trans_at` not in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtBetween(Long value1, Long value2) {
            addCriterion("`trans_at` between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotBetween(Long value1, Long value2) {
            addCriterion("`trans_at` not between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtIsNull() {
            addCriterion("`settle_at` is null");
            return (Criteria) this;
        }

        public Criteria andSettleAtIsNotNull() {
            addCriterion("`settle_at` is not null");
            return (Criteria) this;
        }

        public Criteria andSettleAtEqualTo(Long value) {
            addCriterion("`settle_at` =", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtNotEqualTo(Long value) {
            addCriterion("`settle_at` <>", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtGreaterThan(Long value) {
            addCriterion("`settle_at` >", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`settle_at` >=", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtLessThan(Long value) {
            addCriterion("`settle_at` <", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtLessThanOrEqualTo(Long value) {
            addCriterion("`settle_at` <=", value, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtIn(List<Long> values) {
            addCriterion("`settle_at` in", values, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtNotIn(List<Long> values) {
            addCriterion("`settle_at` not in", values, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtBetween(Long value1, Long value2) {
            addCriterion("`settle_at` between", value1, value2, "settleAt");
            return (Criteria) this;
        }

        public Criteria andSettleAtNotBetween(Long value1, Long value2) {
            addCriterion("`settle_at` not between", value1, value2, "settleAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtIsNull() {
            addCriterion("`fee_at` is null");
            return (Criteria) this;
        }

        public Criteria andFeeAtIsNotNull() {
            addCriterion("`fee_at` is not null");
            return (Criteria) this;
        }

        public Criteria andFeeAtEqualTo(Long value) {
            addCriterion("`fee_at` =", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtNotEqualTo(Long value) {
            addCriterion("`fee_at` <>", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtGreaterThan(Long value) {
            addCriterion("`fee_at` >", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`fee_at` >=", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtLessThan(Long value) {
            addCriterion("`fee_at` <", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtLessThanOrEqualTo(Long value) {
            addCriterion("`fee_at` <=", value, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtIn(List<Long> values) {
            addCriterion("`fee_at` in", values, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtNotIn(List<Long> values) {
            addCriterion("`fee_at` not in", values, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtBetween(Long value1, Long value2) {
            addCriterion("`fee_at` between", value1, value2, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFeeAtNotBetween(Long value1, Long value2) {
            addCriterion("`fee_at` not between", value1, value2, "feeAt");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("`file_path` is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("`file_path` is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("`file_path` =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("`file_path` <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("`file_path` >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("`file_path` >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("`file_path` <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("`file_path` <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("`file_path` like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("`file_path` not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("`file_path` in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("`file_path` not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("`file_path` between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("`file_path` not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNull() {
            addCriterion("`last_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNotNull() {
            addCriterion("`last_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdEqualTo(String value) {
            addCriterion("`last_oper_id` =", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotEqualTo(String value) {
            addCriterion("`last_oper_id` <>", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThan(String value) {
            addCriterion("`last_oper_id` >", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` >=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThan(String value) {
            addCriterion("`last_oper_id` <", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` <=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLike(String value) {
            addCriterion("`last_oper_id` like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotLike(String value) {
            addCriterion("`last_oper_id` not like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIn(List<String> values) {
            addCriterion("`last_oper_id` in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotIn(List<String> values) {
            addCriterion("`last_oper_id` not in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdBetween(String value1, String value2) {
            addCriterion("`last_oper_id` between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotBetween(String value1, String value2) {
            addCriterion("`last_oper_id` not between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("`comment` is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("`comment` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("`comment` =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("`comment` <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("`comment` >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("`comment` >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("`comment` <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("`comment` <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("`comment` like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("`comment` not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("`comment` in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("`comment` not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("`comment` between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("`comment` not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_mer_settle_task_log
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_mer_settle_task_log
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}