package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChnlInfoExample {
    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public ChnlInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_chnl_info
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_info
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChnlIdIsNull() {
            addCriterion("`chnl_id` is null");
            return (Criteria) this;
        }

        public Criteria andChnlIdIsNotNull() {
            addCriterion("`chnl_id` is not null");
            return (Criteria) this;
        }

        public Criteria andChnlIdEqualTo(String value) {
            addCriterion("`chnl_id` =", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotEqualTo(String value) {
            addCriterion("`chnl_id` <>", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThan(String value) {
            addCriterion("`chnl_id` >", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdGreaterThanOrEqualTo(String value) {
            addCriterion("`chnl_id` >=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThan(String value) {
            addCriterion("`chnl_id` <", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLessThanOrEqualTo(String value) {
            addCriterion("`chnl_id` <=", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdLike(String value) {
            addCriterion("`chnl_id` like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotLike(String value) {
            addCriterion("`chnl_id` not like", value, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdIn(List<String> values) {
            addCriterion("`chnl_id` in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotIn(List<String> values) {
            addCriterion("`chnl_id` not in", values, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdBetween(String value1, String value2) {
            addCriterion("`chnl_id` between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlIdNotBetween(String value1, String value2) {
            addCriterion("`chnl_id` not between", value1, value2, "chnlId");
            return (Criteria) this;
        }

        public Criteria andChnlDescIsNull() {
            addCriterion("`chnl_desc` is null");
            return (Criteria) this;
        }

        public Criteria andChnlDescIsNotNull() {
            addCriterion("`chnl_desc` is not null");
            return (Criteria) this;
        }

        public Criteria andChnlDescEqualTo(String value) {
            addCriterion("`chnl_desc` =", value, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescNotEqualTo(String value) {
            addCriterion("`chnl_desc` <>", value, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescGreaterThan(String value) {
            addCriterion("`chnl_desc` >", value, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescGreaterThanOrEqualTo(String value) {
            addCriterion("`chnl_desc` >=", value, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescLessThan(String value) {
            addCriterion("`chnl_desc` <", value, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescLessThanOrEqualTo(String value) {
            addCriterion("`chnl_desc` <=", value, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescLike(String value) {
            addCriterion("`chnl_desc` like", value, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescNotLike(String value) {
            addCriterion("`chnl_desc` not like", value, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescIn(List<String> values) {
            addCriterion("`chnl_desc` in", values, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescNotIn(List<String> values) {
            addCriterion("`chnl_desc` not in", values, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescBetween(String value1, String value2) {
            addCriterion("`chnl_desc` between", value1, value2, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andChnlDescNotBetween(String value1, String value2) {
            addCriterion("`chnl_desc` not between", value1, value2, "chnlDesc");
            return (Criteria) this;
        }

        public Criteria andTransTypeIsNull() {
            addCriterion("`trans_type` is null");
            return (Criteria) this;
        }

        public Criteria andTransTypeIsNotNull() {
            addCriterion("`trans_type` is not null");
            return (Criteria) this;
        }

        public Criteria andTransTypeEqualTo(String value) {
            addCriterion("`trans_type` =", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotEqualTo(String value) {
            addCriterion("`trans_type` <>", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeGreaterThan(String value) {
            addCriterion("`trans_type` >", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_type` >=", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLessThan(String value) {
            addCriterion("`trans_type` <", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLessThanOrEqualTo(String value) {
            addCriterion("`trans_type` <=", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeLike(String value) {
            addCriterion("`trans_type` like", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotLike(String value) {
            addCriterion("`trans_type` not like", value, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeIn(List<String> values) {
            addCriterion("`trans_type` in", values, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotIn(List<String> values) {
            addCriterion("`trans_type` not in", values, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeBetween(String value1, String value2) {
            addCriterion("`trans_type` between", value1, value2, "transType");
            return (Criteria) this;
        }

        public Criteria andTransTypeNotBetween(String value1, String value2) {
            addCriterion("`trans_type` not between", value1, value2, "transType");
            return (Criteria) this;
        }

        public Criteria andFeeLevelIsNull() {
            addCriterion("`fee_level` is null");
            return (Criteria) this;
        }

        public Criteria andFeeLevelIsNotNull() {
            addCriterion("`fee_level` is not null");
            return (Criteria) this;
        }

        public Criteria andFeeLevelEqualTo(String value) {
            addCriterion("`fee_level` =", value, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelNotEqualTo(String value) {
            addCriterion("`fee_level` <>", value, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelGreaterThan(String value) {
            addCriterion("`fee_level` >", value, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelGreaterThanOrEqualTo(String value) {
            addCriterion("`fee_level` >=", value, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelLessThan(String value) {
            addCriterion("`fee_level` <", value, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelLessThanOrEqualTo(String value) {
            addCriterion("`fee_level` <=", value, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelLike(String value) {
            addCriterion("`fee_level` like", value, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelNotLike(String value) {
            addCriterion("`fee_level` not like", value, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelIn(List<String> values) {
            addCriterion("`fee_level` in", values, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelNotIn(List<String> values) {
            addCriterion("`fee_level` not in", values, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelBetween(String value1, String value2) {
            addCriterion("`fee_level` between", value1, value2, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andFeeLevelNotBetween(String value1, String value2) {
            addCriterion("`fee_level` not between", value1, value2, "feeLevel");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andTransLimitIsNull() {
            addCriterion("`trans_limit` is null");
            return (Criteria) this;
        }

        public Criteria andTransLimitIsNotNull() {
            addCriterion("`trans_limit` is not null");
            return (Criteria) this;
        }

        public Criteria andTransLimitEqualTo(String value) {
            addCriterion("`trans_limit` =", value, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitNotEqualTo(String value) {
            addCriterion("`trans_limit` <>", value, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitGreaterThan(String value) {
            addCriterion("`trans_limit` >", value, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_limit` >=", value, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitLessThan(String value) {
            addCriterion("`trans_limit` <", value, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitLessThanOrEqualTo(String value) {
            addCriterion("`trans_limit` <=", value, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitLike(String value) {
            addCriterion("`trans_limit` like", value, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitNotLike(String value) {
            addCriterion("`trans_limit` not like", value, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitIn(List<String> values) {
            addCriterion("`trans_limit` in", values, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitNotIn(List<String> values) {
            addCriterion("`trans_limit` not in", values, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitBetween(String value1, String value2) {
            addCriterion("`trans_limit` between", value1, value2, "transLimit");
            return (Criteria) this;
        }

        public Criteria andTransLimitNotBetween(String value1, String value2) {
            addCriterion("`trans_limit` not between", value1, value2, "transLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitIsNull() {
            addCriterion("`day_trans_limit` is null");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitIsNotNull() {
            addCriterion("`day_trans_limit` is not null");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitEqualTo(String value) {
            addCriterion("`day_trans_limit` =", value, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitNotEqualTo(String value) {
            addCriterion("`day_trans_limit` <>", value, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitGreaterThan(String value) {
            addCriterion("`day_trans_limit` >", value, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitGreaterThanOrEqualTo(String value) {
            addCriterion("`day_trans_limit` >=", value, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitLessThan(String value) {
            addCriterion("`day_trans_limit` <", value, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitLessThanOrEqualTo(String value) {
            addCriterion("`day_trans_limit` <=", value, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitLike(String value) {
            addCriterion("`day_trans_limit` like", value, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitNotLike(String value) {
            addCriterion("`day_trans_limit` not like", value, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitIn(List<String> values) {
            addCriterion("`day_trans_limit` in", values, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitNotIn(List<String> values) {
            addCriterion("`day_trans_limit` not in", values, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitBetween(String value1, String value2) {
            addCriterion("`day_trans_limit` between", value1, value2, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andDayTransLimitNotBetween(String value1, String value2) {
            addCriterion("`day_trans_limit` not between", value1, value2, "dayTransLimit");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsIsNull() {
            addCriterion("`operate_conditions` is null");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsIsNotNull() {
            addCriterion("`operate_conditions` is not null");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsEqualTo(String value) {
            addCriterion("`operate_conditions` =", value, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsNotEqualTo(String value) {
            addCriterion("`operate_conditions` <>", value, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsGreaterThan(String value) {
            addCriterion("`operate_conditions` >", value, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsGreaterThanOrEqualTo(String value) {
            addCriterion("`operate_conditions` >=", value, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsLessThan(String value) {
            addCriterion("`operate_conditions` <", value, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsLessThanOrEqualTo(String value) {
            addCriterion("`operate_conditions` <=", value, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsLike(String value) {
            addCriterion("`operate_conditions` like", value, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsNotLike(String value) {
            addCriterion("`operate_conditions` not like", value, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsIn(List<String> values) {
            addCriterion("`operate_conditions` in", values, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsNotIn(List<String> values) {
            addCriterion("`operate_conditions` not in", values, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsBetween(String value1, String value2) {
            addCriterion("`operate_conditions` between", value1, value2, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andOperateConditionsNotBetween(String value1, String value2) {
            addCriterion("`operate_conditions` not between", value1, value2, "operateConditions");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNull() {
            addCriterion("`last_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNotNull() {
            addCriterion("`last_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdEqualTo(String value) {
            addCriterion("`last_oper_id` =", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotEqualTo(String value) {
            addCriterion("`last_oper_id` <>", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThan(String value) {
            addCriterion("`last_oper_id` >", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` >=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThan(String value) {
            addCriterion("`last_oper_id` <", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` <=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLike(String value) {
            addCriterion("`last_oper_id` like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotLike(String value) {
            addCriterion("`last_oper_id` not like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIn(List<String> values) {
            addCriterion("`last_oper_id` in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotIn(List<String> values) {
            addCriterion("`last_oper_id` not in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdBetween(String value1, String value2) {
            addCriterion("`last_oper_id` between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotBetween(String value1, String value2) {
            addCriterion("`last_oper_id` not between", value1, value2, "lastOperId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_info
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chnl_info
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}