package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatMsgManualExample {
    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public ChatMsgManualExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_chat_msg_manual
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chat_msg_manual
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCatelogIsNull() {
            addCriterion("`catelog` is null");
            return (Criteria) this;
        }

        public Criteria andCatelogIsNotNull() {
            addCriterion("`catelog` is not null");
            return (Criteria) this;
        }

        public Criteria andCatelogEqualTo(String value) {
            addCriterion("`catelog` =", value, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogNotEqualTo(String value) {
            addCriterion("`catelog` <>", value, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogGreaterThan(String value) {
            addCriterion("`catelog` >", value, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogGreaterThanOrEqualTo(String value) {
            addCriterion("`catelog` >=", value, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogLessThan(String value) {
            addCriterion("`catelog` <", value, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogLessThanOrEqualTo(String value) {
            addCriterion("`catelog` <=", value, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogLike(String value) {
            addCriterion("`catelog` like", value, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogNotLike(String value) {
            addCriterion("`catelog` not like", value, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogIn(List<String> values) {
            addCriterion("`catelog` in", values, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogNotIn(List<String> values) {
            addCriterion("`catelog` not in", values, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogBetween(String value1, String value2) {
            addCriterion("`catelog` between", value1, value2, "catelog");
            return (Criteria) this;
        }

        public Criteria andCatelogNotBetween(String value1, String value2) {
            addCriterion("`catelog` not between", value1, value2, "catelog");
            return (Criteria) this;
        }

        public Criteria andCmdKeyIsNull() {
            addCriterion("`cmd_key` is null");
            return (Criteria) this;
        }

        public Criteria andCmdKeyIsNotNull() {
            addCriterion("`cmd_key` is not null");
            return (Criteria) this;
        }

        public Criteria andCmdKeyEqualTo(String value) {
            addCriterion("`cmd_key` =", value, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyNotEqualTo(String value) {
            addCriterion("`cmd_key` <>", value, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyGreaterThan(String value) {
            addCriterion("`cmd_key` >", value, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyGreaterThanOrEqualTo(String value) {
            addCriterion("`cmd_key` >=", value, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyLessThan(String value) {
            addCriterion("`cmd_key` <", value, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyLessThanOrEqualTo(String value) {
            addCriterion("`cmd_key` <=", value, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyLike(String value) {
            addCriterion("`cmd_key` like", value, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyNotLike(String value) {
            addCriterion("`cmd_key` not like", value, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyIn(List<String> values) {
            addCriterion("`cmd_key` in", values, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyNotIn(List<String> values) {
            addCriterion("`cmd_key` not in", values, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyBetween(String value1, String value2) {
            addCriterion("`cmd_key` between", value1, value2, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdKeyNotBetween(String value1, String value2) {
            addCriterion("`cmd_key` not between", value1, value2, "cmdKey");
            return (Criteria) this;
        }

        public Criteria andCmdNameIsNull() {
            addCriterion("`cmd_name` is null");
            return (Criteria) this;
        }

        public Criteria andCmdNameIsNotNull() {
            addCriterion("`cmd_name` is not null");
            return (Criteria) this;
        }

        public Criteria andCmdNameEqualTo(String value) {
            addCriterion("`cmd_name` =", value, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameNotEqualTo(String value) {
            addCriterion("`cmd_name` <>", value, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameGreaterThan(String value) {
            addCriterion("`cmd_name` >", value, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameGreaterThanOrEqualTo(String value) {
            addCriterion("`cmd_name` >=", value, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameLessThan(String value) {
            addCriterion("`cmd_name` <", value, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameLessThanOrEqualTo(String value) {
            addCriterion("`cmd_name` <=", value, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameLike(String value) {
            addCriterion("`cmd_name` like", value, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameNotLike(String value) {
            addCriterion("`cmd_name` not like", value, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameIn(List<String> values) {
            addCriterion("`cmd_name` in", values, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameNotIn(List<String> values) {
            addCriterion("`cmd_name` not in", values, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameBetween(String value1, String value2) {
            addCriterion("`cmd_name` between", value1, value2, "cmdName");
            return (Criteria) this;
        }

        public Criteria andCmdNameNotBetween(String value1, String value2) {
            addCriterion("`cmd_name` not between", value1, value2, "cmdName");
            return (Criteria) this;
        }

        public Criteria andMsgIsNull() {
            addCriterion("`msg` is null");
            return (Criteria) this;
        }

        public Criteria andMsgIsNotNull() {
            addCriterion("`msg` is not null");
            return (Criteria) this;
        }

        public Criteria andMsgEqualTo(String value) {
            addCriterion("`msg` =", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotEqualTo(String value) {
            addCriterion("`msg` <>", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThan(String value) {
            addCriterion("`msg` >", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgGreaterThanOrEqualTo(String value) {
            addCriterion("`msg` >=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThan(String value) {
            addCriterion("`msg` <", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLessThanOrEqualTo(String value) {
            addCriterion("`msg` <=", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgLike(String value) {
            addCriterion("`msg` like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotLike(String value) {
            addCriterion("`msg` not like", value, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgIn(List<String> values) {
            addCriterion("`msg` in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotIn(List<String> values) {
            addCriterion("`msg` not in", values, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgBetween(String value1, String value2) {
            addCriterion("`msg` between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andMsgNotBetween(String value1, String value2) {
            addCriterion("`msg` not between", value1, value2, "msg");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("`comments` is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("`comments` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("`comments` =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("`comments` <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("`comments` >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("`comments` >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("`comments` <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("`comments` <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("`comments` like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("`comments` not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("`comments` in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("`comments` not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("`comments` between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("`comments` not between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chat_msg_manual
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_chat_msg_manual
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}