package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentInfoExample {
    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public AgentInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_agent_info
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_info
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAgentCdIsNull() {
            addCriterion("`agent_cd` is null");
            return (Criteria) this;
        }

        public Criteria andAgentCdIsNotNull() {
            addCriterion("`agent_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCdEqualTo(String value) {
            addCriterion("`agent_cd` =", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotEqualTo(String value) {
            addCriterion("`agent_cd` <>", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThan(String value) {
            addCriterion("`agent_cd` >", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_cd` >=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThan(String value) {
            addCriterion("`agent_cd` <", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThanOrEqualTo(String value) {
            addCriterion("`agent_cd` <=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLike(String value) {
            addCriterion("`agent_cd` like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotLike(String value) {
            addCriterion("`agent_cd` not like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdIn(List<String> values) {
            addCriterion("`agent_cd` in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotIn(List<String> values) {
            addCriterion("`agent_cd` not in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdBetween(String value1, String value2) {
            addCriterion("`agent_cd` between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotBetween(String value1, String value2) {
            addCriterion("`agent_cd` not between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentTypeIsNull() {
            addCriterion("`agent_type` is null");
            return (Criteria) this;
        }

        public Criteria andAgentTypeIsNotNull() {
            addCriterion("`agent_type` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentTypeEqualTo(String value) {
            addCriterion("`agent_type` =", value, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeNotEqualTo(String value) {
            addCriterion("`agent_type` <>", value, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeGreaterThan(String value) {
            addCriterion("`agent_type` >", value, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_type` >=", value, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeLessThan(String value) {
            addCriterion("`agent_type` <", value, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeLessThanOrEqualTo(String value) {
            addCriterion("`agent_type` <=", value, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeLike(String value) {
            addCriterion("`agent_type` like", value, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeNotLike(String value) {
            addCriterion("`agent_type` not like", value, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeIn(List<String> values) {
            addCriterion("`agent_type` in", values, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeNotIn(List<String> values) {
            addCriterion("`agent_type` not in", values, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeBetween(String value1, String value2) {
            addCriterion("`agent_type` between", value1, value2, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentTypeNotBetween(String value1, String value2) {
            addCriterion("`agent_type` not between", value1, value2, "agentType");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmIsNull() {
            addCriterion("`agent_cn_nm` is null");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmIsNotNull() {
            addCriterion("`agent_cn_nm` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmEqualTo(String value) {
            addCriterion("`agent_cn_nm` =", value, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmNotEqualTo(String value) {
            addCriterion("`agent_cn_nm` <>", value, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmGreaterThan(String value) {
            addCriterion("`agent_cn_nm` >", value, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_cn_nm` >=", value, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmLessThan(String value) {
            addCriterion("`agent_cn_nm` <", value, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmLessThanOrEqualTo(String value) {
            addCriterion("`agent_cn_nm` <=", value, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmLike(String value) {
            addCriterion("`agent_cn_nm` like", value, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmNotLike(String value) {
            addCriterion("`agent_cn_nm` not like", value, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmIn(List<String> values) {
            addCriterion("`agent_cn_nm` in", values, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmNotIn(List<String> values) {
            addCriterion("`agent_cn_nm` not in", values, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmBetween(String value1, String value2) {
            addCriterion("`agent_cn_nm` between", value1, value2, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnNmNotBetween(String value1, String value2) {
            addCriterion("`agent_cn_nm` not between", value1, value2, "agentCnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmIsNull() {
            addCriterion("`agent_en_nm` is null");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmIsNotNull() {
            addCriterion("`agent_en_nm` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmEqualTo(String value) {
            addCriterion("`agent_en_nm` =", value, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmNotEqualTo(String value) {
            addCriterion("`agent_en_nm` <>", value, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmGreaterThan(String value) {
            addCriterion("`agent_en_nm` >", value, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_en_nm` >=", value, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmLessThan(String value) {
            addCriterion("`agent_en_nm` <", value, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmLessThanOrEqualTo(String value) {
            addCriterion("`agent_en_nm` <=", value, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmLike(String value) {
            addCriterion("`agent_en_nm` like", value, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmNotLike(String value) {
            addCriterion("`agent_en_nm` not like", value, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmIn(List<String> values) {
            addCriterion("`agent_en_nm` in", values, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmNotIn(List<String> values) {
            addCriterion("`agent_en_nm` not in", values, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmBetween(String value1, String value2) {
            addCriterion("`agent_en_nm` between", value1, value2, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentEnNmNotBetween(String value1, String value2) {
            addCriterion("`agent_en_nm` not between", value1, value2, "agentEnNm");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrIsNull() {
            addCriterion("`agent_cn_abbr` is null");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrIsNotNull() {
            addCriterion("`agent_cn_abbr` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrEqualTo(String value) {
            addCriterion("`agent_cn_abbr` =", value, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrNotEqualTo(String value) {
            addCriterion("`agent_cn_abbr` <>", value, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrGreaterThan(String value) {
            addCriterion("`agent_cn_abbr` >", value, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_cn_abbr` >=", value, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrLessThan(String value) {
            addCriterion("`agent_cn_abbr` <", value, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrLessThanOrEqualTo(String value) {
            addCriterion("`agent_cn_abbr` <=", value, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrLike(String value) {
            addCriterion("`agent_cn_abbr` like", value, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrNotLike(String value) {
            addCriterion("`agent_cn_abbr` not like", value, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrIn(List<String> values) {
            addCriterion("`agent_cn_abbr` in", values, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrNotIn(List<String> values) {
            addCriterion("`agent_cn_abbr` not in", values, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrBetween(String value1, String value2) {
            addCriterion("`agent_cn_abbr` between", value1, value2, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentCnAbbrNotBetween(String value1, String value2) {
            addCriterion("`agent_cn_abbr` not between", value1, value2, "agentCnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrIsNull() {
            addCriterion("`agent_en_abbr` is null");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrIsNotNull() {
            addCriterion("`agent_en_abbr` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrEqualTo(String value) {
            addCriterion("`agent_en_abbr` =", value, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrNotEqualTo(String value) {
            addCriterion("`agent_en_abbr` <>", value, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrGreaterThan(String value) {
            addCriterion("`agent_en_abbr` >", value, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_en_abbr` >=", value, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrLessThan(String value) {
            addCriterion("`agent_en_abbr` <", value, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrLessThanOrEqualTo(String value) {
            addCriterion("`agent_en_abbr` <=", value, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrLike(String value) {
            addCriterion("`agent_en_abbr` like", value, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrNotLike(String value) {
            addCriterion("`agent_en_abbr` not like", value, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrIn(List<String> values) {
            addCriterion("`agent_en_abbr` in", values, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrNotIn(List<String> values) {
            addCriterion("`agent_en_abbr` not in", values, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrBetween(String value1, String value2) {
            addCriterion("`agent_en_abbr` between", value1, value2, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAgentEnAbbrNotBetween(String value1, String value2) {
            addCriterion("`agent_en_abbr` not between", value1, value2, "agentEnAbbr");
            return (Criteria) this;
        }

        public Criteria andAreaCdIsNull() {
            addCriterion("`area_cd` is null");
            return (Criteria) this;
        }

        public Criteria andAreaCdIsNotNull() {
            addCriterion("`area_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andAreaCdEqualTo(String value) {
            addCriterion("`area_cd` =", value, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdNotEqualTo(String value) {
            addCriterion("`area_cd` <>", value, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdGreaterThan(String value) {
            addCriterion("`area_cd` >", value, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdGreaterThanOrEqualTo(String value) {
            addCriterion("`area_cd` >=", value, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdLessThan(String value) {
            addCriterion("`area_cd` <", value, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdLessThanOrEqualTo(String value) {
            addCriterion("`area_cd` <=", value, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdLike(String value) {
            addCriterion("`area_cd` like", value, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdNotLike(String value) {
            addCriterion("`area_cd` not like", value, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdIn(List<String> values) {
            addCriterion("`area_cd` in", values, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdNotIn(List<String> values) {
            addCriterion("`area_cd` not in", values, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdBetween(String value1, String value2) {
            addCriterion("`area_cd` between", value1, value2, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAreaCdNotBetween(String value1, String value2) {
            addCriterion("`area_cd` not between", value1, value2, "areaCd");
            return (Criteria) this;
        }

        public Criteria andAgentAddrIsNull() {
            addCriterion("`agent_addr` is null");
            return (Criteria) this;
        }

        public Criteria andAgentAddrIsNotNull() {
            addCriterion("`agent_addr` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentAddrEqualTo(String value) {
            addCriterion("`agent_addr` =", value, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrNotEqualTo(String value) {
            addCriterion("`agent_addr` <>", value, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrGreaterThan(String value) {
            addCriterion("`agent_addr` >", value, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_addr` >=", value, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrLessThan(String value) {
            addCriterion("`agent_addr` <", value, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrLessThanOrEqualTo(String value) {
            addCriterion("`agent_addr` <=", value, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrLike(String value) {
            addCriterion("`agent_addr` like", value, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrNotLike(String value) {
            addCriterion("`agent_addr` not like", value, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrIn(List<String> values) {
            addCriterion("`agent_addr` in", values, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrNotIn(List<String> values) {
            addCriterion("`agent_addr` not in", values, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrBetween(String value1, String value2) {
            addCriterion("`agent_addr` between", value1, value2, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andAgentAddrNotBetween(String value1, String value2) {
            addCriterion("`agent_addr` not between", value1, value2, "agentAddr");
            return (Criteria) this;
        }

        public Criteria andContactPerson1IsNull() {
            addCriterion("`contact_person1` is null");
            return (Criteria) this;
        }

        public Criteria andContactPerson1IsNotNull() {
            addCriterion("`contact_person1` is not null");
            return (Criteria) this;
        }

        public Criteria andContactPerson1EqualTo(String value) {
            addCriterion("`contact_person1` =", value, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1NotEqualTo(String value) {
            addCriterion("`contact_person1` <>", value, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1GreaterThan(String value) {
            addCriterion("`contact_person1` >", value, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1GreaterThanOrEqualTo(String value) {
            addCriterion("`contact_person1` >=", value, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1LessThan(String value) {
            addCriterion("`contact_person1` <", value, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1LessThanOrEqualTo(String value) {
            addCriterion("`contact_person1` <=", value, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1Like(String value) {
            addCriterion("`contact_person1` like", value, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1NotLike(String value) {
            addCriterion("`contact_person1` not like", value, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1In(List<String> values) {
            addCriterion("`contact_person1` in", values, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1NotIn(List<String> values) {
            addCriterion("`contact_person1` not in", values, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1Between(String value1, String value2) {
            addCriterion("`contact_person1` between", value1, value2, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPerson1NotBetween(String value1, String value2) {
            addCriterion("`contact_person1` not between", value1, value2, "contactPerson1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1IsNull() {
            addCriterion("`contact_phone1` is null");
            return (Criteria) this;
        }

        public Criteria andContactPhone1IsNotNull() {
            addCriterion("`contact_phone1` is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhone1EqualTo(String value) {
            addCriterion("`contact_phone1` =", value, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1NotEqualTo(String value) {
            addCriterion("`contact_phone1` <>", value, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1GreaterThan(String value) {
            addCriterion("`contact_phone1` >", value, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1GreaterThanOrEqualTo(String value) {
            addCriterion("`contact_phone1` >=", value, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1LessThan(String value) {
            addCriterion("`contact_phone1` <", value, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1LessThanOrEqualTo(String value) {
            addCriterion("`contact_phone1` <=", value, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1Like(String value) {
            addCriterion("`contact_phone1` like", value, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1NotLike(String value) {
            addCriterion("`contact_phone1` not like", value, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1In(List<String> values) {
            addCriterion("`contact_phone1` in", values, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1NotIn(List<String> values) {
            addCriterion("`contact_phone1` not in", values, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1Between(String value1, String value2) {
            addCriterion("`contact_phone1` between", value1, value2, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactPhone1NotBetween(String value1, String value2) {
            addCriterion("`contact_phone1` not between", value1, value2, "contactPhone1");
            return (Criteria) this;
        }

        public Criteria andContactMail1IsNull() {
            addCriterion("`contact_mail1` is null");
            return (Criteria) this;
        }

        public Criteria andContactMail1IsNotNull() {
            addCriterion("`contact_mail1` is not null");
            return (Criteria) this;
        }

        public Criteria andContactMail1EqualTo(String value) {
            addCriterion("`contact_mail1` =", value, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1NotEqualTo(String value) {
            addCriterion("`contact_mail1` <>", value, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1GreaterThan(String value) {
            addCriterion("`contact_mail1` >", value, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1GreaterThanOrEqualTo(String value) {
            addCriterion("`contact_mail1` >=", value, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1LessThan(String value) {
            addCriterion("`contact_mail1` <", value, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1LessThanOrEqualTo(String value) {
            addCriterion("`contact_mail1` <=", value, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1Like(String value) {
            addCriterion("`contact_mail1` like", value, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1NotLike(String value) {
            addCriterion("`contact_mail1` not like", value, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1In(List<String> values) {
            addCriterion("`contact_mail1` in", values, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1NotIn(List<String> values) {
            addCriterion("`contact_mail1` not in", values, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1Between(String value1, String value2) {
            addCriterion("`contact_mail1` between", value1, value2, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactMail1NotBetween(String value1, String value2) {
            addCriterion("`contact_mail1` not between", value1, value2, "contactMail1");
            return (Criteria) this;
        }

        public Criteria andContactPerson2IsNull() {
            addCriterion("`contact_person2` is null");
            return (Criteria) this;
        }

        public Criteria andContactPerson2IsNotNull() {
            addCriterion("`contact_person2` is not null");
            return (Criteria) this;
        }

        public Criteria andContactPerson2EqualTo(String value) {
            addCriterion("`contact_person2` =", value, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2NotEqualTo(String value) {
            addCriterion("`contact_person2` <>", value, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2GreaterThan(String value) {
            addCriterion("`contact_person2` >", value, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2GreaterThanOrEqualTo(String value) {
            addCriterion("`contact_person2` >=", value, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2LessThan(String value) {
            addCriterion("`contact_person2` <", value, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2LessThanOrEqualTo(String value) {
            addCriterion("`contact_person2` <=", value, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2Like(String value) {
            addCriterion("`contact_person2` like", value, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2NotLike(String value) {
            addCriterion("`contact_person2` not like", value, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2In(List<String> values) {
            addCriterion("`contact_person2` in", values, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2NotIn(List<String> values) {
            addCriterion("`contact_person2` not in", values, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2Between(String value1, String value2) {
            addCriterion("`contact_person2` between", value1, value2, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPerson2NotBetween(String value1, String value2) {
            addCriterion("`contact_person2` not between", value1, value2, "contactPerson2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2IsNull() {
            addCriterion("`contact_phone2` is null");
            return (Criteria) this;
        }

        public Criteria andContactPhone2IsNotNull() {
            addCriterion("`contact_phone2` is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhone2EqualTo(String value) {
            addCriterion("`contact_phone2` =", value, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2NotEqualTo(String value) {
            addCriterion("`contact_phone2` <>", value, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2GreaterThan(String value) {
            addCriterion("`contact_phone2` >", value, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2GreaterThanOrEqualTo(String value) {
            addCriterion("`contact_phone2` >=", value, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2LessThan(String value) {
            addCriterion("`contact_phone2` <", value, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2LessThanOrEqualTo(String value) {
            addCriterion("`contact_phone2` <=", value, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2Like(String value) {
            addCriterion("`contact_phone2` like", value, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2NotLike(String value) {
            addCriterion("`contact_phone2` not like", value, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2In(List<String> values) {
            addCriterion("`contact_phone2` in", values, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2NotIn(List<String> values) {
            addCriterion("`contact_phone2` not in", values, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2Between(String value1, String value2) {
            addCriterion("`contact_phone2` between", value1, value2, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactPhone2NotBetween(String value1, String value2) {
            addCriterion("`contact_phone2` not between", value1, value2, "contactPhone2");
            return (Criteria) this;
        }

        public Criteria andContactMail2IsNull() {
            addCriterion("`contact_mail2` is null");
            return (Criteria) this;
        }

        public Criteria andContactMail2IsNotNull() {
            addCriterion("`contact_mail2` is not null");
            return (Criteria) this;
        }

        public Criteria andContactMail2EqualTo(String value) {
            addCriterion("`contact_mail2` =", value, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2NotEqualTo(String value) {
            addCriterion("`contact_mail2` <>", value, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2GreaterThan(String value) {
            addCriterion("`contact_mail2` >", value, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2GreaterThanOrEqualTo(String value) {
            addCriterion("`contact_mail2` >=", value, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2LessThan(String value) {
            addCriterion("`contact_mail2` <", value, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2LessThanOrEqualTo(String value) {
            addCriterion("`contact_mail2` <=", value, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2Like(String value) {
            addCriterion("`contact_mail2` like", value, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2NotLike(String value) {
            addCriterion("`contact_mail2` not like", value, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2In(List<String> values) {
            addCriterion("`contact_mail2` in", values, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2NotIn(List<String> values) {
            addCriterion("`contact_mail2` not in", values, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2Between(String value1, String value2) {
            addCriterion("`contact_mail2` between", value1, value2, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andContactMail2NotBetween(String value1, String value2) {
            addCriterion("`contact_mail2` not between", value1, value2, "contactMail2");
            return (Criteria) this;
        }

        public Criteria andZipCdIsNull() {
            addCriterion("`zip_cd` is null");
            return (Criteria) this;
        }

        public Criteria andZipCdIsNotNull() {
            addCriterion("`zip_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andZipCdEqualTo(String value) {
            addCriterion("`zip_cd` =", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdNotEqualTo(String value) {
            addCriterion("`zip_cd` <>", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdGreaterThan(String value) {
            addCriterion("`zip_cd` >", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdGreaterThanOrEqualTo(String value) {
            addCriterion("`zip_cd` >=", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdLessThan(String value) {
            addCriterion("`zip_cd` <", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdLessThanOrEqualTo(String value) {
            addCriterion("`zip_cd` <=", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdLike(String value) {
            addCriterion("`zip_cd` like", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdNotLike(String value) {
            addCriterion("`zip_cd` not like", value, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdIn(List<String> values) {
            addCriterion("`zip_cd` in", values, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdNotIn(List<String> values) {
            addCriterion("`zip_cd` not in", values, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdBetween(String value1, String value2) {
            addCriterion("`zip_cd` between", value1, value2, "zipCd");
            return (Criteria) this;
        }

        public Criteria andZipCdNotBetween(String value1, String value2) {
            addCriterion("`zip_cd` not between", value1, value2, "zipCd");
            return (Criteria) this;
        }

        public Criteria andFaxIsNull() {
            addCriterion("`fax` is null");
            return (Criteria) this;
        }

        public Criteria andFaxIsNotNull() {
            addCriterion("`fax` is not null");
            return (Criteria) this;
        }

        public Criteria andFaxEqualTo(String value) {
            addCriterion("`fax` =", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotEqualTo(String value) {
            addCriterion("`fax` <>", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThan(String value) {
            addCriterion("`fax` >", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxGreaterThanOrEqualTo(String value) {
            addCriterion("`fax` >=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThan(String value) {
            addCriterion("`fax` <", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLessThanOrEqualTo(String value) {
            addCriterion("`fax` <=", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxLike(String value) {
            addCriterion("`fax` like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotLike(String value) {
            addCriterion("`fax` not like", value, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxIn(List<String> values) {
            addCriterion("`fax` in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotIn(List<String> values) {
            addCriterion("`fax` not in", values, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxBetween(String value1, String value2) {
            addCriterion("`fax` between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andFaxNotBetween(String value1, String value2) {
            addCriterion("`fax` not between", value1, value2, "fax");
            return (Criteria) this;
        }

        public Criteria andStCdIsNull() {
            addCriterion("`st_cd` is null");
            return (Criteria) this;
        }

        public Criteria andStCdIsNotNull() {
            addCriterion("`st_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andStCdEqualTo(String value) {
            addCriterion("`st_cd` =", value, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdNotEqualTo(String value) {
            addCriterion("`st_cd` <>", value, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdGreaterThan(String value) {
            addCriterion("`st_cd` >", value, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdGreaterThanOrEqualTo(String value) {
            addCriterion("`st_cd` >=", value, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdLessThan(String value) {
            addCriterion("`st_cd` <", value, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdLessThanOrEqualTo(String value) {
            addCriterion("`st_cd` <=", value, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdLike(String value) {
            addCriterion("`st_cd` like", value, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdNotLike(String value) {
            addCriterion("`st_cd` not like", value, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdIn(List<String> values) {
            addCriterion("`st_cd` in", values, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdNotIn(List<String> values) {
            addCriterion("`st_cd` not in", values, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdBetween(String value1, String value2) {
            addCriterion("`st_cd` between", value1, value2, "stCd");
            return (Criteria) this;
        }

        public Criteria andStCdNotBetween(String value1, String value2) {
            addCriterion("`st_cd` not between", value1, value2, "stCd");
            return (Criteria) this;
        }

        public Criteria andAgentStIsNull() {
            addCriterion("`agent_st` is null");
            return (Criteria) this;
        }

        public Criteria andAgentStIsNotNull() {
            addCriterion("`agent_st` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentStEqualTo(String value) {
            addCriterion("`agent_st` =", value, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStNotEqualTo(String value) {
            addCriterion("`agent_st` <>", value, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStGreaterThan(String value) {
            addCriterion("`agent_st` >", value, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_st` >=", value, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStLessThan(String value) {
            addCriterion("`agent_st` <", value, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStLessThanOrEqualTo(String value) {
            addCriterion("`agent_st` <=", value, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStLike(String value) {
            addCriterion("`agent_st` like", value, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStNotLike(String value) {
            addCriterion("`agent_st` not like", value, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStIn(List<String> values) {
            addCriterion("`agent_st` in", values, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStNotIn(List<String> values) {
            addCriterion("`agent_st` not in", values, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStBetween(String value1, String value2) {
            addCriterion("`agent_st` between", value1, value2, "agentSt");
            return (Criteria) this;
        }

        public Criteria andAgentStNotBetween(String value1, String value2) {
            addCriterion("`agent_st` not between", value1, value2, "agentSt");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIsNull() {
            addCriterion("`settle_period` is null");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIsNotNull() {
            addCriterion("`settle_period` is not null");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodEqualTo(String value) {
            addCriterion("`settle_period` =", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotEqualTo(String value) {
            addCriterion("`settle_period` <>", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodGreaterThan(String value) {
            addCriterion("`settle_period` >", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodGreaterThanOrEqualTo(String value) {
            addCriterion("`settle_period` >=", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLessThan(String value) {
            addCriterion("`settle_period` <", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLessThanOrEqualTo(String value) {
            addCriterion("`settle_period` <=", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodLike(String value) {
            addCriterion("`settle_period` like", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotLike(String value) {
            addCriterion("`settle_period` not like", value, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodIn(List<String> values) {
            addCriterion("`settle_period` in", values, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotIn(List<String> values) {
            addCriterion("`settle_period` not in", values, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodBetween(String value1, String value2) {
            addCriterion("`settle_period` between", value1, value2, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodNotBetween(String value1, String value2) {
            addCriterion("`settle_period` not between", value1, value2, "settlePeriod");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("`comment` is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("`comment` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("`comment` =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("`comment` <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("`comment` >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("`comment` >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("`comment` <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("`comment` <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("`comment` like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("`comment` not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("`comment` in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("`comment` not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("`comment` between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("`comment` not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNull() {
            addCriterion("`last_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNotNull() {
            addCriterion("`last_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdEqualTo(String value) {
            addCriterion("`last_oper_id` =", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotEqualTo(String value) {
            addCriterion("`last_oper_id` <>", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThan(String value) {
            addCriterion("`last_oper_id` >", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` >=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThan(String value) {
            addCriterion("`last_oper_id` <", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` <=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLike(String value) {
            addCriterion("`last_oper_id` like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotLike(String value) {
            addCriterion("`last_oper_id` not like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIn(List<String> values) {
            addCriterion("`last_oper_id` in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotIn(List<String> values) {
            addCriterion("`last_oper_id` not in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdBetween(String value1, String value2) {
            addCriterion("`last_oper_id` between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotBetween(String value1, String value2) {
            addCriterion("`last_oper_id` not between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andDepositIsNull() {
            addCriterion("`deposit` is null");
            return (Criteria) this;
        }

        public Criteria andDepositIsNotNull() {
            addCriterion("`deposit` is not null");
            return (Criteria) this;
        }

        public Criteria andDepositEqualTo(String value) {
            addCriterion("`deposit` =", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotEqualTo(String value) {
            addCriterion("`deposit` <>", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThan(String value) {
            addCriterion("`deposit` >", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositGreaterThanOrEqualTo(String value) {
            addCriterion("`deposit` >=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThan(String value) {
            addCriterion("`deposit` <", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLessThanOrEqualTo(String value) {
            addCriterion("`deposit` <=", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositLike(String value) {
            addCriterion("`deposit` like", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotLike(String value) {
            addCriterion("`deposit` not like", value, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositIn(List<String> values) {
            addCriterion("`deposit` in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotIn(List<String> values) {
            addCriterion("`deposit` not in", values, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositBetween(String value1, String value2) {
            addCriterion("`deposit` between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andDepositNotBetween(String value1, String value2) {
            addCriterion("`deposit` not between", value1, value2, "deposit");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("`password` is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("`password` is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("`password` =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("`password` <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("`password` >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("`password` >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("`password` <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("`password` <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("`password` like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("`password` not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("`password` in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("`password` not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("`password` between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("`password` not between", value1, value2, "password");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_info
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_agent_info
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}