package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_vacc_info

 *
 * @mbg.generated
 */
public class VaccInfoKey implements Serializable {
    /**
     * 分类目录
     * Database column : tbl_vacc_info.catalog
     *
     * @mbg.generated
     */
    private String catalog;

    /**
     * 主帐户号
     * Database column : tbl_vacc_info.acc_id
     *
     * @mbg.generated
     */
    private String accId;

    /**
     * 子帐户号(系统保留：0000=主帐户,0001=主冻结帐户,0002=T1冻结帐户...，其他自定义请从1000开始编号)
     * Database column : tbl_vacc_info.acc_sub_id
     *
     * @mbg.generated
     */
    private String accSubId;

    /**
     * Database table : tbl_vacc_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_vacc_info
     *
     * @mbg.generated
     */
    public VaccInfoKey(String catalog, String accId, String accSubId) {
        this.catalog = catalog;
        this.accId = accId;
        this.accSubId = accSubId;
    }

    /**
     * Database table : tbl_vacc_info
     *
     * @mbg.generated
     */
    public VaccInfoKey() {
        super();
    }

    /**
     * 分类目录
     * @return catalog 分类目录
     *
     * @mbg.generated
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * 分类目录
     * @param catalog 分类目录
     *
     * @mbg.generated
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }

    /**
     * 主帐户号
     * @return acc_id 主帐户号
     *
     * @mbg.generated
     */
    public String getAccId() {
        return accId;
    }

    /**
     * 主帐户号
     * @param accId 主帐户号
     *
     * @mbg.generated
     */
    public void setAccId(String accId) {
        this.accId = accId;
    }

    /**
     * 子帐户号(系统保留：0000=主帐户,0001=主冻结帐户,0002=T1冻结帐户...，其他自定义请从1000开始编号)
     * @return acc_sub_id 子帐户号(系统保留：0000=主帐户,0001=主冻结帐户,0002=T1冻结帐户...，其他自定义请从1000开始编号)
     *
     * @mbg.generated
     */
    public String getAccSubId() {
        return accSubId;
    }

    /**
     * 子帐户号(系统保留：0000=主帐户,0001=主冻结帐户,0002=T1冻结帐户...，其他自定义请从1000开始编号)
     * @param accSubId 子帐户号(系统保留：0000=主帐户,0001=主冻结帐户,0002=T1冻结帐户...，其他自定义请从1000开始编号)
     *
     * @mbg.generated
     */
    public void setAccSubId(String accSubId) {
        this.accSubId = accSubId;
    }

    /**
     * Database table : tbl_vacc_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VaccInfoKey other = (VaccInfoKey) that;
        return (this.getCatalog() == null ? other.getCatalog() == null : this.getCatalog().equals(other.getCatalog()))
            && (this.getAccId() == null ? other.getAccId() == null : this.getAccId().equals(other.getAccId()))
            && (this.getAccSubId() == null ? other.getAccSubId() == null : this.getAccSubId().equals(other.getAccSubId()));
    }

    /**
     * Database table : tbl_vacc_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCatalog() == null) ? 0 : getCatalog().hashCode());
        result = prime * result + ((getAccId() == null) ? 0 : getAccId().hashCode());
        result = prime * result + ((getAccSubId() == null) ? 0 : getAccSubId().hashCode());
        return result;
    }

    /**
     * Database table : tbl_vacc_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", catalog=").append(catalog);
        sb.append(", accId=").append(accId);
        sb.append(", accSubId=").append(accSubId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(VaccInfoKey source) {
        this.catalog=source.catalog;
        this.accId=source.accId;
        this.accSubId=source.accSubId;
    }
}