package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AgentMchntTxnExample {
    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public AgentMchntTxnExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : view_agent_mchnt_txn_01
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_agent_mchnt_txn_01
     * @author user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransSeqIdIsNull() {
            addCriterion("`trans_seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIsNotNull() {
            addCriterion("`trans_seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdEqualTo(String value) {
            addCriterion("`trans_seq_id` =", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotEqualTo(String value) {
            addCriterion("`trans_seq_id` <>", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdGreaterThan(String value) {
            addCriterion("`trans_seq_id` >", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_seq_id` >=", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLessThan(String value) {
            addCriterion("`trans_seq_id` <", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLessThanOrEqualTo(String value) {
            addCriterion("`trans_seq_id` <=", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLike(String value) {
            addCriterion("`trans_seq_id` like", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotLike(String value) {
            addCriterion("`trans_seq_id` not like", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIn(List<String> values) {
            addCriterion("`trans_seq_id` in", values, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotIn(List<String> values) {
            addCriterion("`trans_seq_id` not in", values, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdBetween(String value1, String value2) {
            addCriterion("`trans_seq_id` between", value1, value2, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotBetween(String value1, String value2) {
            addCriterion("`trans_seq_id` not between", value1, value2, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNull() {
            addCriterion("`order_state` is null");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNotNull() {
            addCriterion("`order_state` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStateEqualTo(String value) {
            addCriterion("`order_state` =", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotEqualTo(String value) {
            addCriterion("`order_state` <>", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThan(String value) {
            addCriterion("`order_state` >", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThanOrEqualTo(String value) {
            addCriterion("`order_state` >=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThan(String value) {
            addCriterion("`order_state` <", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThanOrEqualTo(String value) {
            addCriterion("`order_state` <=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLike(String value) {
            addCriterion("`order_state` like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotLike(String value) {
            addCriterion("`order_state` not like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateIn(List<String> values) {
            addCriterion("`order_state` in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotIn(List<String> values) {
            addCriterion("`order_state` not in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateBetween(String value1, String value2) {
            addCriterion("`order_state` between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotBetween(String value1, String value2) {
            addCriterion("`order_state` not between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrIsNull() {
            addCriterion("`mchnt_cn_abbr` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrIsNotNull() {
            addCriterion("`mchnt_cn_abbr` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrEqualTo(String value) {
            addCriterion("`mchnt_cn_abbr` =", value, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrNotEqualTo(String value) {
            addCriterion("`mchnt_cn_abbr` <>", value, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrGreaterThan(String value) {
            addCriterion("`mchnt_cn_abbr` >", value, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cn_abbr` >=", value, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrLessThan(String value) {
            addCriterion("`mchnt_cn_abbr` <", value, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cn_abbr` <=", value, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrLike(String value) {
            addCriterion("`mchnt_cn_abbr` like", value, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrNotLike(String value) {
            addCriterion("`mchnt_cn_abbr` not like", value, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrIn(List<String> values) {
            addCriterion("`mchnt_cn_abbr` in", values, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrNotIn(List<String> values) {
            addCriterion("`mchnt_cn_abbr` not in", values, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrBetween(String value1, String value2) {
            addCriterion("`mchnt_cn_abbr` between", value1, value2, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andMchntCnAbbrNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cn_abbr` not between", value1, value2, "mchntCnAbbr");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("`order_id` is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("`order_id` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("`order_id` =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("`order_id` <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("`order_id` >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("`order_id` >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("`order_id` <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("`order_id` <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("`order_id` like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("`order_id` not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("`order_id` in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("`order_id` not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("`order_id` between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("`order_id` not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIsNull() {
            addCriterion("`int_trans_cd` is null");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIsNotNull() {
            addCriterion("`int_trans_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andIntTransCdEqualTo(String value) {
            addCriterion("`int_trans_cd` =", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotEqualTo(String value) {
            addCriterion("`int_trans_cd` <>", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdGreaterThan(String value) {
            addCriterion("`int_trans_cd` >", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdGreaterThanOrEqualTo(String value) {
            addCriterion("`int_trans_cd` >=", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLessThan(String value) {
            addCriterion("`int_trans_cd` <", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLessThanOrEqualTo(String value) {
            addCriterion("`int_trans_cd` <=", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLike(String value) {
            addCriterion("`int_trans_cd` like", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotLike(String value) {
            addCriterion("`int_trans_cd` not like", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIn(List<String> values) {
            addCriterion("`int_trans_cd` in", values, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotIn(List<String> values) {
            addCriterion("`int_trans_cd` not in", values, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdBetween(String value1, String value2) {
            addCriterion("`int_trans_cd` between", value1, value2, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotBetween(String value1, String value2) {
            addCriterion("`int_trans_cd` not between", value1, value2, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNull() {
            addCriterion("`trans_at` is null");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNotNull() {
            addCriterion("`trans_at` is not null");
            return (Criteria) this;
        }

        public Criteria andTransAtEqualTo(Long value) {
            addCriterion("`trans_at` =", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotEqualTo(Long value) {
            addCriterion("`trans_at` <>", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThan(Long value) {
            addCriterion("`trans_at` >", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`trans_at` >=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThan(Long value) {
            addCriterion("`trans_at` <", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThanOrEqualTo(Long value) {
            addCriterion("`trans_at` <=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtIn(List<Long> values) {
            addCriterion("`trans_at` in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotIn(List<Long> values) {
            addCriterion("`trans_at` not in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtBetween(Long value1, Long value2) {
            addCriterion("`trans_at` between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotBetween(Long value1, Long value2) {
            addCriterion("`trans_at` not between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransFeeIsNull() {
            addCriterion("`trans_fee` is null");
            return (Criteria) this;
        }

        public Criteria andTransFeeIsNotNull() {
            addCriterion("`trans_fee` is not null");
            return (Criteria) this;
        }

        public Criteria andTransFeeEqualTo(Long value) {
            addCriterion("`trans_fee` =", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeNotEqualTo(Long value) {
            addCriterion("`trans_fee` <>", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeGreaterThan(Long value) {
            addCriterion("`trans_fee` >", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeGreaterThanOrEqualTo(Long value) {
            addCriterion("`trans_fee` >=", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeLessThan(Long value) {
            addCriterion("`trans_fee` <", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeLessThanOrEqualTo(Long value) {
            addCriterion("`trans_fee` <=", value, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeIn(List<Long> values) {
            addCriterion("`trans_fee` in", values, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeNotIn(List<Long> values) {
            addCriterion("`trans_fee` not in", values, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeBetween(Long value1, Long value2) {
            addCriterion("`trans_fee` between", value1, value2, "transFee");
            return (Criteria) this;
        }

        public Criteria andTransFeeNotBetween(Long value1, Long value2) {
            addCriterion("`trans_fee` not between", value1, value2, "transFee");
            return (Criteria) this;
        }

        public Criteria andTxnStateIsNull() {
            addCriterion("`txn_state` is null");
            return (Criteria) this;
        }

        public Criteria andTxnStateIsNotNull() {
            addCriterion("`txn_state` is not null");
            return (Criteria) this;
        }

        public Criteria andTxnStateEqualTo(String value) {
            addCriterion("`txn_state` =", value, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateNotEqualTo(String value) {
            addCriterion("`txn_state` <>", value, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateGreaterThan(String value) {
            addCriterion("`txn_state` >", value, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateGreaterThanOrEqualTo(String value) {
            addCriterion("`txn_state` >=", value, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateLessThan(String value) {
            addCriterion("`txn_state` <", value, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateLessThanOrEqualTo(String value) {
            addCriterion("`txn_state` <=", value, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateLike(String value) {
            addCriterion("`txn_state` like", value, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateNotLike(String value) {
            addCriterion("`txn_state` not like", value, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateIn(List<String> values) {
            addCriterion("`txn_state` in", values, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateNotIn(List<String> values) {
            addCriterion("`txn_state` not in", values, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateBetween(String value1, String value2) {
            addCriterion("`txn_state` between", value1, value2, "txnState");
            return (Criteria) this;
        }

        public Criteria andTxnStateNotBetween(String value1, String value2) {
            addCriterion("`txn_state` not between", value1, value2, "txnState");
            return (Criteria) this;
        }

        public Criteria andAccNameIsNull() {
            addCriterion("`acc_name` is null");
            return (Criteria) this;
        }

        public Criteria andAccNameIsNotNull() {
            addCriterion("`acc_name` is not null");
            return (Criteria) this;
        }

        public Criteria andAccNameEqualTo(String value) {
            addCriterion("`acc_name` =", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameNotEqualTo(String value) {
            addCriterion("`acc_name` <>", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameGreaterThan(String value) {
            addCriterion("`acc_name` >", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameGreaterThanOrEqualTo(String value) {
            addCriterion("`acc_name` >=", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameLessThan(String value) {
            addCriterion("`acc_name` <", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameLessThanOrEqualTo(String value) {
            addCriterion("`acc_name` <=", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameLike(String value) {
            addCriterion("`acc_name` like", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameNotLike(String value) {
            addCriterion("`acc_name` not like", value, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameIn(List<String> values) {
            addCriterion("`acc_name` in", values, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameNotIn(List<String> values) {
            addCriterion("`acc_name` not in", values, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameBetween(String value1, String value2) {
            addCriterion("`acc_name` between", value1, value2, "accName");
            return (Criteria) this;
        }

        public Criteria andAccNameNotBetween(String value1, String value2) {
            addCriterion("`acc_name` not between", value1, value2, "accName");
            return (Criteria) this;
        }

        public Criteria andBankNumIsNull() {
            addCriterion("`bank_num` is null");
            return (Criteria) this;
        }

        public Criteria andBankNumIsNotNull() {
            addCriterion("`bank_num` is not null");
            return (Criteria) this;
        }

        public Criteria andBankNumEqualTo(String value) {
            addCriterion("`bank_num` =", value, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumNotEqualTo(String value) {
            addCriterion("`bank_num` <>", value, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumGreaterThan(String value) {
            addCriterion("`bank_num` >", value, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumGreaterThanOrEqualTo(String value) {
            addCriterion("`bank_num` >=", value, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumLessThan(String value) {
            addCriterion("`bank_num` <", value, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumLessThanOrEqualTo(String value) {
            addCriterion("`bank_num` <=", value, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumLike(String value) {
            addCriterion("`bank_num` like", value, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumNotLike(String value) {
            addCriterion("`bank_num` not like", value, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumIn(List<String> values) {
            addCriterion("`bank_num` in", values, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumNotIn(List<String> values) {
            addCriterion("`bank_num` not in", values, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumBetween(String value1, String value2) {
            addCriterion("`bank_num` between", value1, value2, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNumNotBetween(String value1, String value2) {
            addCriterion("`bank_num` not between", value1, value2, "bankNum");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("`bank_name` is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("`bank_name` is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("`bank_name` =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("`bank_name` <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("`bank_name` >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("`bank_name` >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("`bank_name` <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("`bank_name` <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("`bank_name` like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("`bank_name` not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("`bank_name` in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("`bank_name` not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("`bank_name` between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("`bank_name` not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andAgentCdIsNull() {
            addCriterion("`agent_cd` is null");
            return (Criteria) this;
        }

        public Criteria andAgentCdIsNotNull() {
            addCriterion("`agent_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentCdEqualTo(String value) {
            addCriterion("`agent_cd` =", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotEqualTo(String value) {
            addCriterion("`agent_cd` <>", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThan(String value) {
            addCriterion("`agent_cd` >", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_cd` >=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThan(String value) {
            addCriterion("`agent_cd` <", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLessThanOrEqualTo(String value) {
            addCriterion("`agent_cd` <=", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdLike(String value) {
            addCriterion("`agent_cd` like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotLike(String value) {
            addCriterion("`agent_cd` not like", value, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdIn(List<String> values) {
            addCriterion("`agent_cd` in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotIn(List<String> values) {
            addCriterion("`agent_cd` not in", values, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdBetween(String value1, String value2) {
            addCriterion("`agent_cd` between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentCdNotBetween(String value1, String value2) {
            addCriterion("`agent_cd` not between", value1, value2, "agentCd");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsIsNull() {
            addCriterion("`agent_mchnt_rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsIsNotNull() {
            addCriterion("`agent_mchnt_rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsEqualTo(Date value) {
            addCriterion("`agent_mchnt_rec_crt_ts` =", value, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsNotEqualTo(Date value) {
            addCriterion("`agent_mchnt_rec_crt_ts` <>", value, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsGreaterThan(Date value) {
            addCriterion("`agent_mchnt_rec_crt_ts` >", value, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`agent_mchnt_rec_crt_ts` >=", value, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsLessThan(Date value) {
            addCriterion("`agent_mchnt_rec_crt_ts` <", value, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`agent_mchnt_rec_crt_ts` <=", value, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsIn(List<Date> values) {
            addCriterion("`agent_mchnt_rec_crt_ts` in", values, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsNotIn(List<Date> values) {
            addCriterion("`agent_mchnt_rec_crt_ts` not in", values, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`agent_mchnt_rec_crt_ts` between", value1, value2, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`agent_mchnt_rec_crt_ts` not between", value1, value2, "agentMchntRecCrtTs");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateIsNull() {
            addCriterion("`agent_mchnt_state` is null");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateIsNotNull() {
            addCriterion("`agent_mchnt_state` is not null");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateEqualTo(String value) {
            addCriterion("`agent_mchnt_state` =", value, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateNotEqualTo(String value) {
            addCriterion("`agent_mchnt_state` <>", value, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateGreaterThan(String value) {
            addCriterion("`agent_mchnt_state` >", value, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateGreaterThanOrEqualTo(String value) {
            addCriterion("`agent_mchnt_state` >=", value, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateLessThan(String value) {
            addCriterion("`agent_mchnt_state` <", value, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateLessThanOrEqualTo(String value) {
            addCriterion("`agent_mchnt_state` <=", value, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateLike(String value) {
            addCriterion("`agent_mchnt_state` like", value, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateNotLike(String value) {
            addCriterion("`agent_mchnt_state` not like", value, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateIn(List<String> values) {
            addCriterion("`agent_mchnt_state` in", values, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateNotIn(List<String> values) {
            addCriterion("`agent_mchnt_state` not in", values, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateBetween(String value1, String value2) {
            addCriterion("`agent_mchnt_state` between", value1, value2, "agentMchntState");
            return (Criteria) this;
        }

        public Criteria andAgentMchntStateNotBetween(String value1, String value2) {
            addCriterion("`agent_mchnt_state` not between", value1, value2, "agentMchntState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_agent_mchnt_txn_01
     * @author user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : view_agent_mchnt_txn_01
     * @author user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}