package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_order01
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_order01
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderSeqIdIsNull() {
            addCriterion("`order_seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdIsNotNull() {
            addCriterion("`order_seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdEqualTo(String value) {
            addCriterion("`order_seq_id` =", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdNotEqualTo(String value) {
            addCriterion("`order_seq_id` <>", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdGreaterThan(String value) {
            addCriterion("`order_seq_id` >", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdGreaterThanOrEqualTo(String value) {
            addCriterion("`order_seq_id` >=", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdLessThan(String value) {
            addCriterion("`order_seq_id` <", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdLessThanOrEqualTo(String value) {
            addCriterion("`order_seq_id` <=", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdLike(String value) {
            addCriterion("`order_seq_id` like", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdNotLike(String value) {
            addCriterion("`order_seq_id` not like", value, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdIn(List<String> values) {
            addCriterion("`order_seq_id` in", values, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdNotIn(List<String> values) {
            addCriterion("`order_seq_id` not in", values, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdBetween(String value1, String value2) {
            addCriterion("`order_seq_id` between", value1, value2, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andOrderSeqIdNotBetween(String value1, String value2) {
            addCriterion("`order_seq_id` not between", value1, value2, "orderSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIsNull() {
            addCriterion("`trans_seq_id` is null");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIsNotNull() {
            addCriterion("`trans_seq_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdEqualTo(String value) {
            addCriterion("`trans_seq_id` =", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotEqualTo(String value) {
            addCriterion("`trans_seq_id` <>", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdGreaterThan(String value) {
            addCriterion("`trans_seq_id` >", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdGreaterThanOrEqualTo(String value) {
            addCriterion("`trans_seq_id` >=", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLessThan(String value) {
            addCriterion("`trans_seq_id` <", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLessThanOrEqualTo(String value) {
            addCriterion("`trans_seq_id` <=", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdLike(String value) {
            addCriterion("`trans_seq_id` like", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotLike(String value) {
            addCriterion("`trans_seq_id` not like", value, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdIn(List<String> values) {
            addCriterion("`trans_seq_id` in", values, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotIn(List<String> values) {
            addCriterion("`trans_seq_id` not in", values, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdBetween(String value1, String value2) {
            addCriterion("`trans_seq_id` between", value1, value2, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andTransSeqIdNotBetween(String value1, String value2) {
            addCriterion("`trans_seq_id` not between", value1, value2, "transSeqId");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNull() {
            addCriterion("`mchnt_cd` is null");
            return (Criteria) this;
        }

        public Criteria andMchntCdIsNotNull() {
            addCriterion("`mchnt_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andMchntCdEqualTo(String value) {
            addCriterion("`mchnt_cd` =", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotEqualTo(String value) {
            addCriterion("`mchnt_cd` <>", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThan(String value) {
            addCriterion("`mchnt_cd` >", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdGreaterThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` >=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThan(String value) {
            addCriterion("`mchnt_cd` <", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLessThanOrEqualTo(String value) {
            addCriterion("`mchnt_cd` <=", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdLike(String value) {
            addCriterion("`mchnt_cd` like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotLike(String value) {
            addCriterion("`mchnt_cd` not like", value, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdIn(List<String> values) {
            addCriterion("`mchnt_cd` in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotIn(List<String> values) {
            addCriterion("`mchnt_cd` not in", values, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andMchntCdNotBetween(String value1, String value2) {
            addCriterion("`mchnt_cd` not between", value1, value2, "mchntCd");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("`order_id` is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("`order_id` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("`order_id` =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("`order_id` <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("`order_id` >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("`order_id` >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("`order_id` <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("`order_id` <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("`order_id` like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("`order_id` not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("`order_id` in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("`order_id` not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("`order_id` between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("`order_id` not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andExtTransDtIsNull() {
            addCriterion("`ext_trans_dt` is null");
            return (Criteria) this;
        }

        public Criteria andExtTransDtIsNotNull() {
            addCriterion("`ext_trans_dt` is not null");
            return (Criteria) this;
        }

        public Criteria andExtTransDtEqualTo(String value) {
            addCriterion("`ext_trans_dt` =", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtNotEqualTo(String value) {
            addCriterion("`ext_trans_dt` <>", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtGreaterThan(String value) {
            addCriterion("`ext_trans_dt` >", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtGreaterThanOrEqualTo(String value) {
            addCriterion("`ext_trans_dt` >=", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtLessThan(String value) {
            addCriterion("`ext_trans_dt` <", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtLessThanOrEqualTo(String value) {
            addCriterion("`ext_trans_dt` <=", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtLike(String value) {
            addCriterion("`ext_trans_dt` like", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtNotLike(String value) {
            addCriterion("`ext_trans_dt` not like", value, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtIn(List<String> values) {
            addCriterion("`ext_trans_dt` in", values, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtNotIn(List<String> values) {
            addCriterion("`ext_trans_dt` not in", values, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtBetween(String value1, String value2) {
            addCriterion("`ext_trans_dt` between", value1, value2, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransDtNotBetween(String value1, String value2) {
            addCriterion("`ext_trans_dt` not between", value1, value2, "extTransDt");
            return (Criteria) this;
        }

        public Criteria andExtTransTmIsNull() {
            addCriterion("`ext_trans_tm` is null");
            return (Criteria) this;
        }

        public Criteria andExtTransTmIsNotNull() {
            addCriterion("`ext_trans_tm` is not null");
            return (Criteria) this;
        }

        public Criteria andExtTransTmEqualTo(String value) {
            addCriterion("`ext_trans_tm` =", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmNotEqualTo(String value) {
            addCriterion("`ext_trans_tm` <>", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmGreaterThan(String value) {
            addCriterion("`ext_trans_tm` >", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmGreaterThanOrEqualTo(String value) {
            addCriterion("`ext_trans_tm` >=", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmLessThan(String value) {
            addCriterion("`ext_trans_tm` <", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmLessThanOrEqualTo(String value) {
            addCriterion("`ext_trans_tm` <=", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmLike(String value) {
            addCriterion("`ext_trans_tm` like", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmNotLike(String value) {
            addCriterion("`ext_trans_tm` not like", value, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmIn(List<String> values) {
            addCriterion("`ext_trans_tm` in", values, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmNotIn(List<String> values) {
            addCriterion("`ext_trans_tm` not in", values, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmBetween(String value1, String value2) {
            addCriterion("`ext_trans_tm` between", value1, value2, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andExtTransTmNotBetween(String value1, String value2) {
            addCriterion("`ext_trans_tm` not between", value1, value2, "extTransTm");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIsNull() {
            addCriterion("`int_trans_cd` is null");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIsNotNull() {
            addCriterion("`int_trans_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andIntTransCdEqualTo(String value) {
            addCriterion("`int_trans_cd` =", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotEqualTo(String value) {
            addCriterion("`int_trans_cd` <>", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdGreaterThan(String value) {
            addCriterion("`int_trans_cd` >", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdGreaterThanOrEqualTo(String value) {
            addCriterion("`int_trans_cd` >=", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLessThan(String value) {
            addCriterion("`int_trans_cd` <", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLessThanOrEqualTo(String value) {
            addCriterion("`int_trans_cd` <=", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdLike(String value) {
            addCriterion("`int_trans_cd` like", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotLike(String value) {
            addCriterion("`int_trans_cd` not like", value, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdIn(List<String> values) {
            addCriterion("`int_trans_cd` in", values, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotIn(List<String> values) {
            addCriterion("`int_trans_cd` not in", values, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdBetween(String value1, String value2) {
            addCriterion("`int_trans_cd` between", value1, value2, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andIntTransCdNotBetween(String value1, String value2) {
            addCriterion("`int_trans_cd` not between", value1, value2, "intTransCd");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNull() {
            addCriterion("`trans_at` is null");
            return (Criteria) this;
        }

        public Criteria andTransAtIsNotNull() {
            addCriterion("`trans_at` is not null");
            return (Criteria) this;
        }

        public Criteria andTransAtEqualTo(Long value) {
            addCriterion("`trans_at` =", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotEqualTo(Long value) {
            addCriterion("`trans_at` <>", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThan(Long value) {
            addCriterion("`trans_at` >", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtGreaterThanOrEqualTo(Long value) {
            addCriterion("`trans_at` >=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThan(Long value) {
            addCriterion("`trans_at` <", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtLessThanOrEqualTo(Long value) {
            addCriterion("`trans_at` <=", value, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtIn(List<Long> values) {
            addCriterion("`trans_at` in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotIn(List<Long> values) {
            addCriterion("`trans_at` not in", values, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtBetween(Long value1, Long value2) {
            addCriterion("`trans_at` between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andTransAtNotBetween(Long value1, Long value2) {
            addCriterion("`trans_at` not between", value1, value2, "transAt");
            return (Criteria) this;
        }

        public Criteria andCurrCdIsNull() {
            addCriterion("`curr_cd` is null");
            return (Criteria) this;
        }

        public Criteria andCurrCdIsNotNull() {
            addCriterion("`curr_cd` is not null");
            return (Criteria) this;
        }

        public Criteria andCurrCdEqualTo(String value) {
            addCriterion("`curr_cd` =", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotEqualTo(String value) {
            addCriterion("`curr_cd` <>", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdGreaterThan(String value) {
            addCriterion("`curr_cd` >", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdGreaterThanOrEqualTo(String value) {
            addCriterion("`curr_cd` >=", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLessThan(String value) {
            addCriterion("`curr_cd` <", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLessThanOrEqualTo(String value) {
            addCriterion("`curr_cd` <=", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdLike(String value) {
            addCriterion("`curr_cd` like", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotLike(String value) {
            addCriterion("`curr_cd` not like", value, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdIn(List<String> values) {
            addCriterion("`curr_cd` in", values, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotIn(List<String> values) {
            addCriterion("`curr_cd` not in", values, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdBetween(String value1, String value2) {
            addCriterion("`curr_cd` between", value1, value2, "currCd");
            return (Criteria) this;
        }

        public Criteria andCurrCdNotBetween(String value1, String value2) {
            addCriterion("`curr_cd` not between", value1, value2, "currCd");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqIsNull() {
            addCriterion("`orig_log_seq` is null");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqIsNotNull() {
            addCriterion("`orig_log_seq` is not null");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqEqualTo(String value) {
            addCriterion("`orig_log_seq` =", value, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqNotEqualTo(String value) {
            addCriterion("`orig_log_seq` <>", value, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqGreaterThan(String value) {
            addCriterion("`orig_log_seq` >", value, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqGreaterThanOrEqualTo(String value) {
            addCriterion("`orig_log_seq` >=", value, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqLessThan(String value) {
            addCriterion("`orig_log_seq` <", value, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqLessThanOrEqualTo(String value) {
            addCriterion("`orig_log_seq` <=", value, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqLike(String value) {
            addCriterion("`orig_log_seq` like", value, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqNotLike(String value) {
            addCriterion("`orig_log_seq` not like", value, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqIn(List<String> values) {
            addCriterion("`orig_log_seq` in", values, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqNotIn(List<String> values) {
            addCriterion("`orig_log_seq` not in", values, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqBetween(String value1, String value2) {
            addCriterion("`orig_log_seq` between", value1, value2, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andOrigLogSeqNotBetween(String value1, String value2) {
            addCriterion("`orig_log_seq` not between", value1, value2, "origLogSeq");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andNotifyStateIsNull() {
            addCriterion("`notify_state` is null");
            return (Criteria) this;
        }

        public Criteria andNotifyStateIsNotNull() {
            addCriterion("`notify_state` is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyStateEqualTo(String value) {
            addCriterion("`notify_state` =", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateNotEqualTo(String value) {
            addCriterion("`notify_state` <>", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateGreaterThan(String value) {
            addCriterion("`notify_state` >", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateGreaterThanOrEqualTo(String value) {
            addCriterion("`notify_state` >=", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateLessThan(String value) {
            addCriterion("`notify_state` <", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateLessThanOrEqualTo(String value) {
            addCriterion("`notify_state` <=", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateLike(String value) {
            addCriterion("`notify_state` like", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateNotLike(String value) {
            addCriterion("`notify_state` not like", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateIn(List<String> values) {
            addCriterion("`notify_state` in", values, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateNotIn(List<String> values) {
            addCriterion("`notify_state` not in", values, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateBetween(String value1, String value2) {
            addCriterion("`notify_state` between", value1, value2, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateNotBetween(String value1, String value2) {
            addCriterion("`notify_state` not between", value1, value2, "notifyState");
            return (Criteria) this;
        }

        public Criteria andTxnSrcIsNull() {
            addCriterion("`txn_src` is null");
            return (Criteria) this;
        }

        public Criteria andTxnSrcIsNotNull() {
            addCriterion("`txn_src` is not null");
            return (Criteria) this;
        }

        public Criteria andTxnSrcEqualTo(String value) {
            addCriterion("`txn_src` =", value, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcNotEqualTo(String value) {
            addCriterion("`txn_src` <>", value, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcGreaterThan(String value) {
            addCriterion("`txn_src` >", value, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcGreaterThanOrEqualTo(String value) {
            addCriterion("`txn_src` >=", value, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcLessThan(String value) {
            addCriterion("`txn_src` <", value, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcLessThanOrEqualTo(String value) {
            addCriterion("`txn_src` <=", value, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcLike(String value) {
            addCriterion("`txn_src` like", value, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcNotLike(String value) {
            addCriterion("`txn_src` not like", value, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcIn(List<String> values) {
            addCriterion("`txn_src` in", values, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcNotIn(List<String> values) {
            addCriterion("`txn_src` not in", values, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcBetween(String value1, String value2) {
            addCriterion("`txn_src` between", value1, value2, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andTxnSrcNotBetween(String value1, String value2) {
            addCriterion("`txn_src` not between", value1, value2, "txnSrc");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNull() {
            addCriterion("`last_oper_id` is null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIsNotNull() {
            addCriterion("`last_oper_id` is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperIdEqualTo(String value) {
            addCriterion("`last_oper_id` =", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotEqualTo(String value) {
            addCriterion("`last_oper_id` <>", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThan(String value) {
            addCriterion("`last_oper_id` >", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` >=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThan(String value) {
            addCriterion("`last_oper_id` <", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLessThanOrEqualTo(String value) {
            addCriterion("`last_oper_id` <=", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdLike(String value) {
            addCriterion("`last_oper_id` like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotLike(String value) {
            addCriterion("`last_oper_id` not like", value, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdIn(List<String> values) {
            addCriterion("`last_oper_id` in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotIn(List<String> values) {
            addCriterion("`last_oper_id` not in", values, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdBetween(String value1, String value2) {
            addCriterion("`last_oper_id` between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andLastOperIdNotBetween(String value1, String value2) {
            addCriterion("`last_oper_id` not between", value1, value2, "lastOperId");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("`note` is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("`note` is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("`note` =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("`note` <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("`note` >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("`note` >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("`note` <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("`note` <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("`note` like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("`note` not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("`note` in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("`note` not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("`note` between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("`note` not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_order01
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_order01
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}