package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TermSignInfoExample {
    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public TermSignInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_term_sign_info
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_term_sign_info
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTermMnIsNull() {
            addCriterion("`term_mn` is null");
            return (Criteria) this;
        }

        public Criteria andTermMnIsNotNull() {
            addCriterion("`term_mn` is not null");
            return (Criteria) this;
        }

        public Criteria andTermMnEqualTo(String value) {
            addCriterion("`term_mn` =", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnNotEqualTo(String value) {
            addCriterion("`term_mn` <>", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnGreaterThan(String value) {
            addCriterion("`term_mn` >", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnGreaterThanOrEqualTo(String value) {
            addCriterion("`term_mn` >=", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnLessThan(String value) {
            addCriterion("`term_mn` <", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnLessThanOrEqualTo(String value) {
            addCriterion("`term_mn` <=", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnLike(String value) {
            addCriterion("`term_mn` like", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnNotLike(String value) {
            addCriterion("`term_mn` not like", value, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnIn(List<String> values) {
            addCriterion("`term_mn` in", values, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnNotIn(List<String> values) {
            addCriterion("`term_mn` not in", values, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnBetween(String value1, String value2) {
            addCriterion("`term_mn` between", value1, value2, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermMnNotBetween(String value1, String value2) {
            addCriterion("`term_mn` not between", value1, value2, "termMn");
            return (Criteria) this;
        }

        public Criteria andTermBnIsNull() {
            addCriterion("`term_bn` is null");
            return (Criteria) this;
        }

        public Criteria andTermBnIsNotNull() {
            addCriterion("`term_bn` is not null");
            return (Criteria) this;
        }

        public Criteria andTermBnEqualTo(String value) {
            addCriterion("`term_bn` =", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnNotEqualTo(String value) {
            addCriterion("`term_bn` <>", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnGreaterThan(String value) {
            addCriterion("`term_bn` >", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnGreaterThanOrEqualTo(String value) {
            addCriterion("`term_bn` >=", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnLessThan(String value) {
            addCriterion("`term_bn` <", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnLessThanOrEqualTo(String value) {
            addCriterion("`term_bn` <=", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnLike(String value) {
            addCriterion("`term_bn` like", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnNotLike(String value) {
            addCriterion("`term_bn` not like", value, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnIn(List<String> values) {
            addCriterion("`term_bn` in", values, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnNotIn(List<String> values) {
            addCriterion("`term_bn` not in", values, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnBetween(String value1, String value2) {
            addCriterion("`term_bn` between", value1, value2, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermBnNotBetween(String value1, String value2) {
            addCriterion("`term_bn` not between", value1, value2, "termBn");
            return (Criteria) this;
        }

        public Criteria andTermSnIsNull() {
            addCriterion("`term_sn` is null");
            return (Criteria) this;
        }

        public Criteria andTermSnIsNotNull() {
            addCriterion("`term_sn` is not null");
            return (Criteria) this;
        }

        public Criteria andTermSnEqualTo(String value) {
            addCriterion("`term_sn` =", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotEqualTo(String value) {
            addCriterion("`term_sn` <>", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnGreaterThan(String value) {
            addCriterion("`term_sn` >", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnGreaterThanOrEqualTo(String value) {
            addCriterion("`term_sn` >=", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLessThan(String value) {
            addCriterion("`term_sn` <", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLessThanOrEqualTo(String value) {
            addCriterion("`term_sn` <=", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnLike(String value) {
            addCriterion("`term_sn` like", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotLike(String value) {
            addCriterion("`term_sn` not like", value, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnIn(List<String> values) {
            addCriterion("`term_sn` in", values, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotIn(List<String> values) {
            addCriterion("`term_sn` not in", values, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnBetween(String value1, String value2) {
            addCriterion("`term_sn` between", value1, value2, "termSn");
            return (Criteria) this;
        }

        public Criteria andTermSnNotBetween(String value1, String value2) {
            addCriterion("`term_sn` not between", value1, value2, "termSn");
            return (Criteria) this;
        }

        public Criteria andReqIpIsNull() {
            addCriterion("`req_ip` is null");
            return (Criteria) this;
        }

        public Criteria andReqIpIsNotNull() {
            addCriterion("`req_ip` is not null");
            return (Criteria) this;
        }

        public Criteria andReqIpEqualTo(String value) {
            addCriterion("`req_ip` =", value, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpNotEqualTo(String value) {
            addCriterion("`req_ip` <>", value, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpGreaterThan(String value) {
            addCriterion("`req_ip` >", value, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpGreaterThanOrEqualTo(String value) {
            addCriterion("`req_ip` >=", value, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpLessThan(String value) {
            addCriterion("`req_ip` <", value, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpLessThanOrEqualTo(String value) {
            addCriterion("`req_ip` <=", value, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpLike(String value) {
            addCriterion("`req_ip` like", value, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpNotLike(String value) {
            addCriterion("`req_ip` not like", value, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpIn(List<String> values) {
            addCriterion("`req_ip` in", values, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpNotIn(List<String> values) {
            addCriterion("`req_ip` not in", values, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpBetween(String value1, String value2) {
            addCriterion("`req_ip` between", value1, value2, "reqIp");
            return (Criteria) this;
        }

        public Criteria andReqIpNotBetween(String value1, String value2) {
            addCriterion("`req_ip` not between", value1, value2, "reqIp");
            return (Criteria) this;
        }

        public Criteria andMakIsNull() {
            addCriterion("`mak` is null");
            return (Criteria) this;
        }

        public Criteria andMakIsNotNull() {
            addCriterion("`mak` is not null");
            return (Criteria) this;
        }

        public Criteria andMakEqualTo(String value) {
            addCriterion("`mak` =", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakNotEqualTo(String value) {
            addCriterion("`mak` <>", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakGreaterThan(String value) {
            addCriterion("`mak` >", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakGreaterThanOrEqualTo(String value) {
            addCriterion("`mak` >=", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakLessThan(String value) {
            addCriterion("`mak` <", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakLessThanOrEqualTo(String value) {
            addCriterion("`mak` <=", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakLike(String value) {
            addCriterion("`mak` like", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakNotLike(String value) {
            addCriterion("`mak` not like", value, "mak");
            return (Criteria) this;
        }

        public Criteria andMakIn(List<String> values) {
            addCriterion("`mak` in", values, "mak");
            return (Criteria) this;
        }

        public Criteria andMakNotIn(List<String> values) {
            addCriterion("`mak` not in", values, "mak");
            return (Criteria) this;
        }

        public Criteria andMakBetween(String value1, String value2) {
            addCriterion("`mak` between", value1, value2, "mak");
            return (Criteria) this;
        }

        public Criteria andMakNotBetween(String value1, String value2) {
            addCriterion("`mak` not between", value1, value2, "mak");
            return (Criteria) this;
        }

        public Criteria andPikIsNull() {
            addCriterion("`pik` is null");
            return (Criteria) this;
        }

        public Criteria andPikIsNotNull() {
            addCriterion("`pik` is not null");
            return (Criteria) this;
        }

        public Criteria andPikEqualTo(String value) {
            addCriterion("`pik` =", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikNotEqualTo(String value) {
            addCriterion("`pik` <>", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikGreaterThan(String value) {
            addCriterion("`pik` >", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikGreaterThanOrEqualTo(String value) {
            addCriterion("`pik` >=", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikLessThan(String value) {
            addCriterion("`pik` <", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikLessThanOrEqualTo(String value) {
            addCriterion("`pik` <=", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikLike(String value) {
            addCriterion("`pik` like", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikNotLike(String value) {
            addCriterion("`pik` not like", value, "pik");
            return (Criteria) this;
        }

        public Criteria andPikIn(List<String> values) {
            addCriterion("`pik` in", values, "pik");
            return (Criteria) this;
        }

        public Criteria andPikNotIn(List<String> values) {
            addCriterion("`pik` not in", values, "pik");
            return (Criteria) this;
        }

        public Criteria andPikBetween(String value1, String value2) {
            addCriterion("`pik` between", value1, value2, "pik");
            return (Criteria) this;
        }

        public Criteria andPikNotBetween(String value1, String value2) {
            addCriterion("`pik` not between", value1, value2, "pik");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNull() {
            addCriterion("`rec_crt_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIsNotNull() {
            addCriterion("`rec_crt_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsEqualTo(Date value) {
            addCriterion("`rec_crt_ts` =", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <>", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThan(Date value) {
            addCriterion("`rec_crt_ts` >", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` >=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThan(Date value) {
            addCriterion("`rec_crt_ts` <", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_crt_ts` <=", value, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsIn(List<Date> values) {
            addCriterion("`rec_crt_ts` in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotIn(List<Date> values) {
            addCriterion("`rec_crt_ts` not in", values, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_crt_ts` not between", value1, value2, "recCrtTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNull() {
            addCriterion("`rec_upd_ts` is null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIsNotNull() {
            addCriterion("`rec_upd_ts` is not null");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsEqualTo(Date value) {
            addCriterion("`rec_upd_ts` =", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <>", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThan(Date value) {
            addCriterion("`rec_upd_ts` >", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` >=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThan(Date value) {
            addCriterion("`rec_upd_ts` <", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
            addCriterion("`rec_upd_ts` <=", value, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsIn(List<Date> values) {
            addCriterion("`rec_upd_ts` in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotIn(List<Date> values) {
            addCriterion("`rec_upd_ts` not in", values, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }

        public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
            addCriterion("`rec_upd_ts` not between", value1, value2, "recUpdTs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_term_sign_info
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_term_sign_info
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}