package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : view_mchnt_settle_info

 *
 * @mbg.generated
 */
public class MchntSettleInfo implements Serializable {
    /**
     * Database column : view_mchnt_settle_info.chnl_id
     *
     * @mbg.generated
     */
    private String chnlId;

    /**
     * Database column : view_mchnt_settle_info.chnl_mchnt_cd
     *
     * @mbg.generated
     */
    private String chnlMchntCd;

    /**
     * Database column : view_mchnt_settle_info.int_trans_cd
     *
     * @mbg.generated
     */
    private String intTransCd;

    /**
     * Database column : view_mchnt_settle_info.settle_mode
     *
     * @mbg.generated
     */
    private String settleMode;

    /**
     * Database column : view_mchnt_settle_info.settle_algorithm
     *
     * @mbg.generated
     */
    private String settleAlgorithm;

    /**
     * Database column : view_mchnt_settle_info.tx_t0_percent
     *
     * @mbg.generated
     */
    private String txT0Percent;

    /**
     * Database column : view_mchnt_settle_info.tx_time_limit
     *
     * @mbg.generated
     */
    private String txTimeLimit;

    /**
     * Database column : view_mchnt_settle_info.tx_amt_min
     *
     * @mbg.generated
     */
    private String txAmtMin;

    /**
     * Database column : view_mchnt_settle_info.tx_amt_max
     *
     * @mbg.generated
     */
    private String txAmtMax;

    /**
     * Database column : view_mchnt_settle_info.tx_day_max
     *
     * @mbg.generated
     */
    private String txDayMax;

    /**
     * Database column : view_mchnt_settle_info.tx_card_day_max
     *
     * @mbg.generated
     */
    private String txCardDayMax;

    /**
     * Database column : view_mchnt_settle_info.settle_period
     *
     * @mbg.generated
     */
    private String settlePeriod;

    /**
     * Database table : view_mchnt_settle_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : view_mchnt_settle_info
     *
     * @mbg.generated
     */
    public MchntSettleInfo(String chnlId, String chnlMchntCd, String intTransCd, String settleMode, String settleAlgorithm, String txT0Percent, String txTimeLimit, String txAmtMin, String txAmtMax, String txDayMax, String txCardDayMax, String settlePeriod) {
        this.chnlId = chnlId;
        this.chnlMchntCd = chnlMchntCd;
        this.intTransCd = intTransCd;
        this.settleMode = settleMode;
        this.settleAlgorithm = settleAlgorithm;
        this.txT0Percent = txT0Percent;
        this.txTimeLimit = txTimeLimit;
        this.txAmtMin = txAmtMin;
        this.txAmtMax = txAmtMax;
        this.txDayMax = txDayMax;
        this.txCardDayMax = txCardDayMax;
        this.settlePeriod = settlePeriod;
    }

    /**
     * Database table : view_mchnt_settle_info
     *
     * @mbg.generated
     */
    public MchntSettleInfo() {
        super();
    }

    /**
     * @return chnl_id 
     *
     * @mbg.generated
     */
    public String getChnlId() {
        return chnlId;
    }

    /**
     * @param chnlId 
     *
     * @mbg.generated
     */
    public void setChnlId(String chnlId) {
        this.chnlId = chnlId;
    }

    /**
     * @return chnl_mchnt_cd 
     *
     * @mbg.generated
     */
    public String getChnlMchntCd() {
        return chnlMchntCd;
    }

    /**
     * @param chnlMchntCd 
     *
     * @mbg.generated
     */
    public void setChnlMchntCd(String chnlMchntCd) {
        this.chnlMchntCd = chnlMchntCd;
    }

    /**
     * @return int_trans_cd 
     *
     * @mbg.generated
     */
    public String getIntTransCd() {
        return intTransCd;
    }

    /**
     * @param intTransCd 
     *
     * @mbg.generated
     */
    public void setIntTransCd(String intTransCd) {
        this.intTransCd = intTransCd;
    }

    /**
     * @return settle_mode 
     *
     * @mbg.generated
     */
    public String getSettleMode() {
        return settleMode;
    }

    /**
     * @param settleMode 
     *
     * @mbg.generated
     */
    public void setSettleMode(String settleMode) {
        this.settleMode = settleMode;
    }

    /**
     * @return settle_algorithm 
     *
     * @mbg.generated
     */
    public String getSettleAlgorithm() {
        return settleAlgorithm;
    }

    /**
     * @param settleAlgorithm 
     *
     * @mbg.generated
     */
    public void setSettleAlgorithm(String settleAlgorithm) {
        this.settleAlgorithm = settleAlgorithm;
    }

    /**
     * @return tx_t0_percent 
     *
     * @mbg.generated
     */
    public String getTxT0Percent() {
        return txT0Percent;
    }

    /**
     * @param txT0Percent 
     *
     * @mbg.generated
     */
    public void setTxT0Percent(String txT0Percent) {
        this.txT0Percent = txT0Percent;
    }

    /**
     * @return tx_time_limit 
     *
     * @mbg.generated
     */
    public String getTxTimeLimit() {
        return txTimeLimit;
    }

    /**
     * @param txTimeLimit 
     *
     * @mbg.generated
     */
    public void setTxTimeLimit(String txTimeLimit) {
        this.txTimeLimit = txTimeLimit;
    }

    /**
     * @return tx_amt_min 
     *
     * @mbg.generated
     */
    public String getTxAmtMin() {
        return txAmtMin;
    }

    /**
     * @param txAmtMin 
     *
     * @mbg.generated
     */
    public void setTxAmtMin(String txAmtMin) {
        this.txAmtMin = txAmtMin;
    }

    /**
     * @return tx_amt_max 
     *
     * @mbg.generated
     */
    public String getTxAmtMax() {
        return txAmtMax;
    }

    /**
     * @param txAmtMax 
     *
     * @mbg.generated
     */
    public void setTxAmtMax(String txAmtMax) {
        this.txAmtMax = txAmtMax;
    }

    /**
     * @return tx_day_max 
     *
     * @mbg.generated
     */
    public String getTxDayMax() {
        return txDayMax;
    }

    /**
     * @param txDayMax 
     *
     * @mbg.generated
     */
    public void setTxDayMax(String txDayMax) {
        this.txDayMax = txDayMax;
    }

    /**
     * @return tx_card_day_max 
     *
     * @mbg.generated
     */
    public String getTxCardDayMax() {
        return txCardDayMax;
    }

    /**
     * @param txCardDayMax 
     *
     * @mbg.generated
     */
    public void setTxCardDayMax(String txCardDayMax) {
        this.txCardDayMax = txCardDayMax;
    }

    /**
     * @return settle_period 
     *
     * @mbg.generated
     */
    public String getSettlePeriod() {
        return settlePeriod;
    }

    /**
     * @param settlePeriod 
     *
     * @mbg.generated
     */
    public void setSettlePeriod(String settlePeriod) {
        this.settlePeriod = settlePeriod;
    }

    /**
     * Database table : view_mchnt_settle_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MchntSettleInfo other = (MchntSettleInfo) that;
        return (this.getChnlId() == null ? other.getChnlId() == null : this.getChnlId().equals(other.getChnlId()))
            && (this.getChnlMchntCd() == null ? other.getChnlMchntCd() == null : this.getChnlMchntCd().equals(other.getChnlMchntCd()))
            && (this.getIntTransCd() == null ? other.getIntTransCd() == null : this.getIntTransCd().equals(other.getIntTransCd()))
            && (this.getSettleMode() == null ? other.getSettleMode() == null : this.getSettleMode().equals(other.getSettleMode()))
            && (this.getSettleAlgorithm() == null ? other.getSettleAlgorithm() == null : this.getSettleAlgorithm().equals(other.getSettleAlgorithm()))
            && (this.getTxT0Percent() == null ? other.getTxT0Percent() == null : this.getTxT0Percent().equals(other.getTxT0Percent()))
            && (this.getTxTimeLimit() == null ? other.getTxTimeLimit() == null : this.getTxTimeLimit().equals(other.getTxTimeLimit()))
            && (this.getTxAmtMin() == null ? other.getTxAmtMin() == null : this.getTxAmtMin().equals(other.getTxAmtMin()))
            && (this.getTxAmtMax() == null ? other.getTxAmtMax() == null : this.getTxAmtMax().equals(other.getTxAmtMax()))
            && (this.getTxDayMax() == null ? other.getTxDayMax() == null : this.getTxDayMax().equals(other.getTxDayMax()))
            && (this.getTxCardDayMax() == null ? other.getTxCardDayMax() == null : this.getTxCardDayMax().equals(other.getTxCardDayMax()))
            && (this.getSettlePeriod() == null ? other.getSettlePeriod() == null : this.getSettlePeriod().equals(other.getSettlePeriod()));
    }

    /**
     * Database table : view_mchnt_settle_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChnlId() == null) ? 0 : getChnlId().hashCode());
        result = prime * result + ((getChnlMchntCd() == null) ? 0 : getChnlMchntCd().hashCode());
        result = prime * result + ((getIntTransCd() == null) ? 0 : getIntTransCd().hashCode());
        result = prime * result + ((getSettleMode() == null) ? 0 : getSettleMode().hashCode());
        result = prime * result + ((getSettleAlgorithm() == null) ? 0 : getSettleAlgorithm().hashCode());
        result = prime * result + ((getTxT0Percent() == null) ? 0 : getTxT0Percent().hashCode());
        result = prime * result + ((getTxTimeLimit() == null) ? 0 : getTxTimeLimit().hashCode());
        result = prime * result + ((getTxAmtMin() == null) ? 0 : getTxAmtMin().hashCode());
        result = prime * result + ((getTxAmtMax() == null) ? 0 : getTxAmtMax().hashCode());
        result = prime * result + ((getTxDayMax() == null) ? 0 : getTxDayMax().hashCode());
        result = prime * result + ((getTxCardDayMax() == null) ? 0 : getTxCardDayMax().hashCode());
        result = prime * result + ((getSettlePeriod() == null) ? 0 : getSettlePeriod().hashCode());
        return result;
    }

    /**
     * Database table : view_mchnt_settle_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", chnlId=").append(chnlId);
        sb.append(", chnlMchntCd=").append(chnlMchntCd);
        sb.append(", intTransCd=").append(intTransCd);
        sb.append(", settleMode=").append(settleMode);
        sb.append(", settleAlgorithm=").append(settleAlgorithm);
        sb.append(", txT0Percent=").append(txT0Percent);
        sb.append(", txTimeLimit=").append(txTimeLimit);
        sb.append(", txAmtMin=").append(txAmtMin);
        sb.append(", txAmtMax=").append(txAmtMax);
        sb.append(", txDayMax=").append(txDayMax);
        sb.append(", txCardDayMax=").append(txCardDayMax);
        sb.append(", settlePeriod=").append(settlePeriod);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(MchntSettleInfo source) {
        this.chnlId=source.chnlId;
        this.chnlMchntCd=source.chnlMchntCd;
        this.intTransCd=source.intTransCd;
        this.settleMode=source.settleMode;
        this.settleAlgorithm=source.settleAlgorithm;
        this.txT0Percent=source.txT0Percent;
        this.txTimeLimit=source.txTimeLimit;
        this.txAmtMin=source.txAmtMin;
        this.txAmtMax=source.txAmtMax;
        this.txDayMax=source.txDayMax;
        this.txCardDayMax=source.txCardDayMax;
        this.settlePeriod=source.settlePeriod;
    }
}