package com.icpay.payment.db.dao.mybatis.model;

import java.io.Serializable;
import java.util.Date;

/**
 * [Model class] 
 *
 * This class was generated by MyBatis Generator.
 * Database table : tbl_vacc_flow

 *
 * @mbg.generated
 */
public class VaccFlow implements Serializable {
    /**
     * 自动新增流水号
     * Database column : tbl_vacc_flow.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * 来源-分类目录
     * Database column : tbl_vacc_flow.from_cat
     *
     * @mbg.generated
     */
    private String fromCat;

    /**
     * 来源-帐户号
     * Database column : tbl_vacc_flow.from_acc_id
     *
     * @mbg.generated
     */
    private String fromAccId;

    /**
     * 来源-帐户子编号
     * Database column : tbl_vacc_flow.from_acc_sub_id
     *
     * @mbg.generated
     */
    private String fromAccSubId;

    /**
     * 流向-分类目录
     * Database column : tbl_vacc_flow.to_cat
     *
     * @mbg.generated
     */
    private String toCat;

    /**
     * 流向-帐户号
     * Database column : tbl_vacc_flow.to_acc_id
     *
     * @mbg.generated
     */
    private String toAccId;

    /**
     * 流向-帐户子编号
     * Database column : tbl_vacc_flow.to_acc_sub_id
     *
     * @mbg.generated
     */
    private String toAccSubId;

    /**
     * 交易/转帐金额
     * Database column : tbl_vacc_flow.trans_amt
     *
     * @mbg.generated
     */
    private Long transAmt;

    /**
     * 交易流水-帐本id
     * Database column : tbl_vacc_flow.trans_book
     *
     * @mbg.generated
     */
    private String transBook;

    /**
     * 交易流水-主分类(科)
     * Database column : tbl_vacc_flow.trans_catalog
     *
     * @mbg.generated
     */
    private String transCatalog;

    /**
     * 交易流水-子分类(子目)
     * Database column : tbl_vacc_flow.trans_sub_catlog
     *
     * @mbg.generated
     */
    private String transSubCatlog;

    /**
     * 手续费的流水id(tbl_vacc_flow)，若无则留null
     * Database column : tbl_vacc_flow.trans_fee_id
     *
     * @mbg.generated
     */
    private Long transFeeId;

    /**
     * 说明
     * Database column : tbl_vacc_flow.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * Database column : tbl_vacc_flow.rec_crt_ts
     *
     * @mbg.generated
     */
    private Date recCrtTs;

    /**
     * Database column : tbl_vacc_flow.rec_upd_ts
     *
     * @mbg.generated
     */
    private Date recUpdTs;

    /**
     * Database table : tbl_vacc_flow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * Database table : tbl_vacc_flow
     *
     * @mbg.generated
     */
    public VaccFlow(Long id, String fromCat, String fromAccId, String fromAccSubId, String toCat, String toAccId, String toAccSubId, Long transAmt, String transBook, String transCatalog, String transSubCatlog, Long transFeeId, String memo, Date recCrtTs, Date recUpdTs) {
        this.id = id;
        this.fromCat = fromCat;
        this.fromAccId = fromAccId;
        this.fromAccSubId = fromAccSubId;
        this.toCat = toCat;
        this.toAccId = toAccId;
        this.toAccSubId = toAccSubId;
        this.transAmt = transAmt;
        this.transBook = transBook;
        this.transCatalog = transCatalog;
        this.transSubCatlog = transSubCatlog;
        this.transFeeId = transFeeId;
        this.memo = memo;
        this.recCrtTs = recCrtTs;
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_vacc_flow
     *
     * @mbg.generated
     */
    public VaccFlow() {
        super();
    }

    /**
     * 自动新增流水号
     * @return id 自动新增流水号
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * 自动新增流水号
     * @param id 自动新增流水号
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 来源-分类目录
     * @return from_cat 来源-分类目录
     *
     * @mbg.generated
     */
    public String getFromCat() {
        return fromCat;
    }

    /**
     * 来源-分类目录
     * @param fromCat 来源-分类目录
     *
     * @mbg.generated
     */
    public void setFromCat(String fromCat) {
        this.fromCat = fromCat;
    }

    /**
     * 来源-帐户号
     * @return from_acc_id 来源-帐户号
     *
     * @mbg.generated
     */
    public String getFromAccId() {
        return fromAccId;
    }

    /**
     * 来源-帐户号
     * @param fromAccId 来源-帐户号
     *
     * @mbg.generated
     */
    public void setFromAccId(String fromAccId) {
        this.fromAccId = fromAccId;
    }

    /**
     * 来源-帐户子编号
     * @return from_acc_sub_id 来源-帐户子编号
     *
     * @mbg.generated
     */
    public String getFromAccSubId() {
        return fromAccSubId;
    }

    /**
     * 来源-帐户子编号
     * @param fromAccSubId 来源-帐户子编号
     *
     * @mbg.generated
     */
    public void setFromAccSubId(String fromAccSubId) {
        this.fromAccSubId = fromAccSubId;
    }

    /**
     * 流向-分类目录
     * @return to_cat 流向-分类目录
     *
     * @mbg.generated
     */
    public String getToCat() {
        return toCat;
    }

    /**
     * 流向-分类目录
     * @param toCat 流向-分类目录
     *
     * @mbg.generated
     */
    public void setToCat(String toCat) {
        this.toCat = toCat;
    }

    /**
     * 流向-帐户号
     * @return to_acc_id 流向-帐户号
     *
     * @mbg.generated
     */
    public String getToAccId() {
        return toAccId;
    }

    /**
     * 流向-帐户号
     * @param toAccId 流向-帐户号
     *
     * @mbg.generated
     */
    public void setToAccId(String toAccId) {
        this.toAccId = toAccId;
    }

    /**
     * 流向-帐户子编号
     * @return to_acc_sub_id 流向-帐户子编号
     *
     * @mbg.generated
     */
    public String getToAccSubId() {
        return toAccSubId;
    }

    /**
     * 流向-帐户子编号
     * @param toAccSubId 流向-帐户子编号
     *
     * @mbg.generated
     */
    public void setToAccSubId(String toAccSubId) {
        this.toAccSubId = toAccSubId;
    }

    /**
     * 交易/转帐金额
     * @return trans_amt 交易/转帐金额
     *
     * @mbg.generated
     */
    public Long getTransAmt() {
        return transAmt;
    }

    /**
     * 交易/转帐金额
     * @param transAmt 交易/转帐金额
     *
     * @mbg.generated
     */
    public void setTransAmt(Long transAmt) {
        this.transAmt = transAmt;
    }

    /**
     * 交易流水-帐本id
     * @return trans_book 交易流水-帐本id
     *
     * @mbg.generated
     */
    public String getTransBook() {
        return transBook;
    }

    /**
     * 交易流水-帐本id
     * @param transBook 交易流水-帐本id
     *
     * @mbg.generated
     */
    public void setTransBook(String transBook) {
        this.transBook = transBook;
    }

    /**
     * 交易流水-主分类(科)
     * @return trans_catalog 交易流水-主分类(科)
     *
     * @mbg.generated
     */
    public String getTransCatalog() {
        return transCatalog;
    }

    /**
     * 交易流水-主分类(科)
     * @param transCatalog 交易流水-主分类(科)
     *
     * @mbg.generated
     */
    public void setTransCatalog(String transCatalog) {
        this.transCatalog = transCatalog;
    }

    /**
     * 交易流水-子分类(子目)
     * @return trans_sub_catlog 交易流水-子分类(子目)
     *
     * @mbg.generated
     */
    public String getTransSubCatlog() {
        return transSubCatlog;
    }

    /**
     * 交易流水-子分类(子目)
     * @param transSubCatlog 交易流水-子分类(子目)
     *
     * @mbg.generated
     */
    public void setTransSubCatlog(String transSubCatlog) {
        this.transSubCatlog = transSubCatlog;
    }

    /**
     * 手续费的流水id(tbl_vacc_flow)，若无则留null
     * @return trans_fee_id 手续费的流水id(tbl_vacc_flow)，若无则留null
     *
     * @mbg.generated
     */
    public Long getTransFeeId() {
        return transFeeId;
    }

    /**
     * 手续费的流水id(tbl_vacc_flow)，若无则留null
     * @param transFeeId 手续费的流水id(tbl_vacc_flow)，若无则留null
     *
     * @mbg.generated
     */
    public void setTransFeeId(Long transFeeId) {
        this.transFeeId = transFeeId;
    }

    /**
     * 说明
     * @return memo 说明
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * 说明
     * @param memo 说明
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * @return rec_crt_ts 
     *
     * @mbg.generated
     */
    public Date getRecCrtTs() {
        return recCrtTs;
    }

    /**
     * @param recCrtTs 
     *
     * @mbg.generated
     */
    public void setRecCrtTs(Date recCrtTs) {
        this.recCrtTs = recCrtTs;
    }

    /**
     * @return rec_upd_ts 
     *
     * @mbg.generated
     */
    public Date getRecUpdTs() {
        return recUpdTs;
    }

    /**
     * @param recUpdTs 
     *
     * @mbg.generated
     */
    public void setRecUpdTs(Date recUpdTs) {
        this.recUpdTs = recUpdTs;
    }

    /**
     * Database table : tbl_vacc_flow
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VaccFlow other = (VaccFlow) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFromCat() == null ? other.getFromCat() == null : this.getFromCat().equals(other.getFromCat()))
            && (this.getFromAccId() == null ? other.getFromAccId() == null : this.getFromAccId().equals(other.getFromAccId()))
            && (this.getFromAccSubId() == null ? other.getFromAccSubId() == null : this.getFromAccSubId().equals(other.getFromAccSubId()))
            && (this.getToCat() == null ? other.getToCat() == null : this.getToCat().equals(other.getToCat()))
            && (this.getToAccId() == null ? other.getToAccId() == null : this.getToAccId().equals(other.getToAccId()))
            && (this.getToAccSubId() == null ? other.getToAccSubId() == null : this.getToAccSubId().equals(other.getToAccSubId()))
            && (this.getTransAmt() == null ? other.getTransAmt() == null : this.getTransAmt().equals(other.getTransAmt()))
            && (this.getTransBook() == null ? other.getTransBook() == null : this.getTransBook().equals(other.getTransBook()))
            && (this.getTransCatalog() == null ? other.getTransCatalog() == null : this.getTransCatalog().equals(other.getTransCatalog()))
            && (this.getTransSubCatlog() == null ? other.getTransSubCatlog() == null : this.getTransSubCatlog().equals(other.getTransSubCatlog()))
            && (this.getTransFeeId() == null ? other.getTransFeeId() == null : this.getTransFeeId().equals(other.getTransFeeId()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getRecCrtTs() == null ? other.getRecCrtTs() == null : this.getRecCrtTs().equals(other.getRecCrtTs()))
            && (this.getRecUpdTs() == null ? other.getRecUpdTs() == null : this.getRecUpdTs().equals(other.getRecUpdTs()));
    }

    /**
     * Database table : tbl_vacc_flow
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFromCat() == null) ? 0 : getFromCat().hashCode());
        result = prime * result + ((getFromAccId() == null) ? 0 : getFromAccId().hashCode());
        result = prime * result + ((getFromAccSubId() == null) ? 0 : getFromAccSubId().hashCode());
        result = prime * result + ((getToCat() == null) ? 0 : getToCat().hashCode());
        result = prime * result + ((getToAccId() == null) ? 0 : getToAccId().hashCode());
        result = prime * result + ((getToAccSubId() == null) ? 0 : getToAccSubId().hashCode());
        result = prime * result + ((getTransAmt() == null) ? 0 : getTransAmt().hashCode());
        result = prime * result + ((getTransBook() == null) ? 0 : getTransBook().hashCode());
        result = prime * result + ((getTransCatalog() == null) ? 0 : getTransCatalog().hashCode());
        result = prime * result + ((getTransSubCatlog() == null) ? 0 : getTransSubCatlog().hashCode());
        result = prime * result + ((getTransFeeId() == null) ? 0 : getTransFeeId().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getRecCrtTs() == null) ? 0 : getRecCrtTs().hashCode());
        result = prime * result + ((getRecUpdTs() == null) ? 0 : getRecUpdTs().hashCode());
        return result;
    }

    /**
     * Database table : tbl_vacc_flow
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash=").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fromCat=").append(fromCat);
        sb.append(", fromAccId=").append(fromAccId);
        sb.append(", fromAccSubId=").append(fromAccSubId);
        sb.append(", toCat=").append(toCat);
        sb.append(", toAccId=").append(toAccId);
        sb.append(", toAccSubId=").append(toAccSubId);
        sb.append(", transAmt=").append(transAmt);
        sb.append(", transBook=").append(transBook);
        sb.append(", transCatalog=").append(transCatalog);
        sb.append(", transSubCatlog=").append(transSubCatlog);
        sb.append(", transFeeId=").append(transFeeId);
        sb.append(", memo=").append(memo);
        sb.append(", recCrtTs=").append(recCrtTs);
        sb.append(", recUpdTs=").append(recUpdTs);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties value from source.
     * @param source The instance that clone from.
     *
     * @mbg.generated
     */
    public void cloneFrom(VaccFlow source) {
        this.id=source.id;
        this.fromCat=source.fromCat;
        this.fromAccId=source.fromAccId;
        this.fromAccSubId=source.fromAccSubId;
        this.toCat=source.toCat;
        this.toAccId=source.toAccId;
        this.toAccSubId=source.toAccSubId;
        this.transAmt=source.transAmt;
        this.transBook=source.transBook;
        this.transCatalog=source.transCatalog;
        this.transSubCatlog=source.transSubCatlog;
        this.transFeeId=source.transFeeId;
        this.memo=source.memo;
        this.recCrtTs=source.recCrtTs;
        this.recUpdTs=source.recUpdTs;
    }
}