package com.icpay.payment.db.dao.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class IntKeyExample {
    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    protected Integer startNum;

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    protected Integer pageSize;

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public IntKeyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Database table : tbl_int_key
     *
     * @mbg.generated
     */
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_int_key
    
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKeyTpIsNull() {
            addCriterion("`key_tp` is null");
            return (Criteria) this;
        }

        public Criteria andKeyTpIsNotNull() {
            addCriterion("`key_tp` is not null");
            return (Criteria) this;
        }

        public Criteria andKeyTpEqualTo(String value) {
            addCriterion("`key_tp` =", value, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpNotEqualTo(String value) {
            addCriterion("`key_tp` <>", value, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpGreaterThan(String value) {
            addCriterion("`key_tp` >", value, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpGreaterThanOrEqualTo(String value) {
            addCriterion("`key_tp` >=", value, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpLessThan(String value) {
            addCriterion("`key_tp` <", value, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpLessThanOrEqualTo(String value) {
            addCriterion("`key_tp` <=", value, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpLike(String value) {
            addCriterion("`key_tp` like", value, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpNotLike(String value) {
            addCriterion("`key_tp` not like", value, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpIn(List<String> values) {
            addCriterion("`key_tp` in", values, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpNotIn(List<String> values) {
            addCriterion("`key_tp` not in", values, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpBetween(String value1, String value2) {
            addCriterion("`key_tp` between", value1, value2, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyTpNotBetween(String value1, String value2) {
            addCriterion("`key_tp` not between", value1, value2, "keyTp");
            return (Criteria) this;
        }

        public Criteria andKeyValIsNull() {
            addCriterion("`key_val` is null");
            return (Criteria) this;
        }

        public Criteria andKeyValIsNotNull() {
            addCriterion("`key_val` is not null");
            return (Criteria) this;
        }

        public Criteria andKeyValEqualTo(Integer value) {
            addCriterion("`key_val` =", value, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValNotEqualTo(Integer value) {
            addCriterion("`key_val` <>", value, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValGreaterThan(Integer value) {
            addCriterion("`key_val` >", value, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValGreaterThanOrEqualTo(Integer value) {
            addCriterion("`key_val` >=", value, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValLessThan(Integer value) {
            addCriterion("`key_val` <", value, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValLessThanOrEqualTo(Integer value) {
            addCriterion("`key_val` <=", value, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValIn(List<Integer> values) {
            addCriterion("`key_val` in", values, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValNotIn(List<Integer> values) {
            addCriterion("`key_val` not in", values, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValBetween(Integer value1, Integer value2) {
            addCriterion("`key_val` between", value1, value2, "keyVal");
            return (Criteria) this;
        }

        public Criteria andKeyValNotBetween(Integer value1, Integer value2) {
            addCriterion("`key_val` not between", value1, value2, "keyVal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_int_key
    
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * Database table : tbl_int_key
    
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}